### ISSUE TITLE
Add Upsert functionality

### ISSUE THREAD

**Issue by NotoriousGOR** [SeaQL/sea-orm#1005]
## Motivation

It would be super helpful to have an `upsert function instead of manually writing out the select statement first, then using match to verify the record exists (lmk if there's a better way).

## Proposed Solutions

```
let happy_bakery = bakery::ActiveModel {
        name: ActiveValue::Set("Happy Bakery".to_owned()),
        profit_margin: ActiveValue::Set(0.0),
        ..Default::default()
    };
let res = Bakery::upsert(happy_bakery).exec(db).await?;
```

## Additional Information

There would need to be additional logic added for handling if insert vs updating like Prisma does in the Node.js world of things. I'm unsure how chaining would work here as I'm still super new to Rust.

**Comment by NotoriousGOR** [comment]
Didn't see this was built-in with Sea-Query, man great job guys!

**Comment by NotoriousGOR** [comment]
Doesn't seem to be a clean way to implement SeaQuery into SeaORM

**Comment by billy1624** [comment]
Hey @NotoriousGOR, welcome! Actually, we got upsert support in SeaORM. Please check https://www.sea-ql.org/SeaORM/docs/basic-crud/insert/#on-conflict
