### ISSUE TITLE
when installing sea 0.9.2 it generates this error

### ISSUE THREAD

**Issue by efrain2007** [SeaQL/sea-orm#1006]
![image](https://user-images.githubusercontent.com/65697999/187282029-996f2e56-124c-4327-abae-411ed18c3ffd.png)

**Comment by baoyachi** [comment]
repeat https://github.com/SeaQL/sea-orm/issues/875#issuecomment-1185238229

**Comment by billy1624** [comment]
Thanks!! @baoyachi

**Comment by baoyachi** [comment]
It's seems can be closed. @billy1624

**Comment by billy1624** [comment]
Thanks! @baoyachi
Hey @efrain2007, please reopen this if you still have questions about this
