### ISSUE TITLE
The RETURNING feature cannot be turned off when executing PG INSERT statements

### ISSUE THREAD

**Issue by step-baby** [SeaQL/sea-orm#1016]
## Description

I want to turned off The RETURNING syntax when executing PG INSERT statements. 
But I panic when I execute the following code.

``` rust
pub async fn insert(request: request::ActiveModel) -> Result<String> {
        let db = get_connection()?;
        let query = Query::insert()
            .into_table(Request::Table)
            .columns([Request::Id, Request::ReqId])
            .values_panic(vec!["1".into(), "12A".into()])
            .to_owned();

        // Some(ValueTuple::One(sea_orm::Value::String(Some(Box::new("1".to_string())))))
        let query = Inserter::new(None, query);

        let result: InsertResult<request::ActiveModel> = query.exec(db).await?;
        Ok(result.last_insert_id)
    }
``` 

``` text
called `Option::unwrap()` on a `None` value
thread 'tests::test_insert' panicked at 'called `Option::unwrap()` on a `None` value', /Users/yangjiaxin/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/sea-orm-0.9.2/src/executor/insert.rs:118:54
```

**Comment by billy1624** [comment]
Hey @step-baby, I'm not sure why you want to switch off returning but you can execute an insert with it like below.

```rs
let pear = fruit::ActiveModel {
    name: Set("Pear".to_owned()),
    ..Default::default()
};

let res: InsertResult = fruit::Entity::insert(pear) // Insert the `ActiveModel` directly without RETURNING expression
    .exec(db)
    .await?;
assert_eq!(res.last_insert_id, 28)
```

**Comment by step-baby** [comment]
Hey @billy1624 I , I tried the example you gave but still used the RETURNING syntax.
<img width="1408" alt="image" src="https://user-images.githubusercontent.com/50707849/188527764-02112b2f-0397-45c4-9f41-9cf81596a6c7.png">

**Comment by billy1624** [comment]
Okay. I think we should have change this part to execute insert without returning
- https://github.com/SeaQL/sea-orm/blob/d532deb6363d997beae029a8983d64c7e9574af6/src/executor/insert.rs#L102-L135

But i wonder why without RETURNING is important for your use case?

**Comment by step-baby** [comment]
This is because we want to use the SEA-ORM framework to connect PG and other databases, so we want to be able to use standard SQL without any database syntax.

Thank you for supplying us with INSERT statements not using the returning syntax ！！

**Comment by billy1624** [comment]
But SeaORM itself is agnostic to the database. Why not insert a record in SeaORM way?

```rs
let pear = fruit::ActiveModel {
    name: Set("Pear".to_owned()),
    ..Default::default() // all other attributes are `NotSet`
};

let pear: fruit::Model = pear.insert(db).await?;
```
https://www.sea-ql.org/SeaORM/docs/basic-crud/insert/#insert-one

I saw you construct the insert query manually above.

**Comment by billy1624** [comment]
Inside SeaORM `RETURNING` is only used if the target database support such syntax (i.e. only PostgreSQL). For MySQL and SQLite we will insert without `RETURNING`.

**Comment by step-baby** [comment]
I tried to insert records in SeaORM way ,but it used the RETURNING feature. I use SQL that I want to generate with SEA-ORM to connect to DAMeng database. This is done through a database agent that currently supports the standard SQL connection DAMENG.

**Comment by billy1624** [comment]
Oh wait. DAMeng database is a proprietary database hence we don't provide support for it. Is it compatible with PostgreSQL, MySQL or SQLite?

**Comment by step-baby** [comment]
I see that SEA-ORM compatible with the RETURNING feature. But I think this is an optional feature of the Postgres database, so it should be possible not to use it.

**Comment by tyt2y3** [comment]
I believe this have been solved https://docs.rs/sea-orm/latest/sea_orm/struct.Inserter.html#method.exec_without_returning
