### ISSUE TITLE
using .select_only().column() returns error

### ISSUE THREAD

**Issue by lidh15** [SeaQL/sea-orm#1026]
the bugged part is like:
```
for item in mytable::Entity::find()
  .select_only()
  .column(mytable::Column::MyColumn)
  .all(&db)
  .await
  .unwrap()
  .iter() { // do something }
```
error: thread tokio-runtime-worker panicked at called Result::unwrap() on an Error value: Query("no column found for name: my_another_column")

If I remove select_only() and column(), it works but very slow as it clearly queried the whole table.

**Comment by billy1624** [comment]
Hey @lidh15, welcome!! You need `into_model()` method for this. And you need to define a struct to hold your result as well. See https://www.sea-ql.org/SeaORM/docs/advanced-query/custom-select/#handling-custom-selects

**Comment by lidh15** [comment]
thank you!
