### ISSUE TITLE
`InsertResult` to return the primary key's type

### ISSUE THREAD

**Issue by tyt2y3** [SeaQL/sea-orm#103]
Currently, the `last_insert_id` from InsertResult simply uses the ExecResult's last_insert_id.
However, at least for Postgres with `returning`, we should be able to retrieve the primary key column for the Entity and return the value in its native type. For example, a `uuid` instead of an `i64`.

**Comment by billy1624** [comment]
How we handle composite primary keys?

**Comment by tyt2y3** [comment]
Composite primary keys can't be auto generated, and so it's less important. But I think the type could be a tuple, if we really try to support it. Let's leave it and return 0 for now.

**Comment by billy1624** [comment]
I think this issue can be related to #101 if we have an attribute `primary_key`. Then, we can derive a struct to represent value of returning columns (primary keys).

**Comment by billy1624** [comment]
And btw... returning statement in Postgres can return multiple columns at once.

https://www.postgresql.org/docs/current/dml-returning.html

**Comment by tyt2y3** [comment]
I think for the average case where there is only one column as primary key, adding one container layer is counter intuitive.
________________________________
寄件者: Billy Chan ***@***.***>
寄件日期: Tuesday, August 24, 2021 3:25:39 PM
收件者: SeaQL/sea-orm ***@***.***>
副本: Chris Tsang ***@***.***>; Author ***@***.***>
主旨: Re: [SeaQL/sea-orm] `InsertResult` to return the column's type, not i64 (#103)


I think this issue can be related to #101<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSeaQL%2Fsea-orm%2Fissues%2F101&data=04%7C01%7C%7C8b096f566ce241e1353908d966d06059%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637653867426180604%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=sHEIbMiU%2BlT4JeCWoorT4CNhfwnRuDgESLOkTXBLw9c%3D&reserved=0> if we have an attribute primary_key. Then, we can derive a struct to represent value of returning columns (primary keys).

**Comment by tyt2y3** [comment]
I think for the average case where there is only one column as primary key, adding one container layer is counter intuitive.
But perhaps, we can make an associated type def in the PrimaryKeyTrait

```rust
impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i32;
}
```

**Comment by billy1624** [comment]
Adding type def is a good suggestion
