### ISSUE TITLE
[FR] Use nested/shared enum for shared table fields

### ISSUE THREAD

**Issue by frederikhors** [SeaQL/sea-orm#1032]
I'm writing migrations and I have many entities that have the same `tenant_id`, `created_at`, `updated_at` fields in DB.

So I thought of using a nested enum to avoid repetition, like this (I'm very new to Rust):

```rust
pub enum Base {
    TenantId,
    CreatedAt,
    UpdatedAt,
}

enum Player {
    Base(Base),
    Table,
    Id,
    Name,
}

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .create_table(
                Table::create()
                    .table(Player::Table)
                    .if_not_exists()
                    .col(ColumnDef::new(Player::Base(Base::TenantId)).integer().not_null(),)
                    .col(ColumnDef::new(Player::Id).string().not_null().unique_key().primary_key())
                    .col(ColumnDef::new(Player::Name).string().not_null())
                    .to_owned(),
            )
            .await
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .drop_table(Table::drop().table(Player::Table).to_owned())
            .await
    }
}
```

It works!

But with this migration code the columns in the DB are:

```
base | id | name
```

and not

```
tenant_id | id | name
```

Is this possible to have `tenant_id` in this case?

**Comment by billy1624** [comment]
Hey @frederikhors, hi again! I think this is more related to SeaQuery's Iden? Anyways, I think you can add `#[iden(flatten)]` to achieve that.

```rs
#[derive(Iden)]
pub enum Base {
    TenantId,
    CreatedAt,
    UpdatedAt,
}

#[derive(Iden)]
enum Player {
    #[iden(flatten)]
    Base(Base),
    Table,
    Id,
    Name,
}
```

**Comment by ikrivosheev** [comment]
@billy1624 can you create issues in sea-query?

**Comment by billy1624** [comment]
Hey @ikrivosheev, what's the issue for? `[iden(flatten)]` is a existing feature. However, I think we can mention this feature alongside with other common feature such as renaming `[iden = "renamed"]` somewhere in the docs. E.g. README.md

**Comment by ikrivosheev** [comment]
> Hey @ikrivosheev, what's the issue for? `[iden(flatten)]` is a existing feature. However, I think we can mention this feature alongside with other common feature such as renaming `[iden = "renamed"]` somewhere in the docs. E.g. README.md

@billy1624 yes, you are right! Sorry, got a little confused...

**Comment by billy1624** [comment]
No worries :)
