### ISSUE TITLE
[FR] error[E0063]: missing fields `compact_format`, `database_schema`, `date_time_crate` and 7 other fields in initializer of `GenerateSubcommands`

### ISSUE THREAD

**Issue by frederikhors** [SeaQL/sea-orm#1046]
I'm trying to use `sea-orm-cli` (0.9.2) as library with the below code but I don't know how to initialize it without all the command's flags:

```rust
use sea_orm_cli::run_generate_command;

pub async fn gen() {
    run_generate_command(
        sea_orm_cli::GenerateSubcommands::Entity {
            database_url: "...connection_url...",
            output_dir: "./entities".to_string(),
            // compact_format: (),
            // expanded_format: (),
            // include_hidden_tables: (),
            // tables: (),
            // ignore_tables: (),
            // max_connections: (),
            // database_schema: (),
            // with_serde: (),
            // with_copy_enums: (),
            // date_time_crate: (),
        },
        true,
    )
    .await;
}
```

The error is:

```
error[E0063]: missing fields `compact_format`, `database_schema`, `date_time_crate` and 7 other fields in initializer of `GenerateSubcommands`
 --> src\seaorm.rs:6:9
  |
6 |         sea_orm_cli::GenerateSubcommands::Entity {
  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `compact_format`, `database_schema`, `date_time_crate` and 7 other fields
```

How to fix this?

Should we create a `new()` fn?

Can we `derive(Default)`?

**Comment by billy1624** [comment]
Hey @frederikhors, what's up :)

You can find the defaults here, search "default_value = ":
- https://github.com/SeaQL/sea-orm/blob/4e51b8837a7bcea418001bcab854613a5a61c525/sea-orm-cli/src/cli.rs#L84-L191

But I believe you have figured that out already hahaa
- https://github.com/SeaQL/sea-orm/issues/1047#issuecomment-1250139862

---

> Can we `derive(Default)`?

I don't think we should derive default at here. I'm not sure what's the end goal or what you want to achieve using the sea-orm-cli programmatically.

I think it's the best to program your own logic for the code generation part instead of relying on the sea-orm-cli to do it. That means you should depends directly on sea-orm-codegen like this:
- https://github.com/SeaQL/seaography/blob/003770beb6f085dd711019b426aedf501a10ab5a/generator/src/sea_orm_codegen.rs#L9-L19

**Comment by frederikhors** [comment]
I read (I'm still studying Rust) on [this SO answer](https://stackoverflow.com/questions/41510424/most-idiomatic-way-to-create-a-default-struct/41510505#41510505) that you can `derive(Default)` in order to initialize "configuration" structs (like this one) with a simpler code:

```rust
let conf = sea_orm_cli::GenerateSubcommands::Entity {
  database_url: "...database_url here...",
  output_dir: "./entities".to_string(),
  ..Default::default()
}
```

I think this is better than:

```rust
let conf = sea_orm_cli::GenerateSubcommands::Entity {
  database_url: "...database_url here...",
  output_dir: "./entities".to_string(),
  compact_format: false,
  expanded_format: false,
  include_hidden_tables: false,
  tables: None,
  ignore_tables: vec!["".to_string()],
  max_connections: 1,
  database_schema: "public".to_string(),
  with_serde: "none".to_string(),
  with_copy_enums: false,
  date_time_crate: DateTimeCrate::Time,
},
```

Is there another way?

Am I totally wrong?

**Comment by billy1624** [comment]
It's true we can implement `Default` for `GenerateSubcommands` enum. However, how do we provide default value for `database_url`? That's one thing holding me back.

Instead, can we rewrite `async fn run_generate_command`? Pull the logic of it out into another function. The function take a `database_url` and other optional options (with defaults).

**Comment by frederikhors** [comment]
I'm learning Rust... I can't answer. But I think the second is the way to go.

Anyway I think the `derive(Default)` uses empty string for `String` type, right? If yes I think the error will be "cannot connect to DB". 😄

**Comment by billy1624** [comment]
I'll try to create a PR for this tmr :)

**Comment by frederikhors** [comment]
Thank. BTW what I really need now is: https://github.com/SeaQL/sea-orm/discussions/992. If you have time... 😃

**Comment by billy1624** [comment]
I'll draft a PR for this issue then move on to https://github.com/SeaQL/sea-orm/discussions/992. Sorry for the delay

**Comment by frederikhors** [comment]
Yeah. I think we're good.
