### ISSUE TITLE
More compact Entity format

### ISSUE THREAD

**Issue by nappa85** [SeaQL/sea-orm#105]
I was trying your crate, seems promising, but the way you choose to represent models is too verbose.
For example I've a DB table with 53 fields, using your system I've written like 210 LOC, repeating the same informations like 3 times.

I think everything could be done with a single proc_macro, that takes a standard Rust struct and replaces it with a module with the same name of the struct, with Model struct with more or less the same contents of the original struct, Column enum with structs fields as variants, automatic impl ColumnTrait for Column with a type mapping, where the mapping fails you can use a field notation to override it (comes handy for custom types), table name and primary key can be specified with a struct notation, what's missing?
Relations, well, this have to be specified externally, but you can point the enum with another notation, and if the notation isn't present you generate a void enum.

After that, if I can add something more, I often use Cow on my entities, because this way I'm not forced to clone Strings when updating/creating. With your system I can't, because Model doesn't support a lifetime. It's not a big problem, but it blocks also other custom types with a lifetime

**Comment by Acidic9** [comment]
I haven't thought of this before, but I think I can agree with you somewhat.

For example, `Entity`, `Model`, `Column`, `PrimaryKey`, `PrimaryKeyTrait` & `ColumnTrait` could be combined into a single struct definition with derives.
From:
```rust
#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn schema_name(&self) -> Option<&str> {
        Some("public")
    }

    fn table_name(&self) -> &str {
        "users"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel)]
pub struct Model {
    pub id: Uuid,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub username: String,
    pub password: String,
    pub email: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    CreatedAt,
    UpdatedAt,
    Username,
    Password,
    Email,
}


#[derive(Copy, std::clone::Clone, std::fmt::Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Uuid.def(),
            Self::CreatedAt => ColumnType::Timestamp.def(),
            Self::UpdatedAt => ColumnType::Timestamp.def(),
            Self::Username => ColumnType::String(None).def(),
            Self::Password => ColumnType::String(None).def(),
            Self::Email => ColumnType::String(None).def().null(),
        }
    }
}
```
Into:
```rust
#[derive(Clone, Debug, PartialEq, SeaORM)]
#[schema_name = "public"]
#[table_name = "coupons"]
pub struct Model {
    #[primary_key]
    #[auto_increment = false]
    pub id: Uuid,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub username: String,
    pub password: String,
    pub email: Option<String>,
}
```
I think this wouldn't be too hard as a lot of information could be inferred from the struct.
For example:
- If a field is an `Option<T>`, then `.null()` would be added in the `ColumnTrait`
- The Column enum could be generated from the model's fields

Obviously with this comes a lack of customizability. But this could be solved by allowing manual implementations where needed perhaps?

**Comment by tyt2y3** [comment]
Thank you for your interest. I will first talk about the original ideas and choices, and may add more thoughts on later post.

The first thing is, I do not want to invent any DSL or anything with a custom syntax or semantics. It will definitely be much less verbose, but it is hard for anyone other than a code generator to write that code. It will be hard to understand and reason about, and people don't want to learn a new micro-language. Sooner or later, someone will have a need to customise the behaviour and hack the thing, and it will be much easier to do so in the plain Rust language.

(Just a small use case, how can I dynamically remap the table name based on environment variables?)

If there are tricks to reduce the verbosity of the Entity file without countering the above, I'll definitely adopt.

A lesser motivation would be code completion. List out the essential symbols and traits will be helpful.

**Comment by nappa85** [comment]
Yes, I understand your point of view, and it was exactly the reply I thought for the question "why didn't they already made this?".
But, as @Acidic9 pointed, there can be default impl via derive macro and custom impl in plain Rust without any problems.
As far as I can see, code completion works with macro-produced code without problems.
Macros aren't made to replace code, but to easy the life of who writes it.

For example, serde has a derive macro for Serialize and Deserialize, but anyone can manually derive the traits for non-standard situations, and there are lots of docs about it.

I would prefer a serde-like approach, where the default is easily reached with a macro, and non-default-fitting situations can be covered in plain Rust.

**Comment by tyt2y3** [comment]
I also think that having the use both CamelCase and snake_case when referring to attributes is slightly awkward.

Is it better or worse if we break the Rust convention to use snake_case enums?

**Comment by Acidic9** [comment]
I don't think so honestly, I think keeping the enum as CamelCase... and just renaming it through the derive macro

**Comment by tyt2y3** [comment]
Serde is a brilliant library and there is lot to learn and borrow from.

Yes I would prefer to have a more compact form, as long as it is compatible with the longer form.

And that the derive macro should not do too much magic other than providing syntax sugars.

**Comment by tyt2y3** [comment]
Also, it'd be better if we settle on a 'base format' first, and versions afterwards should be backward compatible.
That way, we can incrementally release enhancements towards the 'short format', while the codegen can maintain the capability to generate both formats.

**Comment by tyt2y3** [comment]
@Acidic9 the format you propose already looks good. Perhaps we just need to think about the relations.

**Comment by nappa85** [comment]
I've put together a minimal impl, have a look https://github.com/nappa85/sea-orm-macro/
Inside tests there is a working example.
Sure there is space for improvement, but it can be a starting point

**Comment by tyt2y3** [comment]
> I've put together a minimal impl, have a look https://github.com/nappa85/sea-orm-macro/
> Inside tests there is a working example.
> Sure there is space for improvement, but it can be a starting point

Wow thank you for the quick update. Looks great so far. I was just thinking how to name it (lol) perhaps, `AutoEntity`, `EntityDef`, or simply `Entity`?

**Comment by nappa85** [comment]
> Wow thank you for the quick update. Looks great so far. I was just thinking how to name it (lol) perhaps, `AutoEntity`, `EntityDef`, or simply `Entity`?

I've named it AutoColumn because it's main purpose is to generate Column from Model, but it generates optionally also Entity and PrimaryKey, so maybe a more generic AutoDef?

**Comment by tyt2y3** [comment]
Yeah `AutoDef` sounds good too.

**Comment by Acidic9** [comment]
I feel like `AutoDef` is a little ambiguous. For example, serde just has `Serialize` and `Deserialize`. I like the sound of `Schema` or `Entity` or `Table`

**Comment by tyt2y3** [comment]
Well, `Entity` is the most almighty I guess.

**Comment by tyt2y3** [comment]
@nappa85 we are releasing `0.2.0` soon.
Since you were working on this, do you think you will be able to contribute a bit in the coming month?
Such that we may incorporate and release in `0.3.0`

**Comment by nappa85** [comment]
Yes, if you let me know what you want me to edit, I'll do it ASAP

Here we discussed only the derive macro name

**Comment by Acidic9** [comment]
@tyt2y3 I spent most of my day yesterday and today creating a PR for this too. It's at a working stage, just need the columntrait to be generated too.

I'll create the PR in a few hours!

**Comment by tyt2y3** [comment]
> @tyt2y3 I spent most of my day yesterday and today creating a PR for this too. It's at a working stage, just need the columntrait to be generated too.
> 
> I'll create the PR in a few hours!

Thank you. After 0.2.0 we will make our focus on this matter, with 0.3.0 on the horizon of early Oct.

**Comment by tyt2y3** [comment]
> Yes, if you let me know what you want me to edit, I'll do it ASAP
> 
> Here we discussed only the derive macro name

Great, good to know. Thank you for the suggestion and everything up to now.

**Comment by Acidic9** [comment]
I've created a PR for this https://github.com/SeaQL/sea-orm/pull/122

If @nappa85 's version is preffered thats fine with me, just thought I'd share the work as a PR in case it can be used or to share any thoughts.

Let me know what you guys think

**Comment by tyt2y3** [comment]
> I've created a PR for this https://github.com/SeaQL/sea-orm/pull/122
> 
> 
> 
> If @nappa85 's version is preferred thats fine with me, just thought I'd share the work as a PR in case it can be used or to share any thoughts.
> 
> 
> 
> Let me know what you guys think

Thank you so much for the big PR. I think yours are promising!

@nappa85 What's your view on this?

@Acidic9 Can you show some more examples on the proposed format and annotation syntax?

**Comment by Acidic9** [comment]
@nappa85 I didn't get a chance to get an example working with your code, I'm not sure how exactly to use it. Do you think you could briefly explain what the API looks like for your version?

**Comment by nappa85** [comment]
> @nappa85 I didn't get a chance to get an example working with your code, I'm not sure how exactly to use it. Do you think you could briefly explain what the API looks like for your version?

you can find a working example in the tests folder of my repo https://github.com/nappa85/sea-orm-macro/blob/master/tests/it_works.rs

I can write some docs once we decided what has to be changed

**Comment by tyt2y3** [comment]
Thank you for everyone's input here. We will think a bit and perhaps draft a design document.

**Comment by nappa85** [comment]
I've wrote a little readme to better explain the proc macro: https://github.com/nappa85/sea-orm-macro/blob/master/README.md

**Comment by tyt2y3** [comment]
> I've wrote a little readme to better explain the proc macro: https://github.com/nappa85/sea-orm-macro/blob/master/README.md

Thank you, this is extremely helpful!

**Comment by tyt2y3** [comment]
So based on @nappa85 work, I have had something in mind:

## Basic usage

```rust
use sea_orm::EntityModel;

#[derive(EntityModel)]
struct Model {
    id: u64,
    name: String,
}
```

this will autogenerate the Column enum (omitted here).

## Primary key

To autogenerate the PrimaryKey enum too, simply add the attribute like this:

```rust
use sea_orm::EntityModel;

#[derive(EntityModel)]
struct Model {
    #[sea_orm(primary_key)]
    id: u64,
    name: String,
}
```

this will autogenerate the PrimaryKey enum, with implied `auto_increment = true`.

If we instead want `auto_increment = false`, we can specify:

```rust
#[sea_orm(primary_key, auto_increment = false)]
```

For composite primary key, we can annotate a column multiple times:

```rust
struct Model {
    #[sea_orm(primary_key)]
    id1: i32,
    #[sea_orm(primary_key)]
    id2: i32,
}
```

And auto_increment will be false automatically.

## Custom types

If your struct uses a non-basic type, you'll have to specify the SQL type for that column:
```rust
use sea_orm::EntityModel;

#[derive(EntityModel)]
struct Model {
    #[sea_orm(primary_key)]
    id: u64,
    #[sea_orm(column_type = "String(Some(255))", default_value = "new user")]
    name: MyName,
    #[sea_orm(default_expr = "gen_random_uuid()")]
    uuid: Uuid,
    #[sea_orm(column_type = "Char(Some(1))", unique, nullable)]
    admin: Option<MyBool>,
}
```

These will corresponds to the following column definitions:

```rust
ColumnType::String(Some(2555)).def().default_value("new user")
ColumnType::Uuid().def().default_expr("gen_random_uuid()")
ColumnType::Char(Some(1)).def().unique().null()
```

That said, two more methods will be added:
```rust
fn default_value(v: V) where V: IntoValue { ... }
fn default_expr(expr: &str) { ... }
```

Let's discuss a bit before putting this into implementation.

**Comment by tyt2y3** [comment]
Borrowing ideas from #122,

I think we can enhance the DeriveEntity macro:

```rust
#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
#[sea_orm(schema_name = "public", table_name = "posts")]
pub struct Entity;
```

```rust
impl EntityName for Entity {
    fn schema_name(&self) -> Option<&str> {
        Some("public")
    }

    fn table_name(&self) -> &str {
        "posts"
    }
}
```

**Comment by Acidic9** [comment]
I like what you've descirbed here @tyt2y3.

The sea-orm-cli generates also:
```rust
impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            _ => panic!("No RelationDef"),
        }
    }
}
```
And
```rust
impl ActiveModelBehavior for ActiveModel {}
```

Are these necessary? And should they be expanded from a derive macro also, or manually implemented?

If a table has no relation def, perhaps instead of the panic it should just not implement it? I've seen a few places where panics in the SeaORM source code could be replaced with error types or just adjustments to the types to ensure these are not possible at compile time.

**Comment by tyt2y3** [comment]
The problem here is the Entity requires an associated `Relation` type:

```rust
impl EntityTrait for Entity {
    type Model = Model;

    type Column = Column;

    type PrimaryKey = PrimaryKey;

    type Relation = Relation;
}
```

May be, it's possible for sea_orm to define an `NoRelation` struct so Entities with no relation can use that.
I am still not sure the impact to the rest of the library.

**Comment by Acidic9** [comment]
I think that would make sense.

> This design, I think, will decouple the `InsertModel` (`SimpleInput`) / `UpdateModel` (`SimpleUpdate`) problem.

I'm still thinking deeply about this.

Currently to perform an update on multiple fields, it looks like you do it with:
```rust
Fruit::update_many()
    .col_expr(fruit::Column::CakeId, Expr::value(Value::Null))
    .filter(fruit::Column::Name.contains("Apple"))
    .exec(db)
    .await?;
```
But if you want to update 10 columns, do you need to manually add `.col_expr` for each column?

And doing the following will update the pears name with the ID `123`.
```rust
let pear = pear::ActiveModel { 
    id: Set(123),
    name: Set("Green Pear".to_string()),
};
Fruit::update(pear).exec(db).await?;
```
The issue with this, is that if the id is not set, a panic will occur.
https://github.com/SeaQL/sea-orm/blob/de1f5d397df26659ef11ee9cc97251964503c748/src/query/update.rs#L89-97

But perhaps it'd make sense for the API to remove the lines 89 - 97 (in the link above) and force the user to explicitly add the `WHERE id = '...'` clause:
```rust
Fruit::update(pear)
    .filter(pear::Column::Id.eq(123))
    .exec(db).await?;
```
The benefit of this, is it allows users to write more complex filtering rather than a simple `id = ...`.
The down side is that if the ActiveModel has the ID as `Set`... then it'll actually try to update the ID in the query. But I don't consider this so much as a down side, because some people may actually want to update a primary key.

**Comment by tyt2y3** [comment]
## Relations

Similarly, we might also be able to simplify Relation definition a bit:

```rust
#[derive(EntityRelation)]
pub enum Relation {
    #[sea_orm(belongs_to = "super::cake::Entity", from = "Column::CakeId", to = "super::cake::Column::Id")]
    Cake,
}
```

auto generate the following:

```rust
impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Cake => Entity::belongs_to(super::cake::Entity)
                .from(Column::CakeId)
                .to(super::cake::Column::Id)
                .into(),
        }
    }
}
```

**Comment by tyt2y3** [comment]
> I'm still thinking deeply about this.

I am sorry @Acidic9 but it seems to be a bit off topic, perhaps we can discuss that in a new thread?

**Comment by tyt2y3** [comment]
@nappa85 what's your thought on the proposed design so far?

**Comment by nappa85** [comment]
I've just read everything and I have no objections, (aka "looks dope man!").
I've read in another issue (but actually I can't find it) about the ability to generate more than one Relation with another Entity, maybe we should integrate that too, I've felt this limitation myself

**Comment by tyt2y3** [comment]
@nappa85 
That issue is #89, and basically the `Linked` trait has been introduced in `0.2.0`

Can you open an PR with what you have got in sea-orm-macros for now, so we can work together?

**Comment by nappa85** [comment]
> Can you open a PR with what you have got in sea-orm-macros for now, so we can work together?

Sure, give me a moment

**Comment by nappa85** [comment]
Ok, I've created https://github.com/SeaQL/sea-orm/pull/128

**Comment by nappa85** [comment]
> That said, 3 more methods will be added:
> 
> ```rust
> fn default_value(self, v: V) where V: IntoValue { ... }
> fn default_expr(self, expr: &str) { ... }
> fn nullable(self) { ... }
> ```

Here you talk about adding those methods, are those already been added?

**Comment by billy1624** [comment]
> > That said, 3 more methods will be added:
> > ```rust
> > fn default_value(self, v: V) where V: IntoValue { ... }
> > fn default_expr(self, expr: &str) { ... }
> > fn nullable(self) { ... }
> > ```
> 
> Here you talk about adding those methods, are those already been added?

Not added yet.

**Comment by Acidic9** [comment]
@tyt2y3 @billy1624 @nappa85 Please see my updated PR https://github.com/SeaQL/sea-orm/pull/122.

I've updated the whole thing to match the specs listed here, with few changes such as the attribute being `#[sea( ... )]` instead of `#[sea_orm( ... )]`.

Please take a look and let me know your thoughts, I've explained in detail every change made in the PR :)

**Comment by Acidic9** [comment]
> > > That said, 3 more methods will be added:
> > > ```rust
> > > fn default_value(self, v: V) where V: IntoValue { ... }
> > > fn default_expr(self, expr: &str) { ... }
> > > fn nullable(self) { ... }
> > > ```
> > 
> > 
> > Here you talk about adding those methods, are those already been added?
> 
> Not yet added.

Although, there already exists: `.unique()`, `.null()`, `.index()` right?

**Comment by tyt2y3** [comment]
> @tyt2y3 @billy1624 @nappa85 Please see my updated PR #122.

Sure. I will definitely take a close look.

> Although, there already exists: .unique(), .null(), .index() right?

Yes. SeaQuery already has the `default_value` but not `default_expr`. I think we need to update SeaQuery first.

**Comment by nappa85** [comment]
> Although, there already exists: `.unique()`, `.null()`, `.indexed()` right?

So is it the old `null` or the new `nullable`?
Just to disambiguate...

**Comment by tyt2y3** [comment]
Yes, I think we should use `nullable` for consistency.

**Comment by nappa85** [comment]
> Yes, I think we should use the `nullable` method for consistency.

Perfect, so the macro code is already aligned

**Comment by tyt2y3** [comment]
Thank you everyone for everything!
I am now working on it. Hopefully will have something soon.

**Comment by tyt2y3** [comment]
I am done for today. Feel free to peek at the current status.

**Comment by tyt2y3** [comment]
I am thinking, whether DeriveEntityModel should automatically imply DeriveModel and DeriveActiveModel, to make it less verbose.

**Comment by nappa85** [comment]
> I am thinking, whether DeriveEntityModel should automatically derive DeriveModel and DeriveActiveModel, to make it less verbose.

Could be a good idea

**Comment by tyt2y3** [comment]
> I am thinking, whether DeriveEntityModel should automatically derive DeriveModel and DeriveActiveModel, to make it less verbose.

@billy1624 can you help a bit on this?

**Comment by nappa85** [comment]
> I am thinking, whether DeriveEntityModel should automatically derive DeriveModel and DeriveActiveModel, to make it less verbose.

I've made some tests about it, maybe I'm wrong, but it seems that a derive macro can't edit the original struct, to do so you need a proc-macro.

I've tried with this code, inside DeriveEntityModel macro:
```rust
    attrs.push(Attribute {
        pound_token: Pound(Span::call_site()),
        style: AttrStyle::Outer,
        bracket_token: Bracket(Span::call_site()),
        path: Path {
            leading_colon: None,
            segments: {
                let mut temp = Punctuated::new();
                temp.push(PathSegment {
                    ident: Ident::new("derive", Span::call_site()),
                    arguments: PathArguments::None,
                });
                temp
            },
        },
        tokens: quote! { DeriveModel, DeriveActiveModel },
    });
```

**Comment by Acidic9** [comment]
Rather than modifying the derive attribute of the struct itself, it's probably better to just reuse the code of `DeriveModel` and `DeriveActiveModel`.

For example, if they both use the struct approach, then you could just call them directly.
```rust
struct DeriveEntityModel {
    derive_model: DeriveModel,
    derive_entity_model: DeriveEntityModel,
    ...
}

impl DeriveEntityModel {
    fn new(input: syn::DeriveInput) -> syn::Result<Self, Error> {
        ...
    
        Ok(DeriveEntityModel {
            derive_model: DeriveModel::new(input)?,
            derive_entity_model: DeriveEntityModel::new(input)?,
            ...
        })
     }
     
     fn expand(&self) -> syn::Result<TokenStream> {
         let expanded_derive_model = self.derive_model.expand()?;
         let expanded_derive_entity_model = self.derive_entity_model.expand()?;
         ...
         
         Ok(TokenStream::from_iter([
            expanded_derive_model,
            expanded_derive_entity_model,
            ...
        ]))
     }
}
```

I hope that makes sense.

**Comment by billy1624** [comment]
Oh I just committed 54bb358 for this, feel free to comments :)

**Comment by Acidic9** [comment]
Ah yea you did the same as I explained haha, just call the function directly.

**Comment by nappa85** [comment]
> Oh I just committed [54bb358](https://github.com/SeaQL/sea-orm/commit/54bb358ccac5d6039dcd01f8ac1b70029e44caea) for this, feel free to comments :)

Are we ok with the macro always deriving the other macros?
All other features, like deriving PrimaryKey, were controlled by an attribute.

**Comment by billy1624** [comment]
> > I am thinking, whether DeriveEntityModel should automatically derive DeriveModel and DeriveActiveModel, to make it less verbose.
> 
> I've made some tests about it, maybe I'm wrong, but it seems that a derive macro can't edit the original struct, to do so you need a proc-macro.
> 
> I've tried with this code, inside DeriveEntityModel macro:
> 
> ```rust
>     attrs.push(Attribute {
>         pound_token: Pound(Span::call_site()),
>         style: AttrStyle::Outer,
>         bracket_token: Bracket(Span::call_site()),
>         path: Path {
>             leading_colon: None,
>             segments: {
>                 let mut temp = Punctuated::new();
>                 temp.push(PathSegment {
>                     ident: Ident::new("derive", Span::call_site()),
>                     arguments: PathArguments::None,
>                 });
>                 temp
>             },
>         },
>         tokens: quote! { DeriveModel, DeriveActiveModel },
>     });
> ```

This is crazy loll

**Comment by nappa85** [comment]
> This is crazy loll

Yeah, it was a really raw approach

**Comment by tyt2y3** [comment]
https://github.com/SeaQL/sea-orm/blob/98850295857274cc72bce390278ce5c1f5bd1582/tests/common/bakery_chain/customer.rs#L5-L11

@nappa85 I discovered a strange behavior. when `column_type` is specified, `nullable` can no longer be inferred from the `Option<_>` type

So the following is the correct:

```rust
#[sea_orm(column_type = "Text", nullable)]
pub notes: Option<String>,
```

But the following is not:

```rust
#[sea_orm(column_type = "Text")]
pub notes: Option<String>,
```

**Comment by tyt2y3** [comment]
https://github.com/SeaQL/sea-orm/blob/98850295857274cc72bce390278ce5c1f5bd1582/tests/common/bakery_chain/baker.rs#L13-L23

Our current `DeriveRelation` is quite 'copy & paste' now.

I am thinking if instead of

```rust

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::bakery::Entity",
        from = "Column::BakeryId",
        to = "super::bakery::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Bakery,
}
```

we do

```rust
#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "bakery",
        from = "bakery_id",
        to = "bakery.id",
        on_update = "cascade",
        on_delete = "cascade"
    )]
    Bakery,
}
```

**Comment by nappa85** [comment]
> https://github.com/SeaQL/sea-orm/blob/98850295857274cc72bce390278ce5c1f5bd1582/tests/common/bakery_chain/customer.rs#L5-L11
> 
> @nappa85 I discovered a strange behavior. when `column_type` is specified, `nullable` can no longer be inferred from the `Option<_>` type
> 
> So the following is the correct:
> 
> ```rust
> #[sea_orm(column_type = "Text", nullable)]
> pub notes: Option<String>,
> ```
> 
> But the following is wrong:
> 
> ```rust
> #[sea_orm(column_type = "Text")]
> pub notes: Option<String>,
> ```

Yes, it's kind-of wanted, IMHO if you're specifying the type, you've to specify it entirely

**Comment by nappa85** [comment]
> https://github.com/SeaQL/sea-orm/blob/98850295857274cc72bce390278ce5c1f5bd1582/tests/common/bakery_chain/baker.rs#L13-L23
> 
> Our current `DeriveRelation` is quite 'copy & paste' now.
> 
> I am thinking if instead of
> 
> ```rust
> #[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
> pub enum Relation {
>     #[sea_orm(
>         belongs_to = "super::bakery::Entity",
>         from = "Column::BakeryId",
>         to = "super::bakery::Column::Id",
>         on_update = "Cascade",
>         on_delete = "Cascade"
>     )]
>     Bakery,
> }
> ```
> 
> we do
> 
> ```rust
> #[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
> pub enum Relation {
>     #[sea_orm(
>         belongs_to = "bakery",
>         from = "bakery_id",
>         to = "bakery.id",
>         on_update = "cascade",
>         on_delete = "cascade"
>     )]
>     Bakery,
> }
> ```
> 
> But is this 'too much'?

I think it's becoming too much magic, what if the other entity isn't on the the parent module but it's on another crate?
The first version is better, more explicit

**Comment by Acidic9** [comment]
I agree that it's becoming a little bit too much magic. Perhaps the entire `DeriveRelation` can just be scrapped as it just implements `RelationTrait`..? I think it just makes sense at this point to let the user write their own implementation of it.

**Comment by tyt2y3** [comment]
> I agree that it's becoming a little bit too much magic. Perhaps the entire `DeriveRelation` can just be scrapped as it just implements `RelationTrait`..? I think it just makes sense at this point to let the user write their own implementation of it.

um... it does save a few lines and another impl block, innit?

> I think it's becoming too much magic, what if the other entity isn't on the the parent module but it's on another crate?
The first version is better, more explicit

Great, then seemingly everything is set now
