### ISSUE TITLE
sea-orm-cli generates invalid code when table name is a Rust keyword

### ISSUE THREAD

**Issue by andy128k** [SeaQL/sea-orm#1051]
## Description

I have a database with a table named `type`. When I run `sea-orm-cli` it generates syntactically invalid code.

- `mod type;` should be `mod r#type;`
- `use crate::type::Entity` should be `use crate::r#type::Entity`

## Steps to Reproduce

1. create a database with a table named `type` (probably any rust keyword gives the same resull)
2. `cargo new bug ; cd bug`
3. `sea-orm-cli generate entity -u mysql://user:pw@localhost/db -o entity/src`

### Expected Behavior

Generated code should be valid.

### Actual Behavior

Generated code does not compile.

```
error: expected identifier, found keyword `type`
  --> /.../entity/src/mod.rs:36:9
   |
36 | pub mod type ;
   |         ^^^^ expected identifier, found keyword
   |
help: escape `type` to use it as an identifier
   |
36 | pub mod r#type ;
   |         ++

error: expected identifier, found keyword `type`
  --> /.../entity/src/prelude.rs:34:18
   |
34 | pub use super :: type :: Entity as Type ;
   |                  ^^^^ expected identifier, found keyword
   |
help: escape `type` to use it as an identifier
   |
34 | pub use super :: r#type :: Entity as Type ;
   |                  ++

```

### Reproduces How Often

Always

## Versions

```
├── sea-orm v0.9.2
│   ├── sea-orm-macros v0.9.2 (proc-macro)
│   ├── sea-query v0.26.3
│   │   ├── sea-query-derive v0.2.0 (proc-macro)
│   │   ├── sea-query-driver v0.2.2 (proc-macro)
│   ├── sea-strum v0.23.0
│   │   └── sea-strum_macros v0.23.0 (proc-macro)
│   ├── sea-orm v0.9.2 (*)
```

## Additional Information

It seems like code generated by `DeriveRelation` macro also has this issue.

**Comment by billy1624** [comment]
Hey @andy128k, thanks for the report! Please check https://github.com/SeaQL/sea-orm/pull/1052#pullrequestreview-1113134896
