### ISSUE TITLE
Default value in array column.

### ISSUE THREAD

**Issue by Wiper-R** [SeaQL/sea-orm#1061]
The migration keeps suggesting me to add only u8 values in that.

Also there are no examples/documentation for .array().

**Comment by billy1624** [comment]
Hey @Wiper-R, welcome! Could you show me a code snippet? You can check this example on how to define a array column, https://github.com/SeaQL/sea-query/blob/a7f2defac169c93f9b6a059264d9ba52aebb9b43/examples/postgres/src/main.rs#L37.

Note that SeaORM doesn't support CRUD operations on array column.
- https://github.com/SeaQL/sea-orm/issues/576

**Comment by Wiper-R** [comment]
Thanks @billy1624 for efforts, I have already solved it by passing default array values as string `"{1, 2, 3, 4}"` Like this.

**Comment by billy1624** [comment]
Alright! No problem!
