### ISSUE TITLE
Seed data in migration without using ActiveModel?

### ISSUE THREAD

**Issue by billy1624** [SeaQL/sea-orm#1062]
### Discussed in https://github.com/SeaQL/sea-orm/discussions/1058

<div type='discussions-op-text'>

<sup>Originally posted by **gd87429** September 23, 2022</sup>
In https://www.sea-ql.org/SeaORM/docs/migration/seeding-data/ the insert statement is using `cake::ActiveModel`. But wouldn't that break functionality if the following happens:

1. Migration `#1` create a table with column `test_column`
2. Migraiton `#2` seeds data using `ActiveModel { test_column: whatever }`
3. Migration `#3` deletes column `test_column`
4. At this point `ActiveModel` does not contain `test_column`

Now when a **new** user runs all migrations for the first time, wouldn't migration `#2` break because up-to-date `ActiveModel` does not have column `test_column` anymore and therefore can't be referenced?

Is there a way to seed with data without using `ActiveModel` **and** without using raw SQL so it still works across all 3 db types?</div>

**Comment by tyt2y3** [comment]
I think the general approach is to embed a copy of the old entity in the migration crate
