### ISSUE TITLE
Type `i64` is used instead of `u64`

### ISSUE THREAD

**Issue by frederikhors** [SeaQL/sea-orm#1068]
I think I found a bug: I'm using the following code for a migration for a table with a field `ID` with Rust type `u64` and `bigint` in Postgresql.

But whether I use `.big_integer()` or `.big_unsigned()` or `.unsigned()` the result is always the same: `i64`.

```rust
fn id() -> ColumnDef {
  ColumnDef::new(Id)
    .big_unsigned()
    .not_null()
    .auto_increment()
    .unique_key()
    .to_owned()
}
```

Am I crazy or this is an error?

I'm using:

```toml
sea-orm-migration = "0.9.2"
sqlx = { version = "0.6.2", features = [
  "runtime-tokio-native-tls",
  "migrate",
  "postgres",
] }
```

**UPDATE**:

I correct myself: if I generate using `.big_unsigned()` it panics with:

```
thread 'main' panicked at 'not implemented', C:\Users\Fred\.cargo\registry\src\github.com-1ecc6299db9ec823\sea-query-0.26.3\src\backend\postgres\table.rs:239:26
```

Why is `big_unsigned()` excluded? How to generate `u64` as type for the `ID` field?

Isn't more logical to have an unsigned type for such a field?

**Comment by frederikhors** [comment]
**UPDATE**:

I correct myself: if I generate using `.big_unsigned()` it panics with:

```
thread 'main' panicked at 'not implemented', C:\Users\Fred\.cargo\registry\src\github.com-1ecc6299db9ec823\sea-query-0.26.3\src\backend\postgres\table.rs:239:26
```

Why `big_unsigned()` is excluded? How to obtain `u64` as type for the `ID` field?

Isn't more logical to have an unsigned type for such a field?

**Comment by tyt2y3** [comment]
There is no unsigned in Postgres

**Comment by frederikhors** [comment]
I would like to use big int in postgresql but `u64` in Rust for generated models.

**Comment by frederikhors** [comment]
This is an ORM for Go (superseeded by [Bun](https://bun.uptrace.dev)): https://pg.uptrace.dev/models/#column-names.

They are using `bigint` for `uint64`.

![image](https://user-images.githubusercontent.com/41120635/192146920-f9d69de1-b9d1-45a7-9fc7-14a45c174acb.png)

**Comment by frederikhors** [comment]
[Right now SeaORM is using `N/A` for PG `u64` column type](https://www.sea-ql.org/SeaORM/docs/generate-entity/entity-structure/#column-type).

Why can't we use `bigint`?

![image](https://user-images.githubusercontent.com/41120635/192147055-46510c5d-0a36-4288-b5e8-0908d8fc37b5.png)

**Comment by frederikhors** [comment]
Doing so it does not panic when I generate and I hope that I will use `u64` as a Rust type.

**Comment by billy1624** [comment]
Hey @frederikhors, all unsigned Rust type can't be used with PostgreSQL. Because PostgreSQL simply doesn't support unsigned integers and thus SQLx PostgreSQL driver doesn't support it as well.

You can compile the entity with unsigned fields defined in your SeaORM model but it will cause an runtime error. 
- https://github.com/SeaQL/sea-orm/blob/207e2df48470c2506272d83f2f91a884a553350c/src/executor/query.rs#L156-L159

Btw... I wonder why you need `u64`? Because `i64` isn't large enough for your use case?

**Comment by frederikhors** [comment]
Because this is what I'm using in Golang.

And also because it is logically more correct since an id can never be negative.

I don't understand why at all costs you want to map `u64` to an (nonexistent) `unsigned` on Postgresql.

As I wrote earlier, **can't we just map PG `bigint` to Rust `u64`?**

**Comment by billy1624** [comment]
> I don't understand why at all costs you want to map `u64` to an (nonexistent) `unsigned` on Postgresql.
> 
> As I wrote earlier, **can't we just map PG `bigint` to Rust `u64`?**

Okay, so, you mean, why don't we get `i64` from `QueryResult` then map it to `u64`? And we can do the same thing for `u32` as well.

Correct me if I'm wrong :)

**Comment by frederikhors** [comment]
I think we should do like `go-pg` or `bun` (two Golang ORM). They map PG `bigint` to Go `uint64`.

I need the `u64` in Rust (also for third party libs that are using `u64` and not `i64` for identifiers (ID fields)), I do not care about PG type.

I would like to be free to use the type I want in Rust and which obviously is mapped with the correct type on the DB that I have chosen to use.

**Comment by tyt2y3** [comment]
https://www.postgresql.org/docs/current/datatype-numeric.html

bigint	8 bytes	large-range integer	-9223372036854775808 to +9223372036854775807

it's range is only valid for i64, and using u64 is incorrect in Rust.

**Comment by tyt2y3** [comment]
If you want to, you can create a new type NonNegativeI64

**Comment by j-mendez** [comment]
using supabase @tyt2y3 you can use unsigned. We might want to open this open with a `feature` flag.
