### ISSUE TITLE
Generate m-to-m relations with sea-orm-cli

### ISSUE THREAD

**Issue by billy1624** [SeaQL/sea-orm#1074]
### Discussed in https://github.com/SeaQL/sea-orm/discussions/1066

<div type='discussions-op-text'>

<sup>Originally posted by **dorianim** September 24, 2022</sup>
Hey,

I am currently trying to create a many-to-many relation with sea-orm. I have defined according migrations with three tables, user, group and group_member.
I then ran the migrations and used `sea-orm-cli generate entity` to generate the entities. However, this only generates relations for user -> group_member -> group but not for user -> group as described [here](https://www.sea-ql.org/SeaORM/docs/relation/many-to-many/). Am I doing something wrong, or is this just not supported?

Regards,
Dorian</div>

**Comment by swwu** [comment]
In the meantime, are there any workarounds to using many-to-many relations while relying on auto-generated files created via `sea-orm generate entity`, other than modifying those files directly?
