### ISSUE TITLE
[FR] Get the `T` from `T::find_by_id()` instead of `Option<T>`

### ISSUE THREAD

**Issue by frederikhors** [SeaQL/sea-orm#1078]
I'm trying to understand if this is the way to go or if I'm wrong.

I'm using this code:

```rust
impl Repo for PgRepo {
    async fn player_by_id(&self, tenant_id: String, id: String) -> Result<Option<DomainPlayer>> {
        let player = Player::find_by_id((tenant_id, id))
            .one(&*self.db)
            .await?
            .map(|player| player.into());

        Ok(player)
    }
}
```

As you can see I'm using the signature: `Result<Option<DomainPlayer>>` because `Player::find_by_id()` returns `Option<Model>`.

I'm used to thinking in terms of error if a data cannot be found in the DB (ex: `NOT FOUND ERR!`).

And therefore all my other functions signatures do not include the `Option<T>`.

Is it possible to get `Result<T>` from `T::find_by_id()` instead of `Result<Option<T>>`?

**Comment by billy1624** [comment]
Hey @frederikhors, I think a "find one" method shouldn't throw an "not found", instead, it's a `Option<T>`. That's more natural, from my perspective. What you opinion on this?

**Comment by frederikhors** [comment]
Yeah. I think I'll have to get used to it. Thanks again for the great work you are doing!

**Comment by tyt2y3** [comment]
You can also use https://doc.rust-lang.org/core/option/enum.Option.html#method.unwrap_or_else and map to an Err
