### ISSUE TITLE
Wrong relationship generated for entities after alter statements

### ISSUE THREAD

**Issue by sjud** [SeaQL/sea-orm#1084]
## Description
Given two tables whose iden's have same named fields, that point to different tables. And those different tables that point back  (so that the relationship is one to one), an additional alter statement will be required to set the first table's keys to point to the other it might look like this 

```rust
let banter_key = TableForeignKey::new()
            .name("selected_transcript_file")
            .on_delete(ForeignKeyAction::SetNull)
            .from_tbl(EditBanters::Table)
            .from_col(EditBanters::SelectedTranscriptFile)
            .to_tbl(EditBanterFiles::Table)
            .to_col(EditBanterFiles::FileId)
            .to_owned();
        let banter_key_2 = TableForeignKey::new()
            .name("selected_audio_file")
            .on_delete(ForeignKeyAction::SetNull)
            .from_tbl(EditBanters::Table)
            .from_col(EditBanters::SelectedAudioFile)
            .to_tbl(EditBanterFiles::Table)
            .to_col(EditBanterFiles::FileId)
            .to_owned();
        let banter_alter = Table::alter()
            .table(EditBanters::Table)
            .add_foreign_key(&banter_key)
            .add_foreign_key(&banter_key_2)
            .to_owned();

        manager.alter_table(banter_alter).await?;

        let outro_key = TableForeignKey::new()
            .name("selected_transcript_file")
            .on_delete(ForeignKeyAction::SetNull)
            .from_tbl(EditOutros::Table)
            .from_col(EditOutros::SelectedTranscriptFile)
            .to_tbl(EditOutroFiles::Table)
            .to_col(EditOutroFiles::FileId)
            .to_owned();
        let outro_key_2 = TableForeignKey::new()
            .name("selected_audio_file")
            .on_delete(ForeignKeyAction::SetNull)
            .from_tbl(EditOutros::Table)
            .from_col(EditOutros::SelectedAudioFile)
            .to_tbl(EditOutroFiles::Table)
            .to_col(EditOutroFiles::FileId)
            .to_owned();
        let outro_alter = Table::alter()
            .table(EditOutros::Table)
            .add_foreign_key(&outro_key)
            .add_foreign_key(&outro_key_2)
            .to_owned();

        manager.alter_table(outro_alter).await?;

```
## What's wrong

What happens wrong is then after this gets applied then the entity generated for our Outros table has this relationship

```rust
    Self::EditBanterFiles2 => Entity::belongs_to(super::edit_banter_files::Entity)
                .from(Column::SelectedAudioFile)
                .to(super::edit_banter_files::Column::FileId)
                .into(),
            Self::EditBanterFiles1 => Entity::belongs_to(super::edit_banter_files::Entity)
                .from(Column::SelectedTranscriptFile)
                .to(super::edit_banter_files::Column::FileId)
                .into(),

```

## Steps to Reproduce
Create two tables who have columns that don't have foreign keys, but have each column share the same name.
Create two more tables that each point to a previous table.
Create one migration file where each table then points back.

### Expected Behavior
We expect each table to point to the table described in the alter statement, instead of pointing to the first table given in the first alter statement where the name of the column is shared.

### Actual Behavior

They point to the alter statement in the migration file. In the above example edit_banter_files

### Reproduces How Often

Yes.

## Versions

├── sea-orm v0.9.2
│   ├── sea-orm-macros v0.9.2 (proc-macro)
│   ├── sea-query v0.26.3
│   │   ├── sea-query-derive v0.2.0 (proc-macro)
│   │   ├── sea-query-driver v0.2.0 (proc-macro)
│   ├── sea-strum v0.23.0
│   │   └── sea-strum_macros v0.23.0 (proc-macro)
├── sea-orm-migration v0.9.2
│   ├── sea-orm v0.9.2 (*)
│   ├── sea-orm-cli v0.9.2
│   │   ├── sea-schema v0.9.3
│   │   │   ├── sea-query v0.26.3 (*)
│   │   │   └── sea-schema-derive v0.1.0 (proc-macro)
│   ├── sea-schema v0.9.3 (*)

## Additional Information

Will upload example after work day.
Also this bug is fixed by changing the names of the fields on the original tables, so that they are unique in the migration file where the alter statements are being applied.

**Comment by billy1624** [comment]
Hey @sjud, I move this issue to SeaORM. As it's more related to SeaORM.

I'm still a bit puzzled after reading. But yeah, let me know when you have uploaded the code somewhere. Thanks!!

**Comment by sjud** [comment]
> Hey @sjud, I move this issue to SeaORM. As it's more related to SeaORM.
> 
> I'm still a bit puzzled after reading. But yeah, let me know when you have uploaded the code somewhere. Thanks!!

Hi billy!
https://github.com/sjud/sea-orm-migration-later-generate-bug
If you look at the alter statement and then entity_dump you'll see that even though table_b should relate to other_table_b it relates to other_table_a

**Comment by tyt2y3** [comment]
I am sorry, but this example seems to be too big, and it's hard to guess what's the gist of the problem.
Please re-open if you have a minimally-reproducible example.
