### ISSUE TITLE
Implement `insert` & `update` for `ActiveModel`

### ISSUE THREAD

**Issue by billy1624** [SeaQL/sea-orm#110]
To avoid manually `exec` the insert `ActiveModel`. In below, we cannot simply `save` it because this is a junction table and the composite primary key should be set during insert.

https://github.com/SeaQL/sea-orm/blob/bfaa7d4539afc033cb3f240fa4fed4ff1344c7c0/tests/relational_tests.rs#L562-L569

Perhaps `impl` it here

https://github.com/SeaQL/sea-orm/blob/8cfa14233d2d6bce27857cce8b12a95be414d2cc/sea-orm-macros/src/derives/active_model.rs#L39-L47

**Comment by tyt2y3** [comment]
What is the final intended API?
I kind of get the problem, but I don't get the proposed solution.
