### ISSUE TITLE
Support for row locking?

### ISSUE THREAD

**Issue by nappa85** [SeaQL/sea-orm#111]
Hello, it's me again! xD

I just noticed there is no support for row locking (or at least I haven't find out).
Is it something you have excluded for a reason or simply you still haven't covered this feature?

**Comment by nappa85** [comment]
I think we can close this issue, since my PR has been merged, right?

**Comment by tyt2y3** [comment]
Well only the SeaQuery PR has been merged and since SeaORM bumped the dependency. So technically you can use it now.

It depends on whether you want additional convenience by introducing new API in SeaORM.

**Comment by nappa85** [comment]
> Well only the SeaQuery PR has been merged and since SeaORM has bumped the dependency, you can use it now.
> 
> It depends on whether you want additional convenience by introducing new API in SeaORM.

Oh, you're right, it's the sea-query PR that has been merged, not the sea-orm one
