### ISSUE TITLE
How can I see my deleted records in Gorm?

### ISSUE THREAD

**Issue by FurkanSamaraz** [SeaQL/sea-orm#1118]
How can I see my deleted records in Gorm?

**Comment by billy1624** [comment]
Hey @FurkanSamaraz, sorry for the delay. I'm not sure what do you mean. Are you asking how to perform similar operation that is available on Gorm but in SeaORM?

**Comment by FurkanSamaraz** [comment]
I found the answer thanks this is how i solved it.

func main() {
	db, _ := gorm.Open(sqlite.Open("data.db"), &gorm.Config{})

	// fetch with id
	//****
	var userid []User
	db.Unscoped().First(&userid, 2)
	fmt.Println(userid)
	//****
	
	// fetch all
	//****
	var users []User
	db.Unscoped().Find(&users).Unscoped()
	fmt.Println(users)
	//****
}
