### ISSUE TITLE
sea-orm-cli [Feature Request] Custom derives and attributes for entity generation

### ISSUE THREAD

**Issue by tsar-boomba** [SeaQL/sea-orm#1120]
I just finished setting up my first sea-orm project and really like it so far. I am requesting this feature because I want to derive traits on models generated by the cli without needing to do it manually. Additionally, users would need an `attribute` or `attr` (`--attribute ts(export)`) argument to add extra attributes to the struct. For example, if you run

```bash
sea-orm-cli generate entity --derive ts_rs::TS --attribute ts(export)
```

You would get a model like this

```rs
#[derive(Copy, Clone, Debug, PartialEq, DeriveEntityModel, ts_rs::TS)]
#[ts(export)]
pub struct Model {
    pub title: String,
    pub author: String,
}
```

I am ready and willing to contribute this feature if it is deemed worthy.

**Comment by tyt2y3** [comment]
A feature like that would be great!

I think there are too many command line options already, and I would like to introduce a `sea-orm-codegen.config.json` to store all codegen related options, which will be picked up by `sea-orm-cli` (via .env, explicitly).

**Comment by tsar-boomba** [comment]
So to be clear, I can add the arguments and necessary code to the codegen crate, but not the config file.

**Comment by billy1624** [comment]
> So to be clear, I can add the arguments and necessary code to the codegen crate, but not the config file.

The options should be added as usual, e.g. `--derive ts_rs::TS --attribute ts(export)`. And I'll create another PR to load the config for sea-orm-codegen. But that's another story :)
