### ISSUE TITLE
Why are my queries not fully inspectable?

### ISSUE THREAD

**Issue by frederikhors** [SeaQL/sea-orm#1130]
I'm trying to inspect for the first time a query created with SeaORM and I cannot see the values entirely.

I only see the query like this:

```sql
SELECT                       
  "player"."id",           
  "player"."coach_id",    
  "player"."email"
FROM                         
  "player"                 
WHERE                        
  "player"."coach_id" = $1
  AND "player"."state" = $2
LIMIT                        
  $3 OFFSET $4               
```

Is there a way to see it like the below instead?

```sql
SELECT                       
  "player"."id",           
  "player"."coach_id",    
  "player"."email"
FROM                         
  "player"                 
WHERE                        
  "player"."coach_id" = 123
  AND "player"."state" = 'active'
LIMIT                        
  5 OFFSET 5
```

**Comment by tyt2y3** [comment]
This is because the log you see is logged by sqlx and it's a cached prepared query. You can disable that and use SeaORM's logging which would have the parameters injected for display.

**Comment by alper** [comment]
I mean the tracing setup described there is what I took but still I get question marks in my queries.

**Comment by tyt2y3** [comment]
@billy1624 we might want to add one more paragraph on how to disable SQLx's logs.
