### ISSUE TITLE
Use the `log` crate instead of `"debug-print"` feature

### ISSUE THREAD

**Issue by Acidic9** [SeaQL/sea-orm#114]
Currently SeaORM uses a feature flag called "debug-print" which simple executes a `println` with the query.

It might be nice to use the [`"log"`](https://docs.rs/log/) / [`"env-logger"`](https://docs.rs/env_logger/) crates instead.

For example, replace
```rust
debug_print!("{}", stmt);
```
with
```rust
info!(target: "sea-orm-query", "{}", stmt);
```

The benefit of this is that apps using SeaORM can change logging through env vars rather than recompiling with a new feature flag.
For example:
```bash
$ RUST_LOG=sea-orm-query=info ./main
```

**Comment by tyt2y3** [comment]
Yes, I agree. It will be very helpful at deployment!
