### ISSUE TITLE
DeriveActiveEnum requires sea-query

### ISSUE THREAD

**Issue by inf0rm4tik3r** [SeaQL/sea-orm#1151]
At first, thank you for all your work on sea-orm! It is a fantastic addition to the Rust ecosystem ❤️ 

Upgrading to version `0.10.0`.

That version, being a release candidate, I think should have been named `0.10.0-rc1` or `0.10.0-beta1`, when following semver standards, so that people only looking at versions and not release notes don't get confused.

This change now requires that `sea-query` is added as a dependency (as `DeriveActiveEnum` seem to rely on that now) where it was previously possible to achieve this with just `sea-orm` as a dependency. Was this intentional?

**Comment by siketyan** [comment]
Related: #1143 

You can import sea_query via `use sea_orm::sea_query` to resolve without adding `sea_query` crate as a dependency.

**Comment by billy1624** [comment]
Hey @inf0rm4tik3r, thanks for the report!! @siketyan and I are working on fixing the issue.
- https://github.com/SeaQL/sea-orm/pull/1154

A new patch will be released shortly :)
