### ISSUE TITLE
sea-orm-cli Add option for #[serde(skip_deserializing)] on primary key

### ISSUE THREAD

**Issue by tsar-boomba** [SeaQL/sea-orm#1159]
## Motivation

Currently, it is recommended to skip the deserialization of the primary key of an entity. This has to be manually added to generated entities.

## Proposed Solutions

1. Allow adding `#[serde(skip_deserializing)]` to primary keys through a cli option.
2. If they use `both` or `deserialize` option, it should be included automatically.
3. Some combination, where you have an option that overrides the automatic (`--no-skip-deserialize`)

**Comment by trueb2** [comment]
This looks a lot like #961 to me

**Comment by tsar-boomba** [comment]
It'd be great if you or could add this.

**Comment by tsar-boomba** [comment]
Closing as duplicate of #841.
