### ISSUE TITLE
BigDecimal support

### ISSUE THREAD

**Issue by mattiecnvr** [SeaQL/sea-orm#1167]
## Description

Currently the implementation of SeaORM's `Decimal` type supports a max of 96 bit integers which is a serious limitation on the decimal type which is supposed to support near arbitrarily sized decimals.

## Additional Information

Postgres supports decimals of up to 131072 digits before the decimal and 16383 digits after the decimal (base 10) which is significantly different in scale than a 96 bit integer. For our specific use case, we only need 256 bit integers, but I do not at this time see any way to do this with the ORM.

**Comment by billy1624** [comment]
Hey @mattiecnvr, welcome!! I wonder which crate did you choose to represent such a large Postgres decimals you mentioned above?

**Comment by tyt2y3** [comment]
BigDecimal is supported in SeaQuery, but not SeaORM.
