### ISSUE TITLE
Use `SeaORM` instead of SeaORM in comment

### ISSUE THREAD

**Issue by frederikhors** [SeaQL/sea-orm#1173]
Using `clippy:doc_markdown` which is included in `clippy:pedantic` it warns if this (the actual comment) is used:

```rust
//! SeaORM Entity. Generated by sea-orm-codegen 0.9.3
```

instead of:

```rust
//! `SeaORM` Entity. Generated by sea-orm-codegen 0.9.3
```

What do you think to change it?

**Comment by billy1624** [comment]
Hey @frederikhors, the `clippy:doc_markdown` lint is allowed by default. But just in case, yeah, I agree changing it to ticked `SeaORM`.

Would you like to submit a PR and update it?
