### ISSUE TITLE
sea-orm-cli: reference to a CREATE'd TYPE inside a schema not on search_path leads to database error

### ISSUE THREAD

**Issue by Yuubari** [SeaQL/sea-orm#1179]
## Description
When `sea-orm-cli generate entity -s schema_name` is used, the schema is not on search_path, and a type created with `CREATE TYPE` is used somewhere in the schema, `sea-orm-cli` fails with a database error.

## Steps to Reproduce

1. Have a `CREATE TYPE schema.sometype AS ENUM (…)` in your schema and have a column use this type:
```sql
CREATE SCHEMA mediawiki;

CREATE TYPE mediawiki.media_type AS ENUM (
    'UNKNOWN',
    'BITMAP',
    'DRAWING',
    'AUDIO',
    'VIDEO',
    'MULTIMEDIA',
    'OFFICE',
    'TEXT',
    'EXECUTABLE',
    'ARCHIVE',
    '3D'
);

CREATE TABLE mediawiki.uploadstash (
    us_media_type mediawiki.media_type,
);
```
2. Run `sea-orm-cli generate entity -s mediawiki` (or with `DATABASE_SCHEMA=mediawiki`) without altering `search_path`.

### Expected Behavior

With the schema name provided, references within that schema should (at least partially, ignoring the panic in the example below) work, like when you modify `search_path`:
```
% DATABASE_URL="postgresql://seatest@db/seatest?options=-c search_path%3Dmediawiki" sea-orm-cli generate entity -o . -s mediawiki
Generating uploadstash.rs
    > Column `us_media_type`: Option<MediaType>
thread 'main' panicked at '"3d" is not a valid Ident', /home/xiatian/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-1.0.47/src/fallback.rs:756:9
```
(Free bonus: includes #1172.)

### Actual Behavior

Sea-ORM seems to strip schema name from references and executes the query without the schema qualifier:

```
% DATABASE_URL="postgresql://seatest@db/seatest" sea-orm-cli generate entity -o . -s mediawiki
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Database(PgDatabaseError { severity: Error, code: "42704", message: "type \"media_type\" does not exist", detail: None, hint: None, position: None, where: None, schema: None, table: None, column: None, data_type: None, constraint: None, file: Some("parse_type.c"), line: Some(793), routine: Some("parseTypeString") })', /home/xiatian/.cargo/registry/src/github.com-1ecc6299db9ec823/sea-schema-0.10.2/src/postgres/discovery/executor/real.rs:29:14
```

### Reproduces How Often

Always reproducible.

## Versions

0.10.1.

## Additional Information

With the above schema with default PostgreSQL settings, attempting to run `sea-orm-cli` should be enough to reproduce the issue.

**Comment by billy1624** [comment]
Hey @Yuubari, thanks for the investigation. I just changed the CLI, when initializing the Postgres connection we will always set the search path. See https://github.com/SeaQL/sea-orm/pull/1212 for the fix.

**Comment by Yuubari** [comment]
I often wonder if explicit schema naming would be ‘more correct’ for PostgreSQL, as nothing really prevents you from doing cross-schema queries (and schema elements in different schemata can have identical identifiers).

**Comment by billy1624** [comment]
I think it's safer to prefix everything with schema if you have more than one schema on the database. But it might compromise readability.

**Comment by cbio-jimmy** [comment]
Hello, I had a question regarding this. I'm still unable to use any enums since the schema name isn't prexing to the enum_name.

I can create a issue for this if this isn't a simple question.

The generated code looks like
```rust
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "some_name")]
```

I'm expecting it to look like
```rust
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "schema.some_name")]
```

Since the schema isn't added on to the enum name, any calls to the enum fails when creating a transaction with the database. 

An example enum from sql looks like
```sql
create type schema.location as enum('USA', 'KOR');
```
