### ISSUE TITLE
Joins only support up to 3 composite keys

### ISSUE THREAD

**Issue by ctrlaltdel85** [SeaQL/sea-orm#1182]
## Description
I have a project which requires a join on 4 composite keys, but only up to 3 will compile. Furthermore, there's no way to specify a composite key with the belongs_to macro. The same issue occurs when implementing RelationTrait.
The error I get is:

error[E0271]: type mismatch resolving `<packages::Entity as sea_orm::EntityTrait>::Column == (packages::Column, packages::Column, packages::Column, packages::Column)`

## Steps to Reproduce

The query looks like this:

    let query = A::find()
        .join(
            JoinType::InnerJoin,
            TableA::Entity::belongs_to(TableB::Entity)
                .from((
                    TableA::Column::Col1,
                    TableA::Column::Col2,
                    TableA::Column::Col3,
                    TableA::Column::Col4,
                ))
                .to((
                    TableB::Column::Col1,
                    TableB::Column::Col2,
                    TableB::Column::Col3,
                    TableB::Column::Col4,
                ))
                .into(),
        )

## Additional Information

It looks like this could be fixed by extending identity.rs to support more operations. Is there any way around this problem?

**Comment by billy1624** [comment]
Hey @ctrlaltdel85, welcome!! Correct, under the current architecture we need to add `Quaternary`, `Quinary` and perhaps `Senary`. Another way could be rewrite it and take a dynamic `Vec<DynIden>`.

**Comment by tyt2y3** [comment]
merge into 1294
