### ISSUE TITLE
[PIP] Simple data loader

### ISSUE THREAD

**Issue by tyt2y3** [SeaQL/sea-orm#1191]
I could not think of a good enough API for the 'complex' dataloader yet, but I figured we could ship something incremental.

The problem's gist is not SQL, it's more about the rigid type system in Rust.

Anyway, lets take a look at `ModelTrait`:

```rust
trait ModelTrait {
    ...
    fn find_related<R>(&self, _: R) -> Select<R>
    where
        R: EntityTrait,
        Self::Entity: Related<R>,
    {
        <Self::Entity as Related<R>>::find_related().belongs_to(self)
    }
    ...
}
```

It allows one to find any related entity of a given model.

What we would offer, is a 'vectorized' version of it, meaning given a vec of models we can load all related models of a given relation in one batch.

```rust
impl LoaderTrait for Vec<M>
where M: ModelTrait {
    async fn load_one<R>(&self, _: R) -> Result<Vec<R::Model>>
    where
        R: EntityTrait,
        M::Entity: Related<R>,
    {
        // we should verify this is a has_one relation
    }

    async fn load_many<R>(&self, _: R) -> Result<Vec<Vec<R::Model>>>
    where
        R: EntityTrait,
        M::Entity: Related<R>,
    {
        // we should verify this is a has_many relation
    }
}
```

What the simple loader do under the hood:

1. load all related entities with a subquery
```sql
SELECT [related entity's columns] FROM [related entity table] WHERE [primary key] IN (
    SELECT [related entity's primary key] FROM [relation table, might be parent table or a junction table] WHERE [parent entity primary key] IN ([the list of entity provided to Loader])
)
```
2. aggregate these Models according to the input models's primary key (a hash map would be needed as an intermediate step)
2.1. we should assume that the related entity might be shared; i.e. A1 & A2 both relates to B1, we will only get one B1, so we have to clone it

With this new API, we can now:

```rust
let cakes: Vec<cake::Model> = Cake::find().all(db).await?;
let fruits: Vec<Vec<fruit::Model>> = cakes.load_many(Fruit).await?;
// more relations

// So we can consume them
for (cake: cake::Model, fruits: Vec<fruit::Model>) in std::iter::zip(cakes, fruits) {
    // fruits in this scope belong to cake
}
```

In the end, this would allow us to cascade-load multiple relations eagerly.

**Comment by tyt2y3** [comment]
@karatakis are you interested in working on this?

**Comment by karatakis** [comment]
@tyt2y3 I can work on it. Please assign me on this issue :)

**Comment by karatakis** [comment]
@tyt2y3 I started approaching the solution
Here you can view the progress https://github.com/karatakis/sea-orm/commit/f87f6a8e711f493dadfa49140ab8064e5e735bb6

The trait so far grew to this. The type system is too verbose :scream:

```rust
#[async_trait::async_trait]
pub trait LoaderTrait {
    type Model: ModelTrait;

    async fn load_one<R, C>(&self, db: &C) -> Result<Vec<Option<R::Model>>, DbErr>
    where
        C: ConnectionTrait,
        R: EntityTrait,
        R::Model: Send + Sync,
        <<R as EntityTrait>::Column as FromStr>::Err: Debug,
        <<Self as LoaderTrait>::Model as ModelTrait>::Entity: Related<R>,
        <<<<Self as LoaderTrait>::Model as ModelTrait>::Entity as EntityTrait>::Column as FromStr>::Err: Debug;

    async fn load_many<R, C>(&self, db: &C) -> Result<Vec<Vec<R::Model>>, DbErr>
    where
        C: ConnectionTrait,
        R: EntityTrait,
        R::Model: Send + Sync,
        <<R as EntityTrait>::Column as FromStr>::Err: Debug,
        <<Self as LoaderTrait>::Model as ModelTrait>::Entity: Related<R>,
        <<<<Self as LoaderTrait>::Model as ModelTrait>::Entity as EntityTrait>::Column as FromStr>::Err: Debug;
}
```

**Comment by tyt2y3** [comment]
It's actually not that bad. Although I think `::Err: Debug` are not needed?
`std::Error` should have had `Debug + Display` already.
