### ISSUE TITLE
simplify specific db errors matching

### ISSUE THREAD

**Issue by Samiisd** [SeaQL/sea-orm#1194]
## Motivation

Currently, matching DB specific errors is highly verbose, and I believe some common errors could benefit from being simplified. Current solution is the following: https://github.com/SeaQL/sea-orm/discussions/1152

E.g.
```rust
match user::Entity::insert_many(models).exec(&state.db).await {
    Err(DbErr::Query(RuntimeErr::SqlxError(sqlx::Error::Database(e))))
        if e.code().unwrap().eq("23505") =>
    {
        // 23505 is postgresql error code for violation on column unique constraint
        Ok()
    }
    Err(e) => Err(e),
    Ok(_) => Ok()
}
```

## Proposed Solutions

I don't know every use cases and common errors, but I believe this ORM would benefit from simplifying error handling. 
Another generic enum error could be created + custom DB error mapping logic to this newly created enum.

E.g.
```
enum DbErr {
     ForeignKeyViolation { column: String, key: int },
     NotNullViolation { column: String },
     UniqueViolation { column: String },
     ...
}
```

**Comment by tyt2y3** [comment]
See: https://github.com/SeaQL/sea-orm/pull/1040#issuecomment-1272536790

**Comment by billy1624** [comment]
Closed by https://github.com/SeaQL/sea-orm/pull/1707
