### ISSUE TITLE
Composite key cursor pagination is broken

### ISSUE THREAD

**Issue by jacob-pro** [SeaQL/sea-orm#1209]
## Description

The SQL generated by the `Cursor` struct when using composite keys is incorrect and leads to missed results when paginating. The problem is that the [WHERE clause is incorrect, it can only currently work if it just so happens that your two columns naturally followed the exact same ordering](https://github.com/SeaQL/sea-orm/blob/b9a07ee538239b3f769608073ba5c438f93a72da/src/executor/cursor.rs#L445-L446).

## Example

Lets say you have the following table:

| ID | Category |
|----|----------|
| 1  | B        |
| 2  | B        |
| 3  | A        |
| 4  | C        |
| 5  | A        |
| 6  | A        |
| 7  | C        |
| 8  | B        |
| 9  | A        |

Now lets say you want to paginate by category, category isn't unique so in order to page you need to combine with the ID column into a unique composite key. 

The SQL to fetch the first page would look like:

Lets query the first 3 results:

```sql
SELECT * FROM example
ORDER BY category ASC, id ASC
LIMIT 3
```

Which returns:

| ID | Category |
|----|----------|
| 3  | A        |
| 5  | A        |
| 6  | A        |

Now we want to get the next page, according to the [current implementation](https://github.com/SeaQL/sea-orm/blob/b9a07ee538239b3f769608073ba5c438f93a72da/src/executor/cursor.rs#L445-L446) this creates a query like:

```sql
SELECT * FROM example
WHERE category > 'A' AND id > 6
ORDER BY category ASC, id ASC
LIMIT 3
```
But this is wrong - we would end up only getting two more results, missing out many inbetween

| ID | Category |
|----|----------|
| 8  | B        |
| 7  | C        |

We need to actually have a query like:

```sql
SELECT * FROM example
WHERE (category = 'A' and id > 6) OR category > 'A'
ORDER BY category ASC, id ASC
LIMIT 3
```

which produces:

| ID | Category |
|----|----------|
| 9  | A        |
| 1  | B        |
| 2  | B        |

## Three Columns

Lets say you have 3 columns "x", "y", "z", then the WHERE clause needs to look like:

```sql
WHERE ("x"= X AND "y" = Y AND "z" > Z) OR ("x" = X AND "y" > Y) OR "x" > X
```

## Versions

Present in master

## Related To

- https://github.com/SeaQL/sea-orm/issues/300
- https://github.com/SeaQL/sea-orm/pull/754
- https://github.com/SeaQL/sea-orm/pull/822

@tyt2y3  @billy1624 @Sytten @ikrivosheev

**Comment by Sytten** [comment]
Interestingly this is the same technique used when you have a single column key but you want to order the result set by a column. Having a generic solution could be reused for both use cases.

**Comment by tyt2y3** [comment]
@billy1624 I am going to give this a try if you are not working on it already

**Comment by billy1624** [comment]
Hey @tyt2y3, please proceed

**Comment by holmofy** [comment]
[composite type comparison](https://www.postgresql.org/docs/current/functions-comparisons.html#COMPOSITE-TYPE-COMPARISON) is a good solution.

```sql
SELECT val1, val2, val3, id
FROM sortme
WHERE (val1, val2, id) > (1, '2024-01-01 01:00:00+01', 920198)
ORDER BY val1, val2, id
LIMIT 50;
```

**Comment by Sytten** [comment]
@holmofy This is not enough, you have to deal with the case where the order column is equal and nulls too. The document you link is a good resource though. Cursor pagination is very hard to get right especially multi-column
