### ISSUE TITLE
Says `DeriveRelation` does impl `Related` but it doesn't

### ISSUE THREAD

**Issue by TheAwiteb** [SeaQL/sea-orm#1222]
version: 0.10.2

In the [documentation](https://www.sea-ql.org/SeaORM/docs/relation/one-to-many/) it says `DeriveRelation` does impl `Related` but it doesn't

**Comment by billy1624** [comment]
Hey @TheAwiteb, welcome and sorry for the confusion. I'll update the docs now.

The `DeriveRelation` will only expanded into:

```rs
impl RelationTrait for Relation {
    // ...
}
```

That means you still need to manually implements `Related`:

```rs
impl Related<...> for Entity {
    fn to() -> RelationDef {
        // ...
    }
}
```

**Comment by billy1624** [comment]
Hey @TheAwiteb, I just updated the docs. Thanks for the feedback once again!
