### ISSUE TITLE
Alphabetical order generating with `sea-orm-cli`

### ISSUE THREAD

**Issue by frederikhors** [SeaQL/sea-orm#1223]
## Description

Using `sea-orm-cli` to generate entities I found out that the order of relations is random, not alphabetical.

### Expected Behavior

I would like it to be alphabetical.

### Actual Behavior

Sometimes it generates:

```rust
#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::company::Entity",
        from = "Column::CompanyId",
        to = "super::company::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Company,
    #[sea_orm(has_many = "super::player::Entity")]
    Player,
    #[sea_orm(has_many = "super::team::Entity")]
    Team,
    #[sea_orm(has_many = "super::coach::Entity")]
    Coach,
}
```

Sometimes instead:

```rust
#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::company::Entity",
        from = "Column::CompanyId",
        to = "super::company::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Company,
    #[sea_orm(has_many = "super::player::Entity")]
    Player,
    #[sea_orm(has_many = "super::coach::Entity")]
    Coach,
    #[sea_orm(has_many = "super::team::Entity")]
    Team,
}
```

### Reproduces How Often

Yeah

## Versions

```log
sea-orm-cli 0.10.2
```

**Comment by tyt2y3** [comment]
That's right. Non-determinism is sometimes annoying. I am 99% this is due to the pseudo-random seed of HashMap being used. The solution usually is to replace all HashMap with BTreeMap and so it will order naturally by the key.

**Comment by billy1624** [comment]
Hey @frederikhors, thanks for the report!! I'll dig into it :)

**Comment by billy1624** [comment]
Hey @frederikhors, please check https://github.com/SeaQL/sea-orm/pull/1229

**Comment by frederikhors** [comment]
I think it should work. I cannot try it right now. Thanks!
