### ISSUE TITLE
Support configuring `MockDatabase` to return `DbError` on all types of operations against it.

### ISSUE THREAD

**Issue by robot-head** [SeaQL/sea-orm#1235]
## Motivation

With the addition of fine-grained database errors added in `0.10` release, we've written some application code to respond to different errors intelligently.  We'd like to unit test this code.  Currently we have found no way to configure `MockDatabase` to return a `DbErr` for a query result or an execution result.

## Proposed Solutions

Wrap the input to `append_exec_results` and `append_query_results` to accept Result variants instead of just raw values?  

```rust
    /// Add the [MockExecResult]s to the `exec_results` field for `Self`
    pub fn append_exec_results(mut self, mut vec: Vec<MockExecResult>) -> Self {
        self.exec_results.append(&mut vec);
        self
    }

    /// Add the [MockExecResult]s to the `exec_results` field for `Self`
    pub fn append_query_results<T>(mut self, vec: Vec<Vec<T>>) -> Self
    where
        T: IntoMockRow,
    {
        for row in vec.into_iter() {
            let row = row.into_iter().map(|vec| vec.into_mock_row()).collect();
            self.query_results.push(row);
        }
        self
    }
```

**Comment by tyt2y3** [comment]
You are right little thought has been put into the Mock API for this change.
What we can do: add two new methods `append_exec_error` and `append_query_error`.
(I think it will be too bad to break the current API now)
And I think the internals of `MockDatabase` needs a bit rework and testing as well.

**Comment by robot-head** [comment]
Sounds good to me!  Thanks, the ability to write detailed unit tests is my favorite part of this library
