### ISSUE TITLE
Missing method "find_with_linked"

### ISSUE THREAD

**Issue by nitnelave** [SeaQL/sea-orm#1242]
## Motivation

We have `find_with_related` and `find_also_linked`, but there's no `find_with_linked`.
For instance, I want to get all users who are in a group whose name is "admin" (not primary key). I have a "membership" table for the N-N relation. I would want to write:

```rust
User::find().find_also_linked(Group).filter(Group::Column::Name.eq("admin")).all(db).await?;
```

Then there's also the question of inner join vs left join. I know the answer is probably going to be pointing me to https://www.sea-ql.org/SeaORM/docs/advanced-query/custom-select/, but it's just a seemingly missing part of the API.

**Comment by nitnelave** [comment]
Somewhat related, but I'm looking to get a `Vec<(User, Vec<Group>)>`.

**Comment by nitnelave** [comment]
Actually, I was looking at the custom-select page, and even with custom joins and so on, I can't figure out how to get a `Vec<(User, Vec<Group>)>`: You can't derive `FromQueryResult` for a struct with `Vec` inside, and I'm not sure how to aggregate across rows.

**Comment by nitnelave** [comment]
So, from what I understand, the only way to do it given the current code (if we want to leverage the link) is to use `find_also_linked` and then post process the results: we'll get a `(User, Some(Group))` for each pair of (user, group), plus a `(User, None)` for users without groups. If we sort by user, they'll be correctly grouped and we can do some stream processing. Not the prettiest but it works. I still feel like this should be done by the framework.

**Comment by tyt2y3** [comment]
I think this omission is not intentional and this can be added.
@billy1624 I think it should be a matter of refactoring into `prepare_select_two_for_linked` and construct a `SelectTwoMany`?

**Comment by tyt2y3** [comment]
Closed by https://github.com/SeaQL/sea-orm/pull/1743
