### ISSUE TITLE
sea-orm-cli generate entity --tables argument doesn't work as described

### ISSUE THREAD

**Issue by johnbcodes** [SeaQL/sea-orm#1243]
## Description

`sea-orm-cli generate entity --tables` says that it takes a comma-separated list of tables to generate entities for.

```
    -t, --tables <TABLES>
            Generate entity file for specified tables only (comma separated)
```

However, the Clap [definition](https://github.com/SeaQL/sea-orm/blob/80c81eaffe4635303c4d854a8f1d0effef86a6d8/sea-orm-cli/src/cli.rs#L136) uses `Option<String>` instead of `Vec<String>`. All tables after the first comma are ignored.

If the intent is to support multiple tables, the change is small and doesn't harm the single table use case. If the intent is to only generate a single entity, then I think the help should be updated. Either way I'm willing to do the work once I know.

## Steps to Reproduce

1. Create a database with `ledger_entries` and `checks` tables
2. Execute `sea-orm-cli generate entity -u <DATABASE_URL> --tables ledger_entries,checks -o src/entities`

### Expected Behavior

Generates entities for the `ledger_entries` and `checks` tables

### Actual Behavior

Only generates entity for `ledger_entries`

### Reproduces How Often

Always

## Versions

0.10.3
SQLite
Mac OS 12.6

**Comment by tyt2y3** [comment]
It should be able to support multiple tables AFAIK @billy1624

**Comment by billy1624** [comment]
Hey @johnbcodes, thanks for the report!! I'm not sure why it was originally be implemented this way. The original approach takes a comma separated table name and then conditionally generate entity of those with table name is a substring of the comma separated input.

That means, if you have tables `user`, `user_group` and `group` in your database. Then, given your comma separated input be `user`. It will generate the entity file for `user` and `user_group` tables.

Which isn't what we want!

**Comment by billy1624** [comment]
I just fix the issue on https://github.com/SeaQL/sea-orm/pull/1245

**Comment by johnbcodes** [comment]
Thank you @billy1624 @tyt2y3!
