### ISSUE TITLE
Queries don't get logged if they fail

### ISSUE THREAD

**Issue by nitnelave** [SeaQL/sea-orm#1246]
While migrating from sea-query to sea-orm and rewriting all my queries, more than once I hit a sql problem that would turn into an Error during the execution (e.g. "Query(SqlxError(Database(SqliteError { code: 1, message: "ambiguous column name: user_id" })))").

I turned on logging for the queries, but every time the last logged query was not relevant. The actual query with a problem (the one with the ambiguous column name) was not printed to the logs, which made it much harder to debug.

Can we print the queries to the log before running them, whether they succeed or not?

**Comment by billy1624** [comment]
Hey @nitnelave, hi again! I just make up a runtime SQL error and the SQL was being logged right before execution.
- Source code: https://github.com/billy1624/sea-orm/pull/20
- Error message: https://github.com/billy1624/sea-orm/actions/runs/3537627259/jobs/5937841208#step:5:376

**Comment by nitnelave** [comment]
Oh, it might have been sure to my logging layer, since it aggregates some things! Let me double check. Sorry for the trouble.

**Comment by billy1624** [comment]
No worries!

**Comment by nitnelave** [comment]
Confirmed, that was my tracing later.
