### ISSUE TITLE
DeriveActiveEnum's implicit implementation of Display trait needs to be overridable

### ISSUE THREAD

**Issue by nickb937** [SeaQL/sea-orm#1255]
In reference to the implementation of the Display trait for https://github.com/SeaQL/sea-orm/issues/955, the solution provided does not always suit all applications because an application may choose to present the enum in a different way, depending on use case.

For example, for clarity in code, it makes sense to write out the genders in their full form, but presentation elsewhere can often be suitably understood by their single letter abbreviations:

```
#[derive(Debug, Clone, Hash, Eq, PartialEq, EnumIter, DeriveActiveEnum, Serialize, Deserialize_repr)]
#[sea_orm(rs_type = "i16", db_type = "SmallInteger")]
#[repr(u16)]
pub enum Gender {
    #[sea_orm(num_value = 1)]
    Male = 1,
    #[sea_orm(num_value = 2)]
    Female = 2,
    #[sea_orm(num_value = 3)]
    Unspecified = 3,
    #[sea_orm(num_value = 4)]
    Other = 4,
}

impl Display for Gender {
    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}",
               match self {
                   Gender::Male => "M",
                   Gender::Female => "F",
                   Gender::Unspecified => "U",
                   Gender::Other => "O",
               }
        )
    }
}
```

The suggestion from Discord is to implement a `display_value` attribute to overside the default display value of, say, "Male" with "M":

```
    #[sea_orm(num_value = 1, display_value="M")]
    Male = 1,
    #[sea_orm(num_value = 1, display_value="F")]
    Female = 2,
```

**Comment by simonask** [comment]
Ran into this as well.

My problem is that I have a string enum, and the `Display` implementation of `sea_orm::Value` outputs SQL, so the string becomes quoted.

I guess I don't understand why `Display` is the correct trait to implement here. It's meant to produce a user-facing string.

I worked around it by implementing using `#[strum(serialize = "...")]` with the same string value, and then using `maud::Render` to override the `Display` implementation. But this is problematic and error-prone for other reasons (HTML isn't the only user-facing output in my situation).

Please advise. :-)

**Comment by tyt2y3** [comment]
I do think the current implementation of `Display` is weird. To be precise, we should print `Male` instead of `1`.
You can write a custom `Serialize` impl, or you can use a wrapper type and override `Display`.

**Comment by tyt2y3** [comment]
It might be better we rework that implementation

**Comment by kerkmann** [comment]
Yes please, It's really annoying (sadly). ^^"
