### ISSUE TITLE
sea-orm-cli generates invalid code if a table has no primary key

### ISSUE THREAD

**Issue by nicoulaj** [SeaQL/sea-orm#126]
With given schema:
```
create table tag
(
    id bigint generated by default as identity
        constraint tag_pkey
            primary key
);
```

`sea-orm-cli generate` outputs:
```
impl PrimaryKeyTrait for PrimaryKey {
    fn auto_increment() -> bool {
        true
    }
}
```
instead of:
```
impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i64;
    fn auto_increment() -> bool {
        true
    }
}
```

Tested with sea-orm-cli 0.1.3
related: SeaQL/sea-schema#13

**Comment by tyt2y3** [comment]
Yes, we were in the process of a release.
Please run `cargo install sea-orm-cli` again to update to [sea-orm-cli/0.2.0](https://crates.io/crates/sea-orm-cli/0.2.0).

**Comment by nicoulaj** [comment]
Ha yes my bad, I can confirm this works fine on 0.2.0.

Another small issue though: if a table has no primary key, it generates invalid code instead of skipping it or throwing a proper error, eg:
```
create table test
(
    id         bigint generated by default as identity
);
```
generates:
```
impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = ;
    fn auto_increment () -> bool {
        true
    }
}
```

**Comment by tyt2y3** [comment]
Thank you for your report. I think currently SeaORM requires an Entity to have a primary key.
Though, it does not necessarily to be an actual primary key in the database table.
This behavior is common in other ORM too (AFAIK).
