### ISSUE TITLE
support exclude column

### ISSUE THREAD

**Issue by yuhaya** [SeaQL/sea-orm#1261]
## Motivation

The data table has 20 fields, but I only want to query 19 of them. Sea-orm does not seem to support field exclusion at present. It is too troublesome to call .column() 19 times

## Proposed Solutions

add select api 

```rust
fn column_exclude<C>(mut self, col: C) -> Self
    where
        C: ColumnTrait,
    {
        // code...
        self
    }
```

**Comment by billy1624** [comment]
Hey @yuhaya, welcome!! Thanks for the suggestions! I just created a PR to perform similar operation.

https://github.com/SeaQL/sea-orm/blob/1520beaa15b86e7eafb7f0679e2c23d59d34c005/src/query/helper.rs#L115-L131

**Comment by yuhaya** [comment]
> Hey @yuhaya, welcome!! Thanks for the suggestions! I just created a PR to perform similar operation.
> 
> https://github.com/SeaQL/sea-orm/blob/1520beaa15b86e7eafb7f0679e2c23d59d34c005/src/query/helper.rs#L115-L131

good!
