### ISSUE TITLE
How to downgrade sea-orm-cli version?

### ISSUE THREAD

**Issue by frederikhors** [SeaQL/sea-orm#1286]
If I install with:

```shell
cargo install sea-orm-cli@0.10.2
```

and generate with:

```shell
sea-orm-cli generate entity //......
```

the generated file have:

```rust
//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.5
```

instead of of `0.10.2`.

If I run

```shell
sea-orm-cli -v
```

I can see:

```shell
sea-orm-cli 0.10.2
```

What is going on?

I need the 0.10.2 version right now.

**Comment by billy1624** [comment]
Hey @frederikhors, please use the following command to degrade `sea-orm-cli`.

```shell
cargo install --version 0.10.2 sea-orm-cli
```

**Comment by frederikhors** [comment]
I tried this too and with `--force` too. Nothing. The version of generated files is 0.10.5 always. Crazy!

**Comment by billy1624** [comment]
Hmmm... why? Did you try uninstall it first then install it again?

**Comment by frederikhors** [comment]
Yeah! Of course!

**Comment by frederikhors** [comment]
I used:

```shell
cargo uninstall sea-orm-cli

Removing C:\Users\Fred\.cargo\bin\sea-orm-cli.exe
Removing C:\Users\Fred\.cargo\bin\sea.exe
```

**Comment by billy1624** [comment]
And try restarting the command prompt after installation

**Comment by frederikhors** [comment]
Then I installed with:

```shell
cargo install --version 0.10.2 sea-orm-cli

...
  Compiling tracing-subscriber v0.3.16
  Compiling clap v3.2.23
  Compiling chrono v0.4.23
  Compiling sqlx v0.6.2
  Compiling sea-query-binder v0.2.2
  Compiling sea-schema v0.10.3
  Compiling sea-orm-codegen v0.10.5
  Compiling sea-orm-cli v0.10.2
  Finished release [optimized] target(s) in 2m 48s
Installing C:\Users\Fred\.cargo\bin\sea-orm-cli.exe
Installing C:\Users\Fred\.cargo\bin\sea.exe
  Installed package `sea-orm-cli v0.10.2` (executables `sea-orm-cli.exe`, `sea.exe`)
```

Now it is 0.10.2.

If I generate the files have the comment (and the differences) of the 0.10.5! Crazy!

**Comment by frederikhors** [comment]
It's crazy because the .exe in cargo's bin directory is the new one!

**Comment by billy1624** [comment]
I suspect this is the result of some weird caching issue

**Comment by billy1624** [comment]
Please :)

**Comment by frederikhors** [comment]
I did. I removed everything because this is a new PC.

I manully removed cache directories too.

I installed rustup & cargo again, and sea-orm-cli with 0.10.2.

Nothing. The generation is for 0.10.5.

I give up. This is totally crazy.

**Comment by frederikhors** [comment]
This is really bad because I'm stucked right now. I cannot generate nor new table or old ones.

Is there a way I can use Cargo.toml to fix the version o sea-orm-cli avoiding the executable?

**Comment by billy1624** [comment]
I guess you can git clone the project at 0.10.2 tag. Then run the CLI locally.

**Comment by frederikhors** [comment]
Yeah. I will in a few minutes temporarily. I think this should work.

What do you think could be the problem?

Have you tried the downgrade on your PC?

**Comment by billy1624** [comment]
Okay. I think I think what have happen! Check how `sea-orm-cli` depends on `sea-orm-codegen`.

https://github.com/SeaQL/sea-orm/blob/f23c99bcc9bd458401d94eef1effefc2dcf336fa/sea-orm-cli/Cargo.toml#L37

Basically, it will pick the latest `sea-orm-codegen`! i.e. `sea-orm-codegen` 0.10.5

**Comment by frederikhors** [comment]
Wow! This is the issue. How can we fix this?

**Comment by frederikhors** [comment]
Also we have to fix this for older versions too?

https://github.com/SeaQL/sea-orm/blob/0.10.2/sea-orm-cli/Cargo.toml

**Comment by billy1624** [comment]
It's intended to always fetch the latest 0.10.x sea-orm-codegen.

**Comment by frederikhors** [comment]
> It's intended to always fetch the latest 0.10.x sea-orm-codegen.

I think this is not the correct behavior.

In this case we were stuck because of the bug of the related trait.

I think we need a way to downgrade safely.

**Comment by billy1624** [comment]
Oh. sorry... didn't mean to close this issue

**Comment by frederikhors** [comment]
Ok. It was a little bit strange! 😄

**Comment by billy1624** [comment]
> It's intended to always fetch the latest 0.10.x sea-orm-codegen.

So, the intention is to compile with the latest codegen but as a side effect, one cannot downgrade to 0.10.x unless going below it e.g. 0.9.x

I think we should make it

```rs
sea-orm-codegen = { version = "=0.10.5", ... } 
```

**Comment by frederikhors** [comment]
Is there a way we can choose in `Cargo.toml` which version of both we depend on?

**Comment by billy1624** [comment]
> Is there a way we can choose in `Cargo.toml` which version of both we depend on?

Yes, if you clone this repository into local then modify the `Cargo.toml` and finally execute `cargo install --path sea-orm-cli --force` to install sea-orm-cli

**Comment by frederikhors** [comment]
Yes, I meant for the future. Wouldn't there be a way just using Cargo.toml?

**Comment by billy1624** [comment]
Note that every time we released a new `sea-orm-codegen`, we always bump the version of `sea-orm-cli`. That way, you can downgrade to each and every single version of it.
