### ISSUE TITLE
support for uuid::Hypenated

### ISSUE THREAD

**Issue by nappa85** [SeaQL/sea-orm#1290]
Let's take for example this uuid: `008bc4af-d1e2-0000-0000-0000000002e3`
It's valid, but if I put that on a database field mapped with uuid::Uuid type, I get an error `invalid length: expected 16 bytes, found 36`
That's because sqlx's implementation of [Decode](https://github.com/launchbadge/sqlx/blob/main/sqlx-core/src/mysql/types/uuid.rs#L28) for uuid::Uuid uses the method `uuid::Uuid::from_slice`
Few lines under we can find the implementation for `uuid::fmt::Hypenated` that correcly uses the method `uuid::Uuid::parse_str`
Have you something against re-exporting also `uuid::fmt::Hypenated` type and implementing all sea-orm's traits for it?

**Comment by nappa85** [comment]
Well, this way we accept 2 different formats but we always save in one
format, I would prefer to have control over the format

Il gio 8 dic 2022, 04:02 Chris Tsang ***@***.***> ha scritto:

**Comment by billy1624** [comment]
I consider `uuid::fmt::Hypenated` as another type of UUID.

For `uuid::fmt::Hypenated`, it's a string with value `008bc4af-d1e2-0000-0000-0000000002e3`. However, for `uuid::Uuid` it's a byte (string) `008bc4afd1e2000000000000000002e3`. So, I support treating it just as a separate data type, i.e. adding a new variant to `sea_query::Value` and implement the `sea_orm::TryGetable` for it.

@tyt2y3 please advice

**Comment by tyt2y3** [comment]
I see. Then yes, I agree with having `Hypenated` as a supported type.
However, I don't think sea-query needs to be changed.
We only need to impl `TryGetable*` for it. 
It's just like a user-defined wrapper type, except in this case the user can't impl it due to orphan rule.

**Comment by billy1624** [comment]
One cannot use it in SeaORM model without touching sea-query.

```rs
pub struct Model {
    uuid_hyphenated: uuid::fmt::Hyphenated, // `From<uuid::fmt::Hyphenated> for sea_query::Value`
}
```

Instead, we can implement a conversion method: `uuid::fmt::Hyphenated` -> `sea_query::Value::Uuid`.

Sounds good?

**Comment by tyt2y3** [comment]
Yes this approach makes more sense

**Comment by Ar0010r** [comment]
In my case it gives this compile error when I try to use uuid::fmt::Hyphenated as type for the primary key column
Do I miss something?

Thanks!
<img width="850" alt="Screenshot 2024-07-03 at 16 58 11" src="https://github.com/SeaQL/sea-orm/assets/47714178/9ca43982-9fac-48c1-a286-8a46bef965b2">

rustc 1.76.0 (07dca489a 2024-02-04)
uuid = {version ="1.9.1", features = ["v4","fast-rng", "macro-diagnostics"] }
sea-orm = { version = "0.12.15", features = [ "sqlx-mysql", "runtime-tokio-native-tls", "macros", "with-chrono", "with-uuid", "debug-print" ] }
