### ISSUE TITLE
"##@@" appears in the database connection password, which cannot be parsed

### ISSUE THREAD

**Issue by x7c7v7i87** [SeaQL/sea-orm#1306]
## Description

passwd not "##“ as passwd to "asjdoasjAAAjqie##@@911" in report error

## Steps to Reproduce

1. 
2. 
3. 

## Versions
0.10.5

## Additional Information

![image](https://user-images.githubusercontent.com/102465614/207686293-15cce090-39b1-4f77-a7c4-f5a5a5f1015f.png)

**Comment by x7c7v7i87** [comment]
cfg file are loaded through the dotenv library

**Comment by dragonnn** [comment]
try replacing ##@@ with %23%23%40%40. DATABASE_URL need to use percentage encoding (at least on sqlx but I am pretty sure it is the same for sea-orm as it uses sqlx), you can encode it online here https://www.url-encode-decode.com

**Comment by x7c7v7i87** [comment]
okay,
thanks

**Comment by billy1624** [comment]
Hey @x7c7v7i87, I guess this might be related. https://github.com/SeaQL/sea-orm/issues/1090

**Comment by x7c7v7i87** [comment]
ok,thank you

**Comment by billy1624** [comment]
Anytime :)

**Comment by billy1624** [comment]
@dragonnn thanks for helping!

**Comment by tyt2y3** [comment]
> try replacing ##@@ with %23%23%40%40. DATABASE_URL need to use percentage encoding (at least on sqlx but I am pretty sure it is the same for sea-orm as it uses sqlx), you can encode it online here https://www.url-encode-decode.com

Thank you @dragonnn this is a very good to know
