### ISSUE TITLE
Implement `TryGetable` for `Vec<u8>`

### ISSUE THREAD

**Issue by Acidic9** [SeaQL/sea-orm#133]
There is no implementation of [`TryGetable`](https://docs.rs/sea-orm/0.2.1/sea_orm/trait.TryGetable.html#) for `Vec<u8>`. This should be possible as [sqlx implements it for `Vec<u8>`](https://docs.rs/sqlx/0.5.7/sqlx/trait.Decode.html#impl-Decode%3C%27r%2C%20Postgres%3E-for-Vec%3CT%2C%20Global%3E).

This could be resolved easily by adding `try_getable_all!(Vec<u8>);` to [`src/executir/query.rs`](https://docs.rs/sea-orm/0.2.1/src/sea_orm/executor/query.rs.html#236).

**Comment by tyt2y3** [comment]
Let me try it real quick.

**Comment by Acidic9** [comment]
Oops I made a PR already for it 😄

**Comment by tyt2y3** [comment]
Thanks. It's pretty much the same second!

**Comment by Acidic9** [comment]
I wonder if it could also be implemented for `&str`?

Looks like there's just a missing implementation of `&str` for `ValueType`, but it might be as simple as adding `type_to_value!(&str, String);` to `src/value.rs`.

**Comment by Acidic9** [comment]
It looks like TryGetable does not support any borrowed values as the trait does not have any lifetimes indicated.
This is probably why the `Decode<'r, DB>` trait in sqlx has `'r`
https://docs.rs/sqlx/0.5.7/sqlx/trait.Decode.html#impl-Decode%3C%27r%2C%20Any%3E-for-%26%27r%20str

**Comment by Acidic9** [comment]
I guess this is resolved @tyt2y3 ?

**Comment by tyt2y3** [comment]
Not sure. We havn't got a test case for this.
