### ISSUE TITLE
Add a .gitignore in migration folder for  `sea-orm-cli migrate init` 

### ISSUE THREAD

**Issue by sanihaq** [SeaQL/sea-orm#1331]
Please add a `.gitignore` with the default rust ignore pattern.
I've twice committed the `target` folder already

**Comment by billy1624** [comment]
Hey @sanihaq, thanks for the suggestion!! I think it would be better if we able to mimic similar behaviour of `cargo init` command.

> If you are not in an existing git repo, cargo init does start a git repo and adds a .gitignore. If you are already in a git repo maybe change the root .gitignore to include something like `*/target/*`
> 
> https://github.com/rust-lang/cargo/issues/9633#issuecomment-869704995

We can check if the migration folder resides in a Git VCS or not with this: https://docs.rs/git-discover/latest/git_discover/fn.upwards.html
