### ISSUE TITLE
add if_not_exists() for Type::create()

### ISSUE THREAD

**Issue by manwantnosmoke** [SeaQL/sea-orm#1337]
When creating types using the provided orm functions, we are missing the if_not_exists as we have on table creation.

**Comment by ikrivosheev** [comment]
@manwantnosmoke hello! Postgres doesnot have `CREATE TYPE IF NOT EXISTS`:

Link: https://www.postgresql.org/docs/current/sql-createtype.html

**Comment by manwantnosmoke** [comment]
Could we translate that to some actions that would still result in the same thing? 
such as: https://stackoverflow.com/questions/7624919/check-if-a-user-defined-type-already-exists-in-postgresql

**Comment by tyt2y3** [comment]
It would make more sense to use another function to check the existence of such type, probably by querying `pg_type`
