### ISSUE TITLE
`sea-orm-cli` errors exit with error code 0

### ISSUE THREAD

**Issue by AngelOnFira** [SeaQL/sea-orm#1342]
## Description

When using the CLI, any error returns the status code `0`, which suggests that the command worked properly.

## Steps to Reproduce

1. Write an incorrect migration
2. Run `sea-orm-cli migrate; echo "status = $?"`

### Expected Behavior

`sea-orm-cli migrate; echo "status = $?"` should output `status = 1` or some other code.

### Actual Behavior

`sea-orm-cli migrate; echo "status = $?"` outputs `status = 0`, suggesting that the command worked.

### Reproduces How Often

Always

## Versions

```
│   ├── sea-orm v0.10.6
│   │   ├── sea-orm-macros v0.10.6 (proc-macro)
│   │   ├── sea-query v0.27.2
│   │   │   ├── sea-query-derive v0.2.0 (proc-macro)
│   │   ├── sea-query-binder v0.2.2
│   │   │   ├── sea-query v0.27.2 (*)
│   │   ├── sea-strum v0.23.0
│   │   │   └── sea-strum_macros v0.23.0 (proc-macro)
├── sea-orm v0.10.6 (*)
```

## Additional Information

This is likely quite easy to fix, it just requires exiting with error code 1 on any error :slightly_smiling_face:

My particular use case is I have a script to run migrations in development that looks like the following:
```bash
dropdb -U postgres -h localhost -p 5432 -w postgres
createdb -U postgres -h localhost -p 5432 -w postgres
sea-orm-cli migrate \
    && sea-orm-cli generate entity \
        -o entity/src/entities \
        --expanded-format \
        --with-serde both
```
In this case, I want the script to stop running if the migration failed, since it's easier to debug without the rest of the data from generating entities. The `&&` will only run the second command if the first one exits with a return value of `0`.

**Comment by Diwakar-Gupta** [comment]
I did reproduce this issue and would like to work on it.
@tyt2y3 @billy1624
I saw no member has commented on this can you please confirm once?

**Comment by billy1624** [comment]
Hey @AngelOnFira, thanks for the report. After some digging I found that we didn't check the status code of the executed command.

To handle it properly, we should:

```rs
// Run migrator CLI on user's behalf
println!("Running `cargo {}`", args.join(" "));
let exit_status = Command::new("cargo").args(args).status()?; // Get the status code
if !exit_status.success() { // Propagate the error if any
    return Err("Fail to run migration".into());
}
```

Source code location: https://github.com/SeaQL/sea-orm/blob/ca205543a37ba734a90fed8f23daf1cf0e45ce0d/sea-orm-cli/src/commands/migrate.rs#L67-L69

I simply thrown an error and it will be handled by `handle_error` function at https://github.com/SeaQL/sea-orm/blob/ca205543a37ba734a90fed8f23daf1cf0e45ce0d/sea-orm-cli/src/bin/main.rs#L18-L30

**Comment by billy1624** [comment]
Hey @Diwakar-Gupta, thanks for the initiative! Any opinions?
Maybe we should double check all places where we have used `std::process::Command`?

**Comment by Diwakar-Gupta** [comment]
@billy1624
I did checked the suggested code and I worked.
Apart from `sea-orm-cli/src/commands/migrate.rs` we also need to handle same in `sea-orm-cli/src/commands/generate.rs` file.
I will raise a PR with this changes soon.

**Comment by billy1624** [comment]
Thanks again for contributing! :D

**Comment by AngelOnFira** [comment]
Thanks for the fix @Diwakar-Gupta!
