### ISSUE TITLE
Allow limit to take -1

### ISSUE THREAD

**Issue by 112RG** [SeaQL/sea-orm#1372]
## Motivation
When writing web API there is often a time when you would like to limit the items returned by a request via query params. But sometimes these can be not set so we want to return all in that case
Currently in sea-orm when you provide a .limit() there is no way of saying just return all. Having something like -1 be a valid option taken and would then just ignore the limit all together would help clean up code where you have 

```rust
pub async fn get_latest_albums(
    db: &DatabaseConnection,
    size: Option<u64>,
) -> anyhow::Result<Vec<entity::album::Model>> {
    Ok(entity::album::Entity::find()
        .order_by_desc(entity::album::Column::CreatedAt)
        .limit(size.unwrap_or(50))
        .all(db)
        .await?)
}
```

Currently, I would have to setup crazy high default for the unwrap. Or have another function that doesn't have a .limit()

## Proposed Solutions
Allow .limit() to take None or -1 and return all items

**Comment by JonasCir** [comment]
If this get's implemented, I think we should use `Option::None` to represent this, using magic values has its downsides.

**Comment by 112RG** [comment]
Yes thinking about it ``Option:None`` seems better. My original plan was 
```rust  
.limit(size.unwrap_or(u64::MAX))
```

But it just throws a error ``called `Result::unwrap()` on an `Err` value: TryFromIntError(())'``

**Comment by dragonnn** [comment]
I don't think any of that is a good idea, why not just do it like that:
```rust
let mut query = entity::album::Entity::find()
        .order_by_desc(entity::album::Column::CreatedAt);
if let Some(size) = size {
     Ok(query.limit(size).all(db).await?)
} else {
    Ok(query.all(db).await?) //I think all needs to be replaced with find_all? Need to check
}
```
That should work.

**Comment by 112RG** [comment]
> I don't think any of that is a good idea, why not just do it like that:
> 
> ```rust
> let mut query = entity::album::Entity::find()
>         .order_by_desc(entity::album::Column::CreatedAt);
> if let Some(size) = size {
>     Ok(query.limit(size).all(db).await?)
> } else {
>     Ok(query.all(db).await?) //I think all needs to be replaced with find_all? Need to check
> }
> ```
> 
> That should work.

I know that will that is what I currently have but then I need if else blocks everywhere.
Adding that into code like this 

```rust
pub async fn get_albums(
    db: &DatabaseConnection,
    size: Option<u64>,
    sort: Option<String>,
) -> anyhow::Result<Vec<entity::album::Model>> {
    let order = match sort.as_deref() {
        Some("name") => entity::album::Column::Name,
        Some("artist_name") => entity::album::Column::ArtistName,
        Some("year") => entity::album::Column::Year,
        Some("latest") => entity::album::Column::CreatedAt,
        _ => entity::album::Column::Name,
    };

    let limit = size.unwrap_or(100);
    let result = match order {
        entity::album::Column::CreatedAt => {
            entity::album::Entity::find()
                .order_by_desc(order)
                .limit(limit)
                .all(db)
                .await
        }
        _ => {
            entity::album::Entity::find()
                .order_by_asc(order)
                .limit(limit)
                .all(db)
                .await
        }
    }
    .map_err(|e| anyhow!("Failed to get albums: {}", e))?;

    Ok(result)
}
```

It just adds even unnecessary code to the block. With .limit() taking a None value it would allow the query not to have to be built with if else match block hell. This also falls in line with https://github.com/SeaQL/sea-orm/discussions/1360

**Comment by dragonnn** [comment]
I think you should be able to extended what functions are under a Entity with you own trait and make such stuff generic so you only have to write it once.
Maybe this will help you https://gist.github.com/dragonnn/011dcdaf0a293d27c3d2eafa9904a760 this a snippet from my own code base where I use sea-orm to do generic kind of requests (note that it might not compile because I need to paste stuff from different files and might missed something.

**Comment by 112RG** [comment]
I still don't understand the issue you have with this? Why wouldn't I want giant generic blocks of code? When this can be a feature of the library?

**Comment by dragonnn** [comment]
It is not at this point so I wanted to help you. And the generic block helps with search and sorting too that is why it is giant with I see you are doing too.
When it comes to a feature of the library I agree that can be done but it would be a breaking change (unless you add a new function limit_option or something like that).

**Comment by JonasCir** [comment]
I Agree with this being a breaking change. However, I think the situation with `limit` arises frequently, maybe a `limit_or` function can be justified?

**Comment by 112RG** [comment]
I think limit_or is a better idea. Maybe also something to create in the future is an order_by(desc|asc. Your sea-orm-helper @dragonnn is really inciteful and does a lot of things I never thought of doing I really like the ``select.order_by(sort_column, sort.order().into());`` you have. I might make a issue for a say ``order_by(sort_column`` like you have for sea-orm too

If this was a personal project just for me I would use it but I don't like having abstractions on library code such as sea-orm. Which was my main request for this

**Comment by JonasCir** [comment]
On second thought, maybe call it `limit_of` or something, `or` suffix is used  [differently](https://doc.rust-lang.org/nightly/std/result/enum.Result.html#method.map_or) in Rust already.

**Comment by billy1624** [comment]
Hey everyone, thanks for joining in and discussing it! Hope I'm not too late to hop in :)

There are three use cases:
1. select without limit
2. select with limit
3. select with default limit

I imagine the APIs for each of the use cases are:
1. select without limit: `.limit(None)`
2. select with limit: `.limit(Some(100))` or simply `.limit(100)`
3. select with default limit:
```rs
let page_size: Option<u64> = ...;

select.limit(page_size.unwrap_or(100));
```

Similar API could also be introduced for `offset`.

Does that make sense?

**Comment by 112RG** [comment]
That is exactly it!

**Comment by JonasCir** [comment]
@billy1624 Thank you! Are you fine with changing the signature from `limit` to take an `Option<u64>`? What's your policy w.r.t. to breaking changes here?

Independently of this, I would like to do the implementation work of this ticket once we reach consensus of the design :) Seems like a good way to get started with the project :rocket:

**Comment by billy1624** [comment]
Hey @JonasCir, sorry, did I just steal your issue once again?

We tend to avoid breaking changes unless it's a must for us to move forward and does more good than harm.

If you look at https://github.com/SeaQL/sea-orm/pull/1410. I consider this as breaking changes as well since methods' parameter type is being changed. However, this is a "mild breaking changes", it's backward compatible.

```rs
// Backward compatible: existing user don't need to change anything
// They just has to make sure that `OptionalU64` is being imported into the scope
assert_eq!(
     cake::Entity::find()
         .offset(10)
         .build(DbBackend::MySql)
         .to_string(),
     "SELECT `cake`.`id`, `cake`.`name` FROM `cake` OFFSET 10"
 );

// New usages
assert_eq!(
    cake::Entity::find()
        .offset(Some(10))
        .build(DbBackend::MySql)
        .to_string(),
    "SELECT `cake`.`id`, `cake`.`name` FROM `cake` OFFSET 10"
);
assert_eq!(
    cake::Entity::find()
        .offset(None)
        .build(DbBackend::MySql)
        .to_string(),
    "SELECT `cake`.`id`, `cake`.`name` FROM `cake`"
);
```

Let me know if that make any sense to you :)
See you on another issue hahaa

**Comment by 112RG** [comment]
I never thought of an OptionalU64 that just wraps a u64 in Some() to keep backward compatibility.

This is a lot better then my hack of 
```rust
impl<E> DeaftoneSelect for Select<E>
where
    E: EntityTrait,
{
    fn limit_option(self, limit: OptionalU64) -> Self {
        if let Some(limit) = limit.optional_u64() {
            self.query().limit(limit);
        }
    }
}
```
That is a really neat feature of the language that I would of never thought to implement like that

**Comment by billy1624** [comment]
I guess that's the Rusty was to "overload method parameters" :)
