### ISSUE TITLE
Syntax Error when saving active model that sets nothing

### ISSUE THREAD

**Issue by billy1624** [SeaQL/sea-orm#1376]
### Discussed in https://github.com/SeaQL/sea-orm/discussions/1371

<div type='discussions-op-text'>

<sup>Originally posted by **lihe07** January  8, 2023</sup>
I have a ActiveModel like this;
```rust
ActiveModel {
    id; Unchanged(1),
    name: NotSet,
    password: NotSet
}
```
The SQL query for saving this looks like that:
```sql
UPDATE
  `users`
SET
WHERE
  `users`.`id` = ?
```
And that leads to a syntax error (empty set section).

I'm considering whether it's sea-orm's task to determine if the ActiveModel does noting or not.</div>

**Comment by lihe07** [comment]
Thanks! I'd be happy to work this out if I can!
(and I don't need a patch for my project either)

**Comment by billy1624** [comment]
Hey @lihe07, thanks for the interest!! Sorry, I didn't realise you want to take this. Please check my PR at https://github.com/SeaQL/sea-orm/pull/1384

**Comment by lihe07** [comment]
Never mind! I'll keep an eye out too, if there's anything I can do to help.
