### ISSUE TITLE
How to "TRUNCATE table_name" in sea-orm.

### ISSUE THREAD

**Issue by billy1624** [SeaQL/sea-orm#1377]
### Discussed in https://github.com/SeaQL/sea-orm/discussions/1375

<div type='discussions-op-text'>

<sup>Originally posted by **baoyachi** January  5, 2023</sup>
with reference link: https://www.postgresql.org/docs/current/sql-truncate.html</div>

**Comment by baoyachi** [comment]
LGTM

**Comment by baoyachi** [comment]
”So it's trivial to bring it into SeaORM.“

 I don't think it's trivial. Because I need use `TRUNCATE  table_name` before the unit test started

**Comment by billy1624** [comment]
Closing this now, as discussed at https://github.com/SeaQL/sea-orm/pull/1409#issuecomment-1403266432
