### ISSUE TITLE
Codegen for compact Entity format

### ISSUE THREAD

**Issue by tyt2y3** [SeaQL/sea-orm#138]
I think it's better for us to preserve the functionality to generate the current long Entity format, and can be switched on with a command line arguemnt.

- [x] update codegen
- [x] update sea-orm-cli to generate short format by default
- [x] update docs

**Comment by billy1624** [comment]
So, at the end the codegen can produce codes of one of the formats? Let say, compact & expanded format.

**Comment by tyt2y3** [comment]
`sea-orm-codegen` `0.2.2` released

**Comment by tyt2y3** [comment]
I discovered a slightly strange behavior, is when there no relation, it will not derive `DeriveRelation` for the `Relation` enum.
```rust
#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            _ => panic!("No RelationDef"),
        }
    }
}
```
