### ISSUE TITLE
[PostgresQL] Ability to set the default value of a UUID column to gen_random_uuid()

### ISSUE THREAD

**Issue by cmwhited** [SeaQL/sea-orm#1397]
## Motivation

When creating a new table with a UUID primary key, it would be very handy to be able to set the default value of the column to be the `gen_random_uuid()` function as such:

```sql
CREATE TABLE IF NOT EXISTS sample_table (
  id uuid NOT NULL PRIMARY KEY DEFAULT gen_random_uuid()
);
```

## Proposed Solutions

Potentially make this a supported default impl fn on the `ColumnDef` struct. Similar to how `auto_increment()` works. Maybe like:

```rust
ColumnDef::new(User::Id).uuid().not_null().primary_key().default_gen_random_uuid()
```

**Comment by tyt2y3** [comment]
Merge into #1398 as they are likely to be handled together

**Comment by musjj** [comment]
So now that this is closed, how do you do this in the latest version?

**Comment by everdrone** [comment]
> So now that this is closed, how do you do this in the latest version?

Did you find out how?

**Comment by dignifiedquire** [comment]
How is this possible? 

I was hoping this would work, but it fails

```rust
.col(uuid_uniq(Usernames::Id).default("gen_random_uuid()"))
```

**Comment by rubbieKelvin** [comment]
still lost on this

**Comment by vessd** [comment]
This works for me
```rust
.col(uuid(Table::Id).default(PgFunc::gen_random_uuid()).primary_key())
```
or
```rust
.col(uuid(Table::Id).extra("default public.gen_random_uuid()").primary_key())
```
