### ISSUE TITLE
Be able to set the default value on a timestamp column to the CURRENT_TIMESTAMP

### ISSUE THREAD

**Issue by cmwhited** [SeaQL/sea-orm#1398]
## Motivation

When creating a new table with timestamp columns - a created_at, updated_at combo, for instance - it would be very handy to be able to set the default value of the column to be the `CURRENT_TIMESTAMP` function as such:

```sql
CREATE TABLE IF NOT EXISTS sample_table (
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
);
```

## Proposed Solutions

Potentially make this a supported default impl fn on the `ColumnDef` struct. Maybe like:

```rust
ColumnDef::new(ApiKey::CreatedAtTs).date_time().not_null().default_current_timestamp()
```

**Comment by the-emerald** [comment]
I believe right now you can get a default timestamp like this:
```rs
ColumnDef::new(ApiKey::CreatedAtTs).date_time().not_null().extra("DEFAULT CURRENT_TIMESTAMP")
```

**Comment by tyt2y3** [comment]
Or

```rust
ColumnDef::new(Char::CreatedAt).timestamp().default(Expr::current_timestamp())
```

However this is only in SeaQuery (which you use in migrations), not on the entity definition.

So SeaORM still has to integrate that.

**Comment by Diwakar-Gupta** [comment]
> So SeaORM still has to integrate that.

@tyt2y3 can you please tell how integration can be done.

**Comment by tyt2y3** [comment]
We currently support default value in entity definition:

// tests/common/features/satellite.rs
```rust
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "satellite")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub satellite_name: String,
    #[sea_orm(default_value = "2022-01-26 16:24:00")]
    pub launch_date: DateTimeUtc,
}
```

So the goal is to also support:
```rust
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "satellite")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub satellite_name: String,
    #[sea_orm(default_expr = "Expr::current_timestamp()")]
    pub launch_date: DateTimeUtc,
}
```

**Comment by Diwakar-Gupta** [comment]
Hey @tyt2y3 I was trying to modify `ColumnDef` to store `Expr::` but ran in a problem
```rust
#[derive(Debug, Clone, PartialEq)]
pub struct ColumnDef {
    ...
    pub(crate) default_value: Option<Expr>, // previously this was Option<Value>
}
```

The problem is ColumnDef has to implement `PartialEq` but it's subfields `Expr` and `SimpleExpr` does not implement `Partial_eq`.

Also there are no test to check behaviour of `ColumnDef.default_value`.
