### ISSUE TITLE
Generate Migration file using sea-orm-cli

### ISSUE THREAD

**Issue by Diwakar-Gupta** [SeaQL/sea-orm#1401]
## Problem

When we create migration file its name is expected to be in a particular pattern `m<date>_<6-digit-index>_<description>.rs`
example: `m20220101_000001_create_table.rs`

It will be better if we can generate it using `sea-orm-cli` which will automatic use current date-time for name and take description as parameter. 

## Proposed Solutions
API format
`sea-orm-cl migrate new [description] [path_to_folder]`
or
`sea-orm-cl generate migration [description] [path_to_folder]`
example 
`sea-orm-cli generate migration create_table_chef ./src/migrator`

Apart from just the name default snippet code can also be written to that file.

## Implementation
We can add a value to MigrateSubCommand / GenerateSubcommands and respective implementation in commands folder.

**Comment by aadi58002** [comment]
@Diwakar-Gupta If i understand correctly the main request is to implement a default template for a migration?
Aside from that there is already the `sea-orm-cli migration generate` command which can be used to generate the migration file.
Also there is a `--universal-time` flag on it to use universal time.

**Comment by Diwakar-Gupta** [comment]
feature already exist `sea-orm-cli migrate generate` Thanks @aadi58002.
