### ISSUE TITLE
Add an instruction of `mock` flag on mock database interface. 

### ISSUE THREAD

**Issue by chansuke** [SeaQL/sea-orm#1453]
## Motivation
I was trying to add mock test with [MockDatabase](https://docs.rs/sea-orm/latest/sea_orm/struct.MockDatabase.html#) but couldn't find the description of `mock` flag in [docs.rs](https://docs.rs/sea-orm/latest/sea_orm/struct.MockDatabase.html) or [Mock Interface](https://www.sea-ql.org/SeaORM/docs/write-test/mock/).

I finally found the solution in [here](https://github.com/SeaQL/sea-orm/blob/master/Cargo.toml#L58) but thought that it will be helpful to add some documentation of `mock` flag for new comer.

## Proposed Solutions
Add some documentation of `mock` flag in docs.rs or [SeaORM docs](https://www.sea-ql.org/SeaORM/docs/write-test/mock/).

**Comment by tyt2y3** [comment]
Thank you for your suggestion. Tried to add some hints to docs.rs. Don't want to keep this open, but you can still comment shall you have further thoughts
