### ISSUE TITLE
Add some methods to `sea_orm_migration::migrator::Migration`

### ISSUE THREAD

**Issue by tp971** [SeaQL/sea-orm#1459]
Right now, you can't really do anything with this struct, so e.g. programmatically checking the status of all migrations using `MigratorTrait::get_migration_with_status` is not possible.

**Comment by sergeiivankov** [comment]
Hi @tp971! Could you describe your problem in more detail?

**Comment by tp971** [comment]
It's not necessarily a problem, rather an inconvenience. The only thing I need is the number of applied migrations, which can be done using `MigratorTrait::get_applied_migrations` or `MigratorTrait::get_migration_models`, but for logging and debugging purposes, it would be nice to have more information. My suggestion is to implement methods for `Migration` to get the name and the status (and maybe store the `applied_at` when `status` is `Applied`).

**Comment by sergeiivankov** [comment]
Can you attach code examples what and how you do it now and how you want do it with possible new api

**Comment by tp971** [comment]
A simple use case would be:
```rs
let migrations = Migrator::get_migration_with_status(db).await?;
//let migrations = Migrator::get_applied_migrations(db).await?; //if only applied migrations are needed
//let migrations = Migrator::get_pending_migrations(db).await?; //if only pending migrations are needed
for migration in &migrations {
    let name = migration.name(); //new method, returning &str
    let status = migration.status(); //new method, returning MigrationStatus
    debug!("migration {}: {}", name, status);
    //do something with name and status here
}
```

**Comment by sergeiivankov** [comment]
Yes, its strange that methods return Vec<Migration>, but Migration have pub visibility with private fields and does not actually provide any information. I'll try to fix it

**Comment by sergeiivankov** [comment]
@tp971 please see #1519
