### ISSUE TITLE
Support generic structures in FromQueryResult

### ISSUE THREAD

**Issue by leviska** [SeaQL/sea-orm#1463]
## Motivation

It seems that there should be no problem to write something like

```rust
#[derive(FromQueryResult)]
struct DateValue<T: TryGetable> {
  date: NaiveDate,
  value: T,
}
```
And then use it something like this
```rust
DateValue::<i32>::find_by_statement(..);
DateValue::<String>::find_by_statement(..);
```

I've tried doing that, and it seems like macro does not support it right now
```
error[E0107]: missing generics for struct `DateValue`
 --> stats/src/charts/insert.rs:6:12
  |
6 | pub struct DateValue<T: TryGetable> {
  |            ^^^^^^^^^ expected 1 generic argument
  |
note: struct defined here, with 1 generic parameter: `T`
 --> stats/src/charts/insert.rs:6:12
  |
6 | pub struct DateValue<T: TryGetable> {
  |            ^^^^^^^^^ -
help: add missing generic argument
  |
6 | pub struct DateValue<T><T: TryGetable> {
  |            ~~~~~~~~~~~~
```

## Proposed Solutions

Add support to the macro

Even better would be is to add `T: TryGetable` in the `impl<T: TryGetable> ...` block, like rust does with `Clone, Debug` and etc, so it would require the type to implement trait only if somebody actually uses fromqueryresult functions

**Comment by tyt2y3** [comment]
It's a very interesting use case
