### ISSUE TITLE
The row locking of innodb is not avaliable

### ISSUE THREAD

**Issue by xmh0511** [SeaQL/sea-orm#1469]
In the program that uses sea-orm, I start a transaction to do `select ... for update`
````rust
let sql= "SELECT * from table_1 where id=1 for update".to_owned();
let begin = db.begin().await?;
let r = Table1::find().from_raw_sql(Statement::from_string(DatabaseBackend::MySql, sql)).one(db).await?;
sleep(std::time::Duration::from_secs(5)).await;  // delay time
start.commit().await? 
````

Then, in the other client, I execute the following commands
````
Begin;
update table_1 set money=1 where id=1;
Commit;
````
When the first program hasn't executed the commit operation yet, the second update command is successful. Seems the first one didn't lock the row. 

If we conversely make the second one executes `select ... for update`
````
Begin;
SELECT * from table_1 where id=1 for update; 

// No commit
````
and I let the first program(i.e use sea-orm) do the update operation, in this time, the sea-orm will wait until I execute the `commit` in the second one. 

Seems like a bug of sea-orm.

**Comment by tyt2y3** [comment]
You misused the API, as in the `begin()` gives up a transaction object that you should use for all your queries.
i.e. 
```rust
let txn = db.begin().await?;
Entity::find().one(&txn).await?;
```

**Comment by xmh0511** [comment]
Thanks.

**Comment by xmh0511** [comment]
> You misused the API, as in the `begin()` gives you a transaction object that you should use for your subsequent queries. i.e.
> 
> ```rust
> let txn = db.begin().await?;
> Entity::find().one(&txn).await?;
> ```

Another question is, in order to keep the lock working in other threads, must I all use `txn`(generated by `db.begin()`) in the subsequent `update`, `insert`, `delete`, and so forth operations if I start a transaction in that thread?

**Comment by tyt2y3** [comment]
I don't fully understand your question, but the Transaction object essentially is a handle to the underlying database connection, which locks it until the transaction is dropped.
