### ISSUE TITLE
Depending only on sea-orm, not sea-query, breaks with `derive(Iden)`

### ISSUE THREAD

**Issue by nitnelave** [SeaQL/sea-orm#1473]
## Description

In order to keep sea-orm and sea-query in sync and not have different versions of traits, one can remove `sea-query` from the direct dependencies (from `Cargo.toml`) and only rely on the re-export of `sea_query` in `sea_orm`.

However, that breaks the following code:

```rust
use sea_orm::Iden;
#[derive(Iden)]
pub enum Users {
  Table
}
```

### Expected Behavior

Compiles.

### Actual Behavior

```
use of undeclared crate or module `sea_query`
```

## Versions

sea-orm 0.11
Implied sea-query.

## Additional Information

I'm guessing the derive macro expands to `sea_query::Iden`. Maybe the `sea_orm::Iden` version should expand to `sea_orm::sea_query::Iden`?

A workaround is to also `use sea_orm::sea_query::self;`.

**Comment by tyt2y3** [comment]
Right now, the `Iden` is just a re-export of the sea_query macro, that's why it isn't aware of sea_orm.
We can maintain a different impl in sea_orm.

**Comment by billy1624** [comment]
I think it's a bad idea to have a `Iden` lite in `sea-orm`. What if an existing `sea-query` user want their `Iden` (with `custom`, `iden = `, `flatten` etc customization) to be used in `sea-orm`? They might be surprised to find the behaviour of the `Iden` changed after importing `sea_orm::Iden`.

So, maybe importing `sea-query` into the scope is a better "solution", i.e. `use sea_orm::sea_query::{self};`

**Comment by billy1624** [comment]
> Thanks for the report. Right now, the `Iden` is just a re-export of the sea_query macro, that's why it isn't aware of sea_orm. We can maintain a different impl in sea_orm, which should remove some unnecessary stuff from sea_query's version as well. The `custom`, `iden = `, `flatten` etc can all be omitted. I think the only relevant attribute to keep is the `iden(rename = )`.

We will do this

**Comment by billy1624** [comment]
And, add a feature flag to `sea-query-derive` crate to conditionally alter the `sea_query::` path as `sea_orm::sea_query::`

**Comment by tyt2y3** [comment]
> And, add a feature flag to `sea-query-derive` crate to conditionally alter the `sea_query::` path as `sea_orm::sea_query::`

We discovered this won't work. However the final resolution has been to remove sea-query's `Iden` macro altogether, while providing a new `DeriveIden` macro.
