### ISSUE TITLE
DeriveActiveEnum requires `use sea_orm::ColumnTypeTrait` in 0.11

### ISSUE THREAD

**Issue by inf0rm4tik3r** [SeaQL/sea-orm#1478]
After migrating sea-orm from 0.10 to 0.11, enums deriving `DeriveActiveEnum` suddenly need the `ColumnTypeTrait` to be put in scope by the user, which was not required previously. The macro implementation should reference the required `def` function by its absolute path so that the additional `use` requirement is not needed.

**Comment by tyt2y3** [comment]
This seems to be a bug we can fix in a patch release.
But can you give a minimal example so that I can pin-point where it originates from?

**Comment by panviktor** [comment]
the whole project is broken, need revert  to the 10th version, the same errors everywhere:



```
   |
19 |         user_id: Set(user_id.to_string()),
   |                  ^^^^^^^^^^^^^^^^^^^^^^^^ expected enum `migration::sea_orm::ActiveValue`, found enum `sea_orm::ActiveValue`
   |
   = note: enum `sea_orm::ActiveValue` and enum `migration::sea_orm::ActiveValue` have similar names, but are actually distinct types
```

**Comment by tyt2y3** [comment]
@panviktor Yours is a different problem.
