### ISSUE TITLE
Move DeriveMigrationName macros to sea-orm-migration

### ISSUE THREAD

**Issue by sergeiivankov** [SeaQL/sea-orm#1481]
## Motivation

DeriveMigrationName macros will implement sea_orm_migration::MigrationName for a migration, so it would be logical to move it to the appropriate crate.

## Proposed Solutions

Move DeriveMigrationName macros from `sea-orm` to `sea-orm-migration` crate

**Comment by sergeiivankov** [comment]
I know, it reexports from `sea-orm-macros` crate, but I think it would be more correct to reexport it in `sea-orm-migration`

**Comment by TheAwiteb** [comment]
Hi @sergeiivankov It's already there [sea_orm_migration](https://docs.rs/sea-orm-migration/latest/sea_orm_migration/index.html)::[prelude](https://docs.rs/sea-orm-migration/latest/sea_orm_migration/prelude/index.html)::[DeriveMigrationName](https://docs.rs/sea-orm-migration/latest/sea_orm_migration/prelude/derive.DeriveMigrationName.html#). So should we deprecated it?

**Comment by sergeiivankov** [comment]
Thank you, i didn't see this reexport. Sea-orm crates have so much reexports between each other
