### ISSUE TITLE
distinct_on uses ambiguous name

### ISSUE THREAD

**Issue by numfin** [SeaQL/sea-orm#1491]
## Description

`.distinct_on()` inserts column name in final query instead of alias.

Screenshot of produced query
![image](https://user-images.githubusercontent.com/8134947/219876459-5ea55bab-8143-4aff-a8dc-b38f0275d568.png)

On screenshot if you change `DISTINCT ON (ipu_id)` to `DISTINCT ON (ipu_ipu_id)` everything works fine :)

## Steps to Reproduce

1. Add join with similar column name
2. Add distinct_on

### Expected Behavior

`DISTINCT ON()` contains column alias

### Actual Behavior

`DISTINCT ON()` contains original column name

### Reproduces How Often

always :)

## Versions

^0.11

**Comment by numfin** [comment]
After reading docs of sea-query `distinct_on` i found that i can use pairs like this:
![image](https://user-images.githubusercontent.com/8134947/219877480-035e451b-4557-49d8-bdc3-f3462c43a488.png)

Now everything works find. 
I think it would be nice to add this example in docs of sea-orm too

**Comment by tyt2y3** [comment]
Can you attach your original Rust code snippet, and fixed code snippet?

**Comment by numfin** [comment]
@tyt2y3 
before:
```
        let select = ipu::Entity::find()
            .filter(account::Column::AccountNumber.eq(&account.account_number))
            .filter(account::Column::AccountStatus.eq(EnumAccountStatus::Active))
            .filter(account::Column::UserId.eq(user.user_id))
            .left_join(service_type::Entity)
            .left_join(ipu_model::Entity)
            .left_join(ipu_reading::Entity)
            .left_join(account::Entity)
            .distinct_on([ipu::Column::IpuId])
            .order_by(ipu::Column::IpuId, Order::Desc)
            .order_by(ipu_reading::Column::Date, Order::Desc)
```
after:
```
            .distinct_on([(ipu::Entity, ipu::Column::IpuId)])
```

**Comment by tyt2y3** [comment]
Thank you @numfin . I adjusted the docs accordingly.
