### ISSUE TITLE
Inconsistent enum select behavior

### ISSUE THREAD

**Issue by TurtIeSocks** [SeaQL/sea-orm#1500]
## Description

Example Enum:
```rs
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "example")]
pub enum Example {
    #[sea_orm(string_value = "foo")]
    Foo,
    #[sea_orm(string_value = "bar")]
    Bar,
    #[sea_orm(string_value = "foo_bar")]
    FooBar,
}
```

When selecting enum columns using `.into_json()`,  their values are returned as the value that's stored in the database, `foo` or `foo_bar`. However, when selecting into their Model struct or with `.into_model::<MyCustomModel>()`, they are returned as their enum value, `Foo` or `FooBar`.

## Steps to Reproduce

1. Create a table with a native enum type
2. `Entity::find().all(db).await`
3. `Entity::find().into_json().all(db).await`
4. Compare

### Expected Behavior
Consistent behavior, doesn't matter to me if it's the enum value or database value, but I suppose it should probably be the database value.

### Actual Behavior
Inconsistent behavior.

### Reproduces How Often
Consistently

## Versions
```
➜  server git:(develop) $ cargo tree | grep sea-
│   │   │   ├── sea-orm v0.11.0
│   │   │   │   ├── sea-orm-macros v0.11.0 (proc-macro)
│   │   │   │   ├── sea-query v0.28.3
│   │   │   │   │   ├── sea-query-derive v0.3.0 (proc-macro)
│   │   │   │   ├── sea-query-binder v0.3.0
│   │   │   │   │   ├── sea-query v0.28.3 (*)
│   │   │   │   ├── sea-strum v0.23.0
│   │   │   │   │   └── sea-strum_macros v0.23.0 (proc-macro)
│   │   ├── sea-orm-migration v0.11.0
│   │   │   ├── sea-orm v0.11.0 (*)
│   │   │   ├── sea-orm-cli v0.11.0
│   │   │   │   ├── sea-schema v0.11.0
│   │   │   │   │   ├── sea-query v0.28.3 (*)
│   │   │   │   │   └── sea-schema-derive v0.1.0 (proc-macro)
│   │   │   ├── sea-schema v0.11.0 (*)
```
Database: MySQL
OS: MacOS Ventura

**Comment by tyt2y3** [comment]
Why is this a bug? Can you post a runnable example with assert statements?

**Comment by tyt2y3** [comment]
Please reopen if you can provide more information
