### ISSUE TITLE
Add support for root arrays in JSON in SeaORM

### ISSUE THREAD

**Issue by a14e** [SeaQL/sea-orm#1517]
## Description

Greetings! I've been trying to use jsonb with a root array object in SeaORM, but it appears that the current implementation doesn't support it.

## Steps to Reproduce

```rust
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "my_model")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: String,
    #[sea_orm(column_type = Json)]
    pub issue_tags: Vec<IssueTag>
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, FromJsonQueryResult)]
pub struct IssueTag {
    name: String,
    time: chrono::DateTime<Utc>,
}
```

### Expected Behavior
I expect the code to compile without errors.

### Actual Behavior
Instead, I encounter the following error:
```
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
   |                                   ^^^^^^^^^^^^^^^^^ the trait `From<Vec<IssueTag>>` is not implemented for `sea_orm::Value`
 ```
It would be great if SeaORM could support root array objects in JSON. Thank you for your attention to this matter!

**Comment by t348575** [comment]
I also want this, in the mean time this simple workaround works (I use postgres) @a14e :
Get stored in the db as if its a Vec<IssueTagData>
```rs
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, FromJsonQueryResult)]
pub struct IssueTag(pub Vec<IssueTagData>);

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, FromJsonQueryResult)]
pub struct IssueTagData {
    pub name: String,
    pub time: chrono::DateTime<Utc>
}
```

**Comment by anshap1719** [comment]
@a14e @t348575 

I was facing similar issue and created a PR today but I didn't realize this issue already exists. Updated my PR to reference this issue and also added support for root array objects. Can you also confirm that the PR works for your case by testing locally?

**Comment by anshap1719** [comment]
@billy1624 @tyt2y3  If this is something you guys don't mind supporting, I'd be happy to create a PR.

**Comment by tyt2y3** [comment]
Yes. A PR would be welcomed. Or we'll see if @darkmmon have the capacity to investigate.

**Comment by IgnisDa** [comment]
Could you guide me on what to do? Maybe I can make a PR.

**Comment by anshap1719** [comment]
@IgnisDa I don't want to take away this issue from you, but are you able to proceed? This issue has raised in priority for me so I'd like to create a PR for it if you're unable to.

**Comment by IgnisDa** [comment]
@anshap1719 I don't plan working on this soon. I would be glad if you take it up!

**Comment by anshap1719** [comment]
@IgnisDa Thanks for confirming. I'll take this up then.

**Comment by anshap1719** [comment]
Update: Although this looked to be a simple change (and it is), there's a conflicting trait implementation that's impossible to get around without changing too much of the code. I'm gonna think more about this, and if I can't see a simple solution without too much refactor, will delegate the decision to one of the maintainers.

**Comment by tyt2y3** [comment]
@anshap1719  Thank you for the effort! Can you briefly describe the blockers you are facing? What are the errors?

**Comment by anshap1719** [comment]
@tyt2y3 Basically, we need this more or less:
```
#[cfg(feature = "with-json")]
impl<T> TryGetableFromJson for Vec<T> where T: TryGetableFromJson {}
```

Even the blanket implementation is enough.

But this causes a conflicting trait implementation for `TryGetable` due to the following code:
```
impl<T> TryGetable for Vec<T>
where
    T: ActiveEnum,
    T::ValueVec: TryGetable,
{
    fn try_get_by<I: crate::ColIdx>(res: &QueryResult, index: I) -> Result<Self, TryGetError> {
        <T::ValueVec as TryGetable>::try_get_by(res, index)?
            .into_iter()
            .map(|value| T::try_from_value(&value).map_err(Into::into))
            .collect()
    }
}
```

This happens because we also have
```
#[cfg(feature = "with-json")]
impl<T> TryGetable for T
where
    T: TryGetableFromJson,
{
    fn try_get_by<I: ColIdx>(res: &QueryResult, index: I) -> Result<Self, TryGetError> {
        T::try_get_from_json(res, index)
    }
}}
```

**Comment by tyt2y3** [comment]
Thank you for pointing this out. I would say it's unfortunate, because `impl<T> TryGetable for Vec<T> where T: ActiveEnum` is only for Postgres Array and we could have feature-guarded this implementation.

However without negative trait bounds, it means that both features cannot be enabled at the same time.

What we wanted is a non-existient trait bound that can allow us to exclude `ActiveEnum`, something like `where T: !ActiveEnum`.

I imagine we have to rework the `Vec<T: ActiveEnum>` impl and have a 'union trait' that represents 'ActiveEnum OR TryGetableFromJson' where it will do runtime dispatch.

In the end there will only be one `impl<T> TryGetable for Vec<T> where T: ActiveEnumOrJson {}`.

This should be possible, because in the end, the number of sqlx types we want to support are bounded: we only support string (we always cast as text) or integers for enums, and Json for Json.

**Comment by anshap1719** [comment]
@tyt2y3 Thanks for that direction. I think I can try that out.

We need a `FromJsonArrayQueryResult` macro anyway which I added in PR. Because the internal type T also needs to implement `NotU8`.

**Comment by tyt2y3** [comment]
Thanks, you see, `NotU8` is also our crude attempt in having a negative trait bound. It will be quite an exercise!

**Comment by anshap1719** [comment]
@tyt2y3 Yup, I saw the doc comment on why it was needed. Makes sense. Thanks :)

**Comment by tyt2y3** [comment]
https://github.com/SeaQL/sea-orm/blob/af52e86a9ced16156899f682011713363e071fcd/src/executor/query.rs#L153-L178

Another type shenanigan I just remembered. This basically 'fused' `str` and `usize` and do runtime selection.

**Comment by anshap1719** [comment]
@tyt2y3 An initial implementation is available here now: https://github.com/anshap1719/sea-orm

I've tested this with my project and everything seems to work as expected. Checked against json (and it's array counterpart) as well as enum (and it's array counterpart).

Still quite a lot to be done, such as unit tests, documentation and some cleanup, but would be great if I could receive an initial feedback on whether or not this is the right direction.

> Another type shenanigan I just remembered. This basically 'unioned' str and usize and do runtime selection.

Also, I didn't go into this as it wasn't needed. But let me know if you'd prefer this to be done as well in this PR.

Thanks for all your help.

**Comment by IgnisDa** [comment]
@anshap1719 I tried your commit. It does not work for me. Is the data type I have selected right? [Here](https://github.com/IgnisDa/ryot/pull/305/commits/9f009a46aeb337243af138f8f9ee88d42941b965) is the commit (in `apps/backend/src/entities/exercise.rs` `L-37`).

**Comment by anshap1719** [comment]
@IgnisDa I think I'll have to run your project locally to see why. Would that be fine? Do you have a sample db dump for me to use?

**Comment by IgnisDa** [comment]
Sure give me a sec.

**Comment by IgnisDa** [comment]
![image](https://github.com/SeaQL/sea-orm/assets/60938164/96251b42-1db8-4e5b-946c-84ceaaa94d06)
BTW this is the error that I am getting.

**Comment by anshap1719** [comment]
@IgnisDa Can you try deriving `FromJsonArrayQueryResult` instead of `FromJsonQueryResult` on your `ExerciseMuscle` type?

**Comment by IgnisDa** [comment]
It derrives `DeriveActiveEnum`.

**Comment by IgnisDa** [comment]
@anshap1719 I forgot to use your derive macro, it works now! https://github.com/IgnisDa/ryot/pull/305/commits/c7f92a1cc779337312d7c86bc9c8e1fb234fd856

**Comment by anshap1719** [comment]
@IgnisDa Glad to hear! I wonder if it is setup as an `enum` in DB schema though. If it is, I'll try and see why `DeriveActiveEnum` wasn't working as that would've been the more appropriate choice here.

**Comment by IgnisDa** [comment]
Its setup as a JSON field.

**Comment by anshap1719** [comment]
@IgnisDa Ah gotcha!

**Comment by IgnisDa** [comment]
Thanks for your help!

**Comment by anshap1719** [comment]
No worries @IgnisDa

**Comment by IgnisDa** [comment]
@anshap1719 could a PR for this, so that it can be merged into sea-orm?

**Comment by anshap1719** [comment]
@IgnisDa I didn't create yet because I'd like to add tests for all changes, which unfortunately I won't be able to do before this weekend. If you get some time before that, feel free to add them if you'd like to.

**Comment by IgnisDa** [comment]
@anshap1719 I see you have added tests, is there anything left?

**Comment by anshap1719** [comment]
@IgnisDa Yeah, sorry about that. I did add tests 2 weeks ago but they were not ready, and also broken. I finally got some time today for this so I've made the PR ready for review and will ensure that tests are passing.

**Comment by IgnisDa** [comment]
@anshap1719 sorry for the nudge. When will you be able to get the PR ready?

**Comment by tyt2y3** [comment]
I think there is a PR already (or did I rmb wrongly)? But there are some intricate details I need to figure out.

**Comment by anshap1719** [comment]
@tyt2y3 @IgnisDa There is indeed a PR already :)

**Comment by IgnisDa** [comment]
cool thanks!

**Comment by tyt2y3** [comment]
I think we are pretty close, if you are interested you can check out https://github.com/SeaQL/sea-orm/pull/1898/files ?

**Comment by tyt2y3** [comment]
> cool thanks!

@IgnisDa  I think we are pretty close, if you are interested you can check out https://github.com/SeaQL/sea-orm/pull/1898/files and try?

**Comment by IgnisDa** [comment]
@tyt2y3 I am not able to figure out how to put this git branch as a dependency. I have:
```toml
sea-orm = { git = "https://github.com/SeaQL/sea-orm.git", branch = "rework-active-enum", features = [
    "debug-print",
    "macros",
    "runtime-tokio-rustls",
    "sqlx-mysql",
    "sqlx-postgres",
    "sqlx-sqlite",
    "with-chrono",
    "with-uuid",
    "with-rust_decimal",
] }
````
but it complains that `sea_orm` is ambiguous.

Probably because it is a workspace?

**Comment by IgnisDa** [comment]
@tyt2y3 The patching part is fine, but I am still getting this error:
![image](https://github.com/SeaQL/sea-orm/assets/60938164/af939a73-a04f-44c2-b2ce-2991bd38a960)

**Comment by anshap1719** [comment]
> @tyt2y3 The patching part is fine, but I am still getting this error:
> 
> ![image](https://github.com/SeaQL/sea-orm/assets/60938164/af939a73-a04f-44c2-b2ce-2991bd38a960)
> 
> 

@IgnisDa 

The error looks self-explanatory to me (you need to import the trait?). Am I missing something?

**Comment by anshap1719** [comment]
@IgnisDa Ah, sorry. Looks like it's the macro that needs to be updated in this case, and not a change that user of the crate should be doing...

Please disregard my previous comment.

**Comment by IgnisDa** [comment]
Yep i have already made the imports but it doesn't work.

**Comment by IgnisDa** [comment]
@tyt2y3 Any updates on what I can do to test the changes you made>

**Comment by tyt2y3** [comment]
@IgnisDa 

I guess: 
1) the error comes from a migration crate, so we can probably leave it for now
2) you also need to patch `sea-orm-macros`

**Comment by anshap1719** [comment]
@IgnisDa @tyt2y3 There's a small change needed in the macro code.

@tyt2y3 I hope you don't mind me pushing to your branch directly 😅

**Comment by anshap1719** [comment]
@tyt2y3 Ah, I can't push to it (permission denied). Are you able to grant me push access, or should I create a PR to merge to your branch?

**Comment by tyt2y3** [comment]
Yes, you can create a PR targeting this branch.
________________________________

**Comment by IgnisDa** [comment]
@tyt2y3 @anshap1719 I am trying to get this working with `Vec<MyEnum>`. Its trying to save the field as `jsonb[]`, but it should be saved as `json`. How can I do it?

**Comment by negezor** [comment]
@IgnisDa Add an attribute for your model field
```rs
#[sea_orm(column_type = "JsonBinary")]
pub muscles: Vec<MyEnum>,
```

**Comment by IgnisDa** [comment]
@negezor The type in my database is JSON, not JSON Binary.

**Comment by negezor** [comment]
@IgnisDa Then it could just be like that, although I haven’t tested it yet.
```rs
#[sea_orm(column_type = "Json")]
pub muscles: Vec<MyEnum>,
```

**Comment by IgnisDa** [comment]
@negezor Awesome that works!
