### ISSUE TITLE
`DatabaseConnection` is not `Send`, `Sync` and `Clone`

### ISSUE THREAD

**Issue by Acidic9** [SeaQL/sea-orm#152]
SeaORM's `DatabaseConnection` type is not `Send`, `Sync` and `Clone`.
These should be easily added as `DatabaseConnection` is a wrapper of the Sqlx pool types, which themselves are `Send`, `Sync` and `Clone`.

On the Sqlx [`Pool`](https://docs.rs/sqlx/0.5.7/sqlx/struct.Pool.html) documentation:
> `Pool` is `Send`, `Sync` and `Clone`, so it should be created once at the start of your application/daemon/web server/etc. and then shared with all tasks throughout its lifetime.

This is usually needed for many apps, such as an actix server, so it can be sent between threads to aquire new connections.

**Comment by tyt2y3** [comment]
I think it is `Send` and `Sync` already, but not `Clone` because yes the design is not for it to be cloned.

https://docs.rs/sea-orm/0.2.1/sea_orm/enum.DatabaseConnection.html#synthetic-implementations

**Comment by tyt2y3** [comment]
The PR changed the behavior to impl `Clone` only when `Mock` is not enabled.
