### ISSUE TITLE
the trait `From<Vec<std::string::String>>` is not implemented for `sea_orm::Value`

### ISSUE THREAD

**Issue by road2react** [SeaQL/sea-orm#1534]
## Description

the trait `From<Vec<std::string::String>>` is not implemented for `sea_orm::Value`

## Steps to Reproduce

1. Create a PostgreSQL database with a table
2. Add a nullable column to the table that contains an array of strings
3. Run `sea-orm-cli generate entity`

### Expected Behavior

The generated entity files should work.

### Actual Behavior

The generated struct looks like this (with `--expanded-format`):

```
#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Serialize, Deserialize)]
pub struct Model {
    pub column_with_array: Option<Vec<String>>,
}
```

However, this leads to a compile error:

```
    | ...Eq, DeriveModel, DeriveActiveModel, Serialize, Deserialize)]
    |                     ^^^^^^^^^^^^^^^^^
    |                     |
    |                     the trait `From<Vec<std::string::String>>` is not implemented for `sea_orm::Value`
    |                     in this derive macro expansion
```

### Reproduces How Often

Always happens

### Workarounds

The generated type could be changed, but it would no longer exactly match the database.

## Versions

`sea-orm-cli 0.11.1`

`sea-orm 0.11.1`

**Comment by billy1624** [comment]
Hey @road2react, welcome to SeaQL. A sanity check: you need to enable `postgres-array` feature on `sea-orm` for it to work.

**Comment by Nueck** [comment]
@billy1624 I try to use  `postgres-array`  but I don't know how to retrieve `text[]`
