### ISSUE TITLE
Execution Error: error returned from database: syntax error at or near "`"

### ISSUE THREAD

**Issue by brsnik** [SeaQL/sea-orm#1539]
## Description

Trying to install uuid-ossp, when I use `uuid-ossp` I get an error, same with 'uuid-ossp': 
```
Execution Error: error returned from database: syntax error at or near "`"
```
And when I leave it as is uuid-ossp I get this error:

```
error returned from database: syntax error at or near "-"
```

## Steps to Reproduce

```
CREATE EXTENSION IF NOT EXISTS uuid-ossp;
                
CREATE EXTENSION IF NOT EXISTS postgis;
```

### Reproduces How Often

Yes

**Comment by tyt2y3** [comment]
The particular Postgres extensions are not currently supported, but if you can describe what integration work is needed, we can see if it can be implemented.

**Comment by brsnik** [comment]
I am doing a migration with raw SQL. And I need to install those extensions.
However there becomes an issue because uuid-ossp is hyphenated. So wrapping it in backticks ` results in an error and so does in single quotes. Leaving it as is also returns an error because of the hyphen.

In your documentation for raw SQL you showcase backticks being used. But they're a problem here.

**Comment by tyt2y3** [comment]
Oh, if that's Postgres, use double quote `"`
