### ISSUE TITLE
When error 23505 is encountered, the primary_key id will be increased

### ISSUE THREAD

**Issue by LveUp** [SeaQL/sea-orm#1541]
## Description

When error 23505 is encountered, the primary_key id will be implicitly increased

## Steps to Reproduce

1. 
2. 
3. 

### Expected Behavior

save/insert like this
id
1    correct
2    correct
      error 
      error 
5    correct
6    correct

error : 
Query(SqlxError(Database(PgDatabaseError { severity: Error, code: "23505", message: "重复键违反唯一约束\"person_website_key\"", detail: Some("键值\"(website)=(http://baidu.com)\" 已经存在"), hint: None, position: None, where: None, schema: Some("public"), table: Some("person"), column: None, data_type: None, constraint: Some("person_website_key"), file: Some("nbtinsert.c"), line: Some(671), routine: Some("_bt_check_unique") })))

### Actual Behavior

save/insert like this
id
1    correct
2    correct
      error 
      error 
3    correct
4    correct

**Comment by tyt2y3** [comment]
This is a known behaviour of the Postgres https://stackoverflow.com/questions/2036571/is-there-a-way-to-avoid-calling-nextval-if-the-insert-fails-in-postgresql
