### ISSUE TITLE
[Regression][SQLite] Insert + On Conflict Do Nothing = error 

### ISSUE THREAD

**Issue by andoriyu** [SeaQL/sea-orm#1549]
## Description

In SeaORM prior 0.11, running the following query twice works fine:

```sql
INSERT INTO \"group_user_membership\" (\"user_id\", \"group_id\") VALUES ('01GVEMDSKK33QX8ET4601B4HG7', '00000000000000000000000000') ON CONFLICT (\"group_id\", \"user_id\") DO NOTHING"
```

Running it on 0.11.x results in `DbErr::RecordNotInserted`

## Steps to Reproduce

1. Insert a record
2. Insert a conflicting record instructing to do nothing on conflict

### Expected Behavior

No error, not records inserted.

### Actual Behavior

Get an error: `DbErr::RecordNotInserted`

### Reproduces How Often

Every single time.

### Workarounds

Check for `DbErr::RecordNotInserted` prior bubbling error up the stack.

## Reproducible Example

https://github.com/andoriyu/seaorm-issues/blob/main/src/lib.rs#L39-L53

## Versions

0.11.0 and 0.11.1

**Comment by tyt2y3** [comment]
Thanks for the question.

It was an intentionally introduced change. For now, you can match the result to distinguish different cases:

```rust
match result {
    Ok(r) => Ok(Some(r)),
    Err(DbErr::RecordNotInserted) => Ok(None),
    Err(e) => Err(e),
}
```

In the future we might add a convenience method for it.
