### ISSUE TITLE
Released versions missmach?

### ISSUE THREAD

**Issue by nagua** [SeaQL/sea-orm#1566]
## Description

I see that you released a new version recently. On Github is says that version `0.11.2` was released. On crates.io there is no version `0.11.2` instead there is a version `0.12.0`. One of these versions seems to have been released wrongly.

## Steps to Reproduce

1. Look at github release page and check version
2. Look at crates.io and check released version

### Expected Behavior

github and crates.io versions are the same.

### Actual Behavior

github and crates.io versions differ.

### Reproduces How Often

Always.

**Comment by billy1624** [comment]
Hey @nagua, thanks for the prompt! Yes, it's a mistake. I just yanked `0.12.0` and released `0.11.2`.

**Comment by tyt2y3** [comment]
Thanks for the nudge!
