### ISSUE TITLE
sea_orm::Values should implement ToSQL + Sync

### ISSUE THREAD

**Issue by AdamJSoftware** [SeaQL/sea-orm#1568]
I am trying to use my deadpool postgres connection with SeaORM. However, after getting my SQL statement. I cannot use the associated values as "expected referece &[&dyn ToSQL + Sync] found reference &std::Option::Value".

This is somehow implemented for sea query but not for sea orm? Slightly confused

**Comment by tyt2y3** [comment]
You can only use SQLx to connect to Postgres right now.
SeaORM has a tight integration with SQLx, e.g. the pooling and transaction mechanism.

To clear the confusion, SeaQuery is the underlying query builder, which we provide integration for `postgres` via `sea-query-postgres`. So if you add that crate to your dep, it will impl `ToSQL` for (wrapped) Value.

Checkout this example https://github.com/SeaQL/sea-query/blob/master/examples/postgres/src/main.rs.

To get the best experience out of SeaORM, definitely use SQLx.

**Comment by tyt2y3** [comment]
Let me know if there is still confusion
