### ISSUE TITLE
attempt to multiply with overflow

### ISSUE THREAD

**Issue by Sky-000** [SeaQL/sea-orm#1575]
## Describe
When I try to query with { page_size: 20, page: 18446744073709551615 }, panicked occurs, instead of throwing an exception, resulting in no response from behind the program. 
Although he is not a number that can be used in normal business, I also hope to be able to catch this exception instead of panicked

### Expected Behavior

back to DbErr

### Actual Behavior

panicked

### Exception

thread 'tokio-runtime-worker' panicked at 'attempt to multiply with overflow', xxx/github.com-1ecc6299db9ec823/sea-orm-0.11.2/src/executor/paginator.rs:49:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

## Versions

sea-orm v0.11.2

**Comment by tyt2y3** [comment]
Thank you for your suggestion. But I don't think overflow and underflow deemed to be an error to be handled.
I sugguest you to check the input parameters beforehand.
