### ISSUE TITLE
The database is bigint, the data is added successfully, but the query is abnormal

### ISSUE THREAD

**Issue by 107295472** [SeaQL/sea-orm#1581]
Query Error: error occurred while decoding column "rmb": mismatched types; Rust type `core::option::Option<i64>` (as SQL type `BIGINT`) is not compatible with SQL type `DECIMAL`
mysql    
![image](https://user-images.githubusercontent.com/6436116/230258079-c0ac55d5-535e-4238-bc45-7c09a77d9e4a.png)

**Comment by tyt2y3** [comment]
Can you share the table schema and your entity definition?

**Comment by 107295472** [comment]
`//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.0

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "alct_api_driver"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct Model {
    pub id: i32,
    pub a: Option<String>,
    pub b: Option<String>,
    pub c: Option<String>,
    pub name: Option<String>,
    pub rmb: Option<i64>,
    pub dalct: Option<String>,
    pub alct: Option<String>,
    pub h: Option<String>,
    pub i: Option<String>,
    pub j: Option<String>,
    pub k: Option<String>,
    pub l: Option<String>,
    pub m: Option<String>,
    pub n: Option<String>,
    pub o: Option<String>,
    pub p: Option<String>,
    pub q: Option<String>,
    pub r: Option<String>,
    pub s: Option<String>,
    pub t: Option<String>,
    pub u: Option<String>,
    pub v: Option<String>,
    pub desc: Option<String>,
    pub status: Option<i8>,
    pub username: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    A,
    B,
    C,
    Name,
    Rmb,
    Dalct,
    Alct,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    T,
    U,
    V,
    Desc,
    Status,
    Username,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i32;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Integer.def(),
            Self::A => ColumnType::String(Some(500u32)).def().null(),
            Self::B => ColumnType::String(Some(500u32)).def().null(),
            Self::C => ColumnType::String(Some(500u32)).def().null(),
            Self::Name => ColumnType::String(Some(500u32)).def().null(),
            Self::Rmb => ColumnType::BigInteger.def().null(),
            Self::Dalct => ColumnType::String(Some(500u32)).def().null(),
            Self::Alct => ColumnType::String(Some(500u32)).def().null(),
            Self::H => ColumnType::String(Some(500u32)).def().null(),
            Self::I => ColumnType::String(Some(500u32)).def().null(),
            Self::J => ColumnType::String(Some(500u32)).def().null(),
            Self::K => ColumnType::String(Some(500u32)).def().null(),
            Self::L => ColumnType::String(Some(500u32)).def().null(),
            Self::M => ColumnType::String(Some(500u32)).def().null(),
            Self::N => ColumnType::String(Some(500u32)).def().null(),
            Self::O => ColumnType::String(Some(500u32)).def().null(),
            Self::P => ColumnType::String(Some(500u32)).def().null(),
            Self::Q => ColumnType::String(Some(500u32)).def().null(),
            Self::R => ColumnType::String(Some(500u32)).def().null(),
            Self::S => ColumnType::String(Some(500u32)).def().null(),
            Self::T => ColumnType::String(Some(500u32)).def().null(),
            Self::U => ColumnType::String(Some(500u32)).def().null(),
            Self::V => ColumnType::String(Some(500u32)).def().null(),
            Self::Desc => ColumnType::String(Some(500u32)).def().null(),
            Self::Status => ColumnType::TinyInteger.def().null(),
            Self::Username => ColumnType::String(Some(255u32)).def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
`

**Comment by 107295472** [comment]
![image](https://user-images.githubusercontent.com/6436116/230516749-2a1ec05f-2522-4936-a740-9f54d3894e62.png)

**Comment by 107295472** [comment]
![image](https://user-images.githubusercontent.com/6436116/230522091-c85b9b65-c8fb-4df9-ad1f-6a41f0cb5e4a.png)

**Comment by tyt2y3** [comment]
I don't think it is immediately obvious that this is a bug. Please open a PR with a reproducible example, or we'll not be able to proceed.

**Comment by 107295472** [comment]
![image](https://user-images.githubusercontent.com/6436116/230576000-daaec1d8-2b2b-4dba-bab9-ff501111b8dc.png)

**Comment by 107295472** [comment]
gggg

**Comment by 107295472** [comment]
`Source Server         : mysql
 Source Server Type    : MariaDB
 Source Server Version : 100418
 Source Host           : 192.168.10.22:3308
 Source Schema         : alct_api

 Target Server Type    : MariaDB
 Target Server Version : 100418
 File Encoding         : 65001

 Date: 10/04/2023 09:56:56
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for alct_api_driver1
-- ----------------------------
DROP TABLE IF EXISTS `alct_api_driver1`;
CREATE TABLE `alct_api_driver1`  (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `a` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `b` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `c` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `name` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `dalct` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `rmb` bigint(20) NULL DEFAULT NULL,`

**Comment by 107295472** [comment]
![image](https://user-images.githubusercontent.com/6436116/230810807-13be87f4-c933-4f0d-8b9e-c82b4d933c7f.png)

**Comment by 107295472** [comment]
gg
