### ISSUE TITLE
sqlite Integer columns associated with wrong rust data type

### ISSUE THREAD

**Issue by bmiyuan** [SeaQL/sea-orm#1594]
## Description

when I use  sea-orm-codegen 0.11.0 generated  `SeaORM` Entity, if associates Integer columns of sqlite, all treat these Integer column as representing i32, but as per the sqlite documentation this column type can represent up to 64 bits.

## Steps to Reproduce
create any table which include integer column, and then use sea-orm-cli generate the seaorm entity, it will show i32 data type.

### Expected Behavior
can we produce the i64 data type?

### Actual Behavior

it produce i32 data type now

### Workarounds

now I just update the type from i32 to i64 manually in the seaorm entity

## Versions

sqlite 3.39.3
rust  1.67.0

**Comment by tyt2y3** [comment]
We have a discussion like this before, the short answer is if you want to `i64` you use `big_integer`, as this aligns with MySQL / Postgres
