### ISSUE TITLE
`LinkDef` with custom join condition

### ISSUE THREAD

**Issue by tyt2y3** [SeaQL/sea-orm#160]
Right now, `LinkDef` is simply an alias of `RelationDef`.
We can design a richer API for `LinkDef` that impl `From<RelationDef>`:

```rust
pub struct CakeToFilling;

impl Linked for CakeToFilling {
    type FromEntity = Entity;

    type ToEntity = super::filling::Entity;

    fn link(&self) -> Vec<LinkDef> {
        vec![
            super::cake_filling::Relation::Cake.def().rev().into()
                .and_on_condition(Expr::cust("a = b")),
            super::cake_filling::Relation::Filling.def().into(),
        ]
    }
}
```

This will open more flexibilities. Unfortunately it is a breaking change, thus has to wait until `0.3.0`

**Comment by tyt2y3** [comment]
Close with lack of interest

**Comment by Tuetuopay** [comment]
@tyt2y3 you should reopen this, as there is currently no way to specify an `ON` clause when joining tables, which is mandatory for some usecases (some are impossible to do with a `WHERE` clause).

**Comment by tyt2y3** [comment]
I would appreciate if you can suggest some test entities )

**Comment by Tuetuopay** [comment]
Sure! I don't have any case with the bakery entities, but here's one that could very well happen: soft-delete filtering.

Say you have two entities, `User` and `BlogPost`, the latter having a `deleted` boolean field (the former could very well have one, but it's irrelevant in the discussion), indicating whether the user has deleted the blog post.

### `user.rs`

```rust
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
}
#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::post::Entity")]
    Post,
}
impl ActiveModelBehavior for ActiveModel {}
```

### `post.rs`

```rust
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "post")]
pub struct Post {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub deleted: bool,
    pub user_id: i32,
    pub created_at: DateTime,
    pub title: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::UserId",
        to = "super::user::Column::Id"
    )]
    User,
}
```

Now, to fetch one user and its latest blog post in a single query, it's not possible to do so without a custom `ON` clause:

```sql
SELECT "user".*, "post".*
FROM "user"
LEFT JOIN "post" ON "post"."user_id" = "user"."id" AND "post"."deleted" = false
ORDER BY "post"."created_at" DESC
WHERE "user"."id" = ?
LIMIT 1
```

The above SQL works in all cases, including the case where the user has no blog post. Indeed, if trying to move the deletion test to the `WHERE` clause, it breaks this case:

```sql
SELECT "user".*, "post".*
FROM "user"
LEFT JOIN "post" ON "post"."user_id" = "user"."id"
ORDER BY "post"."created_at" DESC
WHERE "user"."id" = ? AND "post"."deleted" = false
LIMIT 1
```

Indeed:
- if the user has no blog post, the left join will yield a single row, with `post` columns being `null`, which will be filtered out as the `deleted` column will be `null`, which is not the same as false. this case can be handled clumsily with `AND ("post"."deleted" = false OR "post"."deleted" IS NULL)`
- if the user has only deleted blog posts, the left join will yield one (or more) rows, with all `deleted` fields set to `true`, which will all be filtered out, hence the query yielding no rows at all.

Hope this helps! While softdelete is not the only usecase for this (e.g. posts have a tag, getting the user and its latest post in a single category also works), it's the easier and the most widespread usecase. Also, it has bitten me in production several times.

**Comment by billy1624** [comment]
We are implementing soft delete now at #276. Do you wanna try it out?

**Comment by billy1624** [comment]
Hey @Tuetuopay, indeed!!

**Comment by MattGson** [comment]
This applies to all cases where we want to filter the right-hand table, not just soft-deletions.

**Comment by billy1624** [comment]
Hey @tyt2y3, I have a counter proposal.

Why don't we allow custom join condition on `RelationDef`? I guess it's probably because you don't want to mix details of the join expression into `RelationDef`?

But I think it would be useful to automatically apply the custom join condition when user invoking:

https://github.com/SeaQL/sea-orm/blob/183639dc8c817fbd3211a87c67bcb983db4050ed/src/query/helper.rs#L152-L183

Also, custom join condition will be applied when user call `find_related` & `find_linked` methods for relational selects, as these method invoke the join methods above.

I imagine the API be like:

```rs
#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::cake::Entity",
        from = "Column::CakeId",
        to = "super::cake::Column::Id",
        and_on_condition = "Column::CakeId.gt(10)"
    )]
    Cake,
}
```

I got an pending issue with no "good" solution to it, as I mention in #767:

When we call `find_linked`, we have a case where the RHS (right hand side) table in join expression is being renamed during runtime when user construct the query with `find_linked` method.

```sql
SELECT
    `filling`.`id`,
    `filling`.`name`,
    `filling`.`vendor_id`
FROM
    `filling`
    INNER JOIN `cake_filling` AS `r0` ON `r0`.`filling_id` = `filling`.`id`
    INNER JOIN `cake` AS `r1` ON `cake`.`id` > 2 /* This shoule be "`r1`.`id` > 2" */
    AND `r1`.`id` = `r0`.`cake_id`
WHERE
    `r1`.`id` = 12
```

A possible solution:

`and_on_condition` and `and_on_condition` methods could take a lambda function which has table `DynIden` of LHS and RHS provided. i.e.

```rs
pub fn and_on_condition<C>(mut self, func: F) -> Self
where
    F: Fn(DynIden, DynIden) -> SimpleExpr,
{
    ...
}
```

**Comment by liberwang1013** [comment]
I have same problem. In my situation. I have three entity

### **woker.rs**
```
use sea_orm::entity::prelude::*;
use sea_orm::sea_query::Expr;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, Default, PartialEq, DeriveEntityModel, Deserialize, Serialize)]
#[sea_orm(table_name = "workers", schema_name = "public")]
pub struct Model {
    #[sea_orm(primary_key, column_name = "id")]
    #[serde(skip_deserializing)]
    pub id: i64,
    pub name: String,
    pub description: String,
}

impl ActiveModelBehavior for ActiveModel {}

```
### **label.rs**
```
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Deserialize, Serialize)]
#[sea_orm(table_name = "labels", schema_name = "public")]
pub struct Model {
    #[sea_orm(primary_key, column_name = "id")]
    #[serde(skip_deserializing)]
    pub id: i64,
    pub title: String,
    pub description: String,
}

impl ActiveModelBehavior for ActiveModel {}

```

### **label_link.rs**
```
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Deserialize, Serialize)]
#[sea_orm(table_name = "label_links", schema_name = "public")]
pub struct Model {
    #[sea_orm(primary_key, column_name = "id")]
    #[serde(skip_deserializing)]
    pub id: i64,
    pub label_id: i64,
    pub target_id: i64,
    pub target_type: String,
}

impl ActiveModelBehavior for ActiveModel {}
```


### My Problem
In my case , I use **target_type** field to known the actual resource this label related. So I hope the generated sql can add a extra condition like 
```
label_links.target_type = 'worker'
```
I hope add one more field  In **RelationDef** to support extra join condition.

**Comment by liberwang1013** [comment]
> I have same problem. In my situation. I have three entity
> ### **woker.rs**
> 
> ```
> use sea_orm::entity::prelude::*;
> use sea_orm::sea_query::Expr;
> use serde::{Deserialize, Serialize};
> 
> #[derive(Clone, Debug, Default, PartialEq, DeriveEntityModel, Deserialize, Serialize)]
> #[sea_orm(table_name = "workers", schema_name = "public")]
> pub struct Model {
>     #[sea_orm(primary_key, column_name = "id")]
>     #[serde(skip_deserializing)]
>     pub id: i64,
>     pub name: String,
>     pub description: String,
> }
> 
> impl ActiveModelBehavior for ActiveModel {}
> ```
> 
> ### **label.rs**
> 
> ```
> use sea_orm::entity::prelude::*;
> use serde::{Deserialize, Serialize};
> 
> #[derive(Clone, Debug, PartialEq, DeriveEntityModel, Deserialize, Serialize)]
> #[sea_orm(table_name = "labels", schema_name = "public")]
> pub struct Model {
>     #[sea_orm(primary_key, column_name = "id")]
>     #[serde(skip_deserializing)]
>     pub id: i64,
>     pub title: String,
>     pub description: String,
> }
> 
> impl ActiveModelBehavior for ActiveModel {}
> ```
> 
> ### **label_link.rs**
> 
> ```
> use sea_orm::entity::prelude::*;
> use serde::{Deserialize, Serialize};
> 
> #[derive(Clone, Debug, PartialEq, DeriveEntityModel, Deserialize, Serialize)]
> #[sea_orm(table_name = "label_links", schema_name = "public")]
> pub struct Model {
>     #[sea_orm(primary_key, column_name = "id")]
>     #[serde(skip_deserializing)]
>     pub id: i64,
>     pub label_id: i64,
>     pub target_id: i64,
>     pub target_type: String,
> }
> 
> impl ActiveModelBehavior for ActiveModel {}
> ```
> 
> ### My Problem
> 
> In my case , I use **target_type** field to known the actual resource this label related. So I hope the generated sql can add a extra condition like
> 
> ```
> label_links.target_type = 'worker'
> ```
> 
> I hope add one more field In **RelationDef** to support extra join condition.

Here is my experiment implement for extra condition support https://github.com/liberwang1013/sea-orm/pull/2, through I can using this code to custom join condition

```
impl Related<super::label::Entity> for Entity {
    fn to() -> RelationDef {
        super::label_link::Relation::Label.def()
    }

    fn via() -> Option<RelationDef> {
        let mut def = super::label_link::Relation::Worker.def().rev();
        let expr = Expr::tbl(
            super::label_link::Entity,
            super::label_link::Column::TargetType,
        )
        .eq("worker");
        def.extra_condition = Some(expr);
        Some(def)
    }
}
```
and the generated sql will be like 
```
SELECT
      "workers"."id" AS "A_id",
      "workers"."name" AS "A_name",
      "workers"."description" AS "A_description",
      "labels"."id" AS "B_id",
      "labels"."title" AS "B_title",
      "labels"."description" AS "B_description"
    FROM
      "public"."workers"
      LEFT JOIN "public"."label_links" ON ("workers"."id" = "label_links"."target_id")
      AND ("label_links"."target_type" = $1)
      LEFT JOIN "public"."labels" ON "label_links"."label_id" = "labels"."id"
    WHERE
      "workers"."id" = $2
    ORDER BY
      "workers"."id" ASC
```
