### ISSUE TITLE
Derive macro `FromQueryResult` generic bound not always correct

### ISSUE THREAD

**Issue by Goodjooy** [SeaQL/sea-orm#1602]
## Description
In most situation, macro `FromQueryResult` work find, but if the field not direct a type generic but its associate type, the macro output might have problem.

the following code snippet cannot compile
```rust
    trait FooTrait {
        type Bar;
    }

    #[derive(FromQueryResult)]
    struct Foo<F: FooTrait> {
        bar: F::Bar
    }
```
Through the `cargo expand`,
```rust
    #[automatically_derived]
    impl<F: FooTrait + sea_orm::TryGetable> sea_orm::FromQueryResult for Foo<F> {
        fn from_query_result(
            row: &sea_orm::QueryResult,
            pre: &str,
        ) -> std::result::Result<Self, sea_orm::DbErr> {
            Ok(Self {
                bar: row.try_get(pre, "bar")?,
            })
        }
    }
```
In the implement block, the bound apply on `F`, but the correct bound should on `F::Bar`

## Steps to Reproduce

1. a struct with generic type. The generic type 's bound contain associate type

2. In the struct, not direct using generic type as its field. Using the associate type of that generic type 

### Expected Behavior

In implement block, the bound `TryGetable` should apply on each field's type like following
```rust
#[automatically_derived]
impl<F: FooTrait> sea_orm::FromQueryResult for Foo<F> 
where F::Bar: sea_orm::TryGetable
{
    fn from_query_result(
        row: &sea_orm::QueryResult,
        pre: &str,
    ) -> std::result::Result<Self, sea_orm::DbErr> {
        Ok(Self {
            bar: row.try_get(pre, "bar")?,
        })
    }
}
```

### Actual Behavior

The bound `TryGetable` apply on all type generic , regardless whether it is a field's type or not

**Comment by tyt2y3** [comment]
Can you propose the correct code to be generated?

**Comment by billy1624** [comment]
Hey @Goodjooy, thanks for the report!!

A warm ping to @leviska, the original author of https://github.com/SeaQL/sea-orm/pull/1464.

## Current behaviour

```
#[derive(FromQueryResult)]
struct DoubleGenericTest<T, F> {
    _foo: T,
    _bar: F,
}
```

The `FromQueryResult` derive macro will generate the following...

```
#[automatically_derived]
impl<T, F> sea_orm::FromQueryResult for DoubleGenericTest<T, F>
where
    // Both trait bounds are added automatically by `FromQueryResult` derive macro
    T: sea_orm::TryGetable,
    F: sea_orm::TryGetable,
{
    fn from_query_result(row: &sea_orm::QueryResult, pre: &str) -> std::result::Result<Self, sea_orm::DbErr> {
        Ok(Self {
            #(#field: row.try_get(pre, #name)?),*
        })
    }
}
```

## Proposed behavior

Instead, we should let user to specify the trait bound...

```
#[derive(FromQueryResult)]
struct DoubleGenericTest<T, F>
where
    // The trait bound defined here will be propagated to the impl `FromQueryResult` generated by the `FromQueryResult` derive macro
    T: sea_orm::TryGetable,
    F: sea_orm::TryGetable,
{
    _foo: T,
    _bar: F,
}
```

It's a shift in the design. User has to define the trait bounds manually and `TryGetable` trait bound will NOT be added to each generic types.

Any thoughts? @Goodjooy @leviska

**Comment by Goodjooy** [comment]
> Can you propose the correct code to be generated?

Sorry, I forgot it. I have added one

**Comment by Goodjooy** [comment]
>It's a shift in the design. User has to define the trait bounds manually and TryGetable trait bound will NOT be added to each generic types.

I'd like to add `TryGetable` trait bound on each field of the struct.  The type generic argument may not be a field's type, so directly adding a `TryGetable` trait bound on each type generic is not always correct

**Comment by leviska** [comment]
I think a good idea is to look how serde does that
Because [it works](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=fcda334291449eed40917aaaf18cc151) with given example, without specifying the bounds

From a quick look at the code, it seems that it's adding bounds [here](https://github.com/serde-rs/serde/blob/master/serde_derive/src/ser.rs#L137)
 
And... well, it looks very complicated. Sadly. But it seems that there is a lot of stuff is to make it work with serde attributes. 
I was hoping there is an easy way to implement this functionality, because it feels kinda basic for rust, but I'm not sure now 

I think current PR is a good balance between allowing generics to work, and not getting buried in supporting everything

**Comment by tyt2y3** [comment]
Thank you @ everyone's involvement in this pre-release feature.

It will be difficult to clarify/rectify for a bug report to appear after release.

**Comment by billy1624** [comment]
Hey @leviska, thanks for the input!! I think it's better to ship the feature with verbosity at first then tune it afterward.
