### ISSUE TITLE
sea-orm-cli 0.11.2 regex bug

### ISSUE THREAD

**Issue by Toursslivers** [SeaQL/sea-orm#1608]
## Description
update sea-orm-cli 0.11.0 -> 0.11.2
regex bug

## Steps to Reproduce
1. cargo install sea-orm-cli
2. sea-orm-cli 0.11.0 -> 0.11.2
3. sea-orm-cli generate entity --with-serde both -o entity/src/entities
4. regex bug

## Versions
sea-orm-cli 0.11.2

**Comment by billy1624** [comment]
Hey @Toursslivers, thanks for letting us know. This has been fixed by the tracing team: https://github.com/tokio-rs/tracing/pull/2566.

Please reinstall the `sea-orm-cli` and it should be working just fine.

```
cargo install sea-orm-cli --force
```

Please re-open this if you still encountered any difficulties :)
