### ISSUE TITLE
find_also_linked produces Unknown column error in on clause

### ISSUE THREAD

**Issue by TerranWorks** [SeaQL/sea-orm#1637]
## Description

I have two tables, post and post_meta. Post contains two foreign keys (post_data, and original_post_data) which both point to post_meta. I created these tables in MySQL, used sea-orm-cli to generate code for them, and then created a struct and implemented Link for it. If I try to use ``find_also_linked`` I get ``Unknown column 'r0.original_post_data' in 'on clause'``. 

It could be that find_also_linked simply does not support two connections between tables like this (I was mostly just experimenting). If this is the case, I'd be okay with using custom joins or some other method, but this seems like a simple bug, so I thought I should report it. I think this is a cool project, btw.

## Steps to Reproduce

The SQL script used to generate my tables:
```sql
CREATE TABLE IF NOT EXISTS post_meta (
    id INT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (id),

    title VARCHAR(255) NOT NULL,
    created TIMESTAMP NOT NULL,
    updated TIMESTAMP NOT NULL
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS post (
    id INT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (id),

    post_data INT NOT NULL,
    CONSTRAINT fk_post_data
    FOREIGN KEY (post_data)
    REFERENCES post_meta(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    original_post_data INT,
    CONSTRAINT fk_original_post_data
    FOREIGN KEY (original_post_data)
    REFERENCES post_meta(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
) ENGINE=INNODB;
```

The relations generated for post by sea_orm_cli: with some tweaking according to [this guide](https://billy1624.github.io/sea-orm-tutorial/introduction.html):
```rust
#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "crate::PostMeta",
        from = "Column::OriginalPostData",
        to = "crate::PostMetaColumn::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    OriginalPostData,
    #[sea_orm(
        belongs_to = "crate::PostMeta",
        from = "Column::PostData",
        to = "crate::PostMetaColumn::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    PostData,
}
```

My Link code and my simple test:
```rust
    #[derive(Debug)]
    pub struct PostToPostMeta;
    impl Linked for PostToPostMeta {
        type FromEntity = Post;
        type ToEntity = PostMeta;

        fn link(&self) -> Vec<RelationDef> {
            vec![
                PostRelation::PostData.def(),
                PostRelation::OriginalPostData.def(),
            ]
        }
    }

    let post_select = Post::find()
    .find_also_linked(PostToPostMeta);
 
    dbg!(post_select.all(&db).await?);
    //println!("{}", post_select.build(DbBackend::MySql).to_string());
```

### Expected Behavior

I believe I'm expecting a Vec<(Model, Option<Model>)> but I'm not sure my use case is supported. The error seems like a bug, though.

### Actual Behavior

I get a MySQL error: Unknown column 'r0.original_post_data' in 'on clause'

### Reproduces How Often

Consistently. It seems to be a bug in the SQL generation.

### Workarounds

If I render the SQL expression generated by sea_orm I get:
```sql
SELECT 
	`post`.`id` AS `A_id`, 
	`post`.`post_data` AS `A_post_data`, 
	`post`.`original_post_data` AS `A_original_post_data`, 
	`r1`.`id` AS `B_id`, 
	`r1`.`title` AS `B_title`, 
	`r1`.`created` AS `B_created`, 
	`r1`.`updated` AS `B_updated` 
FROM `post` 
LEFT JOIN `post_meta` AS `r0` 
	ON `post`.`post_data` = `r0`.`id` 
LEFT JOIN `post_meta` AS `r1` 
	ON `r0`.`original_post_data` = `r1`.`id`
```
If I run this statement manually in MySQL I get the same error and if I change 'r0' on the last line to 'post'. I get the expected selection.

If I comment out either ``PostRelation::PostData.def()`` or ``PostRelation::OriginalPostData.def()`` in my impl Linked definition, the program produces no error and displays the correct result.

## Reproducible Example

I'm right at the beginning of my project, so I think my above example is fairly minimal.

## Versions

```zsh
$ cargo tree | grep sea-
├── sea-orm v0.11.3
│   ├── sea-orm-macros v0.11.3 (proc-macro)
│   ├── sea-query v0.28.4
│   │   └── sea-query-derive v0.3.0 (proc-macro)
│   ├── sea-query-binder v0.3.0
│   │   ├── sea-query v0.28.4 (*)
│   ├── sea-strum v0.23.0
│   │   └── sea-strum_macros v0.23.0 (proc-macro)
```

running MariaDB on arch Linux

**Comment by billy1624** [comment]
Hey @TerranWorks, thanks for the detail report!!

The `Linked` API is designed for querying a chain relation so that's why each "JOIN ON" condition is expected to operate on the previous table not the root table. From what I saw above, it's a tree relation where each `Post` has two `PostMeta`.

A side note, maybe consider using data loader? https://www.sea-ql.org/SeaORM/docs/relation/data-loader/

**Comment by TerranWorks** [comment]
Thank you for your quick response, It looks like read the docs incorrectly. It does seem like "load_many" approach from the link you provided is what I'm looking for but I'm unsure how to define the Related impl for a tree relation. Should I mark this issue as closed and link to it an an FAQ  or keep posting here btw?

**Comment by tyt2y3** [comment]
Actually you can impl Linked twice for the same Entity.
