### ISSUE TITLE
add_column_if_not_exists executes abnormally under mysql8.0

### ISSUE THREAD

**Issue by yuhaya** [SeaQL/sea-orm#1642]
```rust
async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        let mut ut = sea_query::Table::alter();
        ut.table(admin::Entity).add_column_if_not_exists(
            ColumnDef::new(admin::Column::Role)
                .tiny_integer()
                .not_null()
                .default(admin::AdminRole::Normal),
        );
        println!("{}", ut.to_string(MysqlQueryBuilder));
        manager.alter_table(ut.to_owned()).await
    }
```

### Gen SQL
ALTER TABLE `admin` ADD COLUMN IF NOT EXISTS `role` tinyint NOT NULL DEFAULT 1
### Output
Execution Error: error returned from database: 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'IF NOT EXISTS `role` tinyint NOT NULL DEFAULT 1' at line 1%
### Cause
mysql cannot directly support ADD COLUMN IF NOT EXISTS

**Comment by tyt2y3** [comment]
This feature only exist in MariaDB 10 AFAIK
