### ISSUE TITLE
Support for Postgres arrays.

### ISSUE THREAD

**Issue by ilyail3** [SeaQL/sea-orm#1659]
Hey everyone, love the design of this library, it might be the reason I switch from FastAPI to rust. I ran into a problem with using current tables, I have a table with a column that is []uuid in postgres, the generator correctly generates the type:
Vec<Uuid> however when compiling I have the following error:
the trait `From<Vec<sea_orm::prelude::Uuid>>` is not implemented for `sea_orm::Value`

I'll dig a bit to figure if I can patch this on my own, but just in case I can't, I'll leave a record.

Also of note: when the column is nullable as well, a different error is thrown:
"the trait `Nullable` is not implemented for `Vec<sea_orm::prelude::Uuid>`"

But that's probably related.

## Motivation

Supporting UUID arrays from Postgres is useful for tables containing aggregations.

## Proposed Solutions

From<Vec<sea_orm::prelude::Uuid>> should be implemented for sea_orm::Value

## Current Workarounds

Remove the column from the generated files, and use custom expressions when I do need to access it.

**Comment by ilyail3** [comment]
Never mind, reading the code, I saw I was missing a feature named "postgres-array" adding that fixed the issue, maybe should be documented somewhere.

**Comment by billy1624** [comment]
Hey @ilyail3, in the coming releasing `postgres-array` will be enabled when postgres backend is turned on. That should ease the confusion.

- https://github.com/SeaQL/sea-orm/pull/1565
