### ISSUE TITLE
https://www.sea-ql.org/SeaORM/docs/install-and-config/database-and-async-runtime/

### ISSUE THREAD

**Issue by Kreijstal** [SeaQL/sea-orm#1668]
it says `rustls` is a pure rust implementation, which can't be true, since it depends on `ring`.

**Comment by tyt2y3** [comment]
Can you suggest a better wording without being tl;dr while remaining accurate?

**Comment by Kreijstal** [comment]
"rustls is a TLS library predominantly implemented in Rust, with a dependency on *ring* for cryptographic operations."

**Comment by Kreijstal** [comment]
there exist now https://github.com/RustCrypto/rustls-rustcrypto which is a PURE rust rustls alternative.
