### ISSUE TITLE
Support returning in update many

### ISSUE THREAD

**Issue by Sytten** [SeaQL/sea-orm#1669]
## Motivation

Currently only `update` supports the `RETURNING` clause, but not the `update_many`.
This is limiting since sometimes you need to use an `update_many` when the `update` doesn't support a feature (like a column expression) but then you lose the returning.

## Proposed Solutions

Add `exec_with_returning` to the `UpdateMany` struct.

## Current Workarounds

You have to select back the rows.

**Comment by billy1624** [comment]
Hey @Sytten, good suggestion!! I think it's possible and nice to have :)

**Comment by Sytten** [comment]
Thanks!
