### ISSUE TITLE
i8 enum value is mistaken for a char in postgresql

### ISSUE THREAD

**Issue by lucat1** [SeaQL/sea-orm#1673]
## Description

`i8` enum value is sent as a `char` in query statements.

## Steps to Reproduce

1. define an enum such as:
```rs
#[derive(Serialize, Debug, Clone, Copy, PartialEq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "i8", db_type = "Integer")]
pub enum TestEnum {
  #[sea_orm(num_value = 0)]
  A,
  #[sea_orm(num_value = 1)]
  B
}
```
3. Use it in a query, for example I came up this issue using `INSERT`s.
4. It will error saying: `column "xx" is of type integer but expression is of type "char"`

### Expected Behavior

This works fine on sqlite. I haven't tried on mysql. Still, this should either be fixed or a note against using `i8` for enums shall be added to the docs.

### Actual Behavior

Errors only in postgresql.

### Reproduces How Often

Always.

### Workarounds

Changing the `rs_type` to `i32` for example, which cannot be mistaken for an ASCII 8bit char solves the issue.

## Versions

```
├── sea-orm v0.11.3
│   ├── sea-orm-macros v0.11.3 (proc-macro)
│   ├── sea-query v0.28.5
│   │   ├── sea-query-derive v0.3.0 (proc-macro)
│   ├── sea-query-binder v0.3.1
│   │   ├── sea-query v0.28.5 (*)
│   ├── sea-strum v0.23.0
│   │   └── sea-strum_macros v0.23.0 (proc-macro)
├── sea-orm-migration v0.11.3
│   ├── sea-orm v0.11.3 (*)
│   ├── sea-orm-cli v0.11.3
│   │   ├── sea-schema v0.11.0
│   │   │   ├── sea-query v0.28.5 (*)
│   │   │   └── sea-schema-derive v0.1.0 (proc-macro)
│   ├── sea-schema v0.11.0 (*)
│   ├── sea-orm v0.11.3 (*)
│   ├── sea-query v0.28.5 (*)
├── sea-orm v0.11.3 (*)
├── sea-orm-migration v0.11.3 (*)
└── sea-orm-migration v0.11.3 (*)
├── sea-orm v0.11.3 (*)
├── sea-orm-migration v0.11.3 (*)
```

Postgres: `PostgreSQL 15.3` from latest `postgresql:alpine` on docker.

**Comment by billy1624** [comment]
Hey @lucat1, thanks for asking! Yes, changing the `rs_type` to any integer types except `i8` will solve the problem. This limitation comes from the fact that Postgres treat `i8` as `char`.

<img width="673" alt="image" src="https://github.com/SeaQL/sea-orm/assets/30400950/0628c1ff-6eb0-485d-9cf9-3e4353a741b4">

https://www.sea-ql.org/SeaORM/docs/generate-entity/entity-structure/#column-type

**Comment by lucat1** [comment]
I see. Thank you for the explanation and I think we can close this.

**Comment by billy1624** [comment]
No problem :)
