### ISSUE TITLE
[SECURITY] bump to sqlx 0.7.0

### ISSUE THREAD

**Issue by Elizafox** [SeaQL/sea-orm#1753]
## Description

libsqlite3-sys has a [high severity security advisory](https://github.com/advisories/GHSA-jw36-hf63-69r9). sqlx depends on libsqlite3-sys for sqlite support.

The fix has landed in sqlx 0.7.0: https://github.com/launchbadge/sqlx/pull/2387

The sqlx dependency must be updated to fix the issue.

### Workarounds

Avoiding huge (billions of character) inputs should prevent triggering the security issue. Sanitising potentially large inputs before passing them to SeaORM should prevent the problem.

## Versions

HEAD, and all released supported versions.

**Comment by billy1624** [comment]
Hey @Elizafox, thanks for the report!! We're aware of the issue and will be be upgraded to SQLx v0.7

**Comment by Elizafox** [comment]
Awesome. I didn't see a report, so I reported it.

**Comment by k-bx** [comment]
Awesome. Can we expect a crate release today? 🙏

**Comment by tyt2y3** [comment]
Please do not push for a release. At the same time we are doing our best.
