### ISSUE TITLE
How to Create Multiple Tables in Migration

### ISSUE THREAD

**Issue by TheBlindM** [SeaQL/sea-orm#1760]
## Description

How to Create Multiple Tables in Migration

## Steps to Reproduce

```
 async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        // Replace the sample below with your own migration scripts
			  manager
				.create_table(
					Table::create()
						.table(Session::Table)
						.if_not_exists()
						.col(
							ColumnDef::new(Session::Id)
								.integer()
								.not_null()
								.auto_increment()
								.primary_key(),
						)
						.col(ColumnDef::new(Session::SessionName).string().not_null())
						.to_owned(),
				).await?;
			 manager
				.create_table(
					Table::create()
						.table(SshSession::Table)
						.if_not_exists()
						.col(
							ColumnDef::new(SshSession::Id)
								.integer()
								.not_null()
								.auto_increment()
								.primary_key(),
						)
						.col(ColumnDef::new(SshSession::AuthType).integer().not_null())
						.col(ColumnDef::new(SshSession::ProxyType).integer().not_null())
						.col(ColumnDef::new(SshSession::TtyType).string().not_null())
						.col(ColumnDef::new(SshSession::SessionId).integer().not_null())
						.col(ColumnDef::new(SshSession::Ip).string().not_null())
						.to_owned(),
				).await?;

    }
```

## Versions
last

**Comment by snipextt** [comment]
Did you maybe forgot to return an Ok(()) from the function?

**Comment by TheBlindM** [comment]
> Did you maybe forgot to return an Ok(()) from the function?

What are the specifications for using Migration?
Should I put the modifications of one version together or a table with mXXXX_ Create_ Table. rs?

**Comment by snipextt** [comment]
> What are the specifications for using Migration? Should I put the modifications of one version together or a table with mXXXX_ Create_ Table. rs?

I think it depends on your own preference. I personally feel having a different migrations for different versions of your app/incremental features makes more sense. However the former can help you maintain your schema better if that's what you prefer. I am not aware if either of them is a recommendation when using seaorm.

**Comment by TheBlindM** [comment]
> > What are the specifications for using Migration? Should I put the modifications of one version together or a table with mXXXX_ Create_ Table. rs?
> 
> I think it depends on your own preference. I personally feel having a different migrations for different versions of your app/incremental features makes more sense. However the former can help you maintain your schema better if that's what you prefer. I am not aware if either of them is a recommendation when using seaorm.

Okay, thank you
