### ISSUE TITLE
migration：only the first clause executed in alter statements!

### ISSUE THREAD

**Issue by xdewx** [SeaQL/sea-orm#1784]
## Description
```rust
manager
            .alter_table(
                Table::alter()
                    .table(Todo::Table)
                    .drop_column(Alias::new("title"))
                    .add_column( ColumnDef::new(Alias::new("title"))
                            .char()
                            .char_len(64)
                            .not_null())
                    .to_owned(),
            )
            .await
```
as the above code, `drop_column` will be execute, but `add_column` will not!

## Steps to Reproduce
1. create table
2. alter table

## Versions
sea-orm-cli v0.11.3

**Comment by tyt2y3** [comment]
Depending on the backend, AFAIK multiple ADD/DROP in one alter statement cannot affect the same column.
You have to use ALTER COLUMN.

**Comment by tyt2y3** [comment]
Well noted.

**Comment by chayleaf** [comment]
I don't think this should be closed? This is very confusing, so it should either fail at runtime or break the query into multiple queries, I just ran into this and I would've spent quite a while debugging this if I didn't find this

**Comment by tyt2y3** [comment]
It's become difficult to continue the discussion. But if you have a new idea and suggestions on how to implement it, feel free to add them.
