### ISSUE TITLE
migration: `add_column_if_not_exist` not work!

### ISSUE THREAD

**Issue by xdewx** [SeaQL/sea-orm#1785]
## Description

expect `add_column_if_not_exist` return `Ok` when column exists.

## Steps to Reproduce

1. create table and and column `x`
2. `add_column_if_not_exist('x')`

**Comment by tyt2y3** [comment]
Again, this depends on the backend. AFAIK `IF NOT EXISTS` clause does not work everywhere.

**Comment by tyt2y3** [comment]
SeaQuery's AST does not hold version information about the backend.
In general, validness of statements cannot be determined at the point of invocation.
We might need a separate linter for that.
