### ISSUE TITLE
migration: big_integer not work 

### ISSUE THREAD

**Issue by xdewx** [SeaQL/sea-orm#1786]
## Description
```rust
    .col(ColumnDef::new(Plugin::CreatedAt).big_integer().null())
```

expect created_at will be `BIGINT` in sqlite but got INTEGER, this will got `i32` with `generate entity`

## Steps to Reproduce

1. 
2. 
3.

**Comment by tyt2y3** [comment]
More work is required in SeaSchema to implement the type affinity logic.
