### ISSUE TITLE
Support feteching `T`, `(T, U)`, `(T, U, P)`..etc where they impl `TryGetableMany`

### ISSUE THREAD

**Issue by MuhannadAlrusayni** [SeaQL/sea-orm#180]
Hi, I think we need a way to fetch data from database without putting into a `Model`, instead we use tuple or single type, here is what's in my mind:
```rust
// where bool: TryGetableMany
let is_locked: Option<bool> = cake::Account::find()
    .select_only()
    .column(account::Column::IsLocked)
    .into_values() // this would return `Selector<?>`
    .one(db)
    .await?;
```

We can also extend this to `TryGetableMany` it self, that would allow us to write:
```rust
let stmt = "select name, count(post.user_id) as post_count .. group by name";
let user_posts = <(String, i32)>::from_statment(stmt, ["name", "post_count"]) // this would return `Selector<?>`
    .one(db)
    .await?;
```

sounds cool?

**Comment by tyt2y3** [comment]
Sounds cool!

However instead of `T`, perhaps we only allow `(T)` (a unit tuple), that'd be more consistent?

**Comment by MuhannadAlrusayni** [comment]
> However instead of `T`, perhaps we only allow `(T)` (a unit tuple), that'd be more consistent?

That's valid, although currently `TryGetableMany` is implemented for `T` not `(T)`, I think we can do both too. Another reason that I would like to have it for `T` is this use case:
```rust
// account.rs
impl Entity {
    // * `IntermediateType` a type that carry how to get `bool` out of the `QueryResult` internally
    //
    // 1) This function return query instead of boolean value, which make it lazy fetching values,
    //    and give the caller the control when to evaluate this query.
    // 2) returning `(bool)` doesn't feel ergonomic when checking against the returned value.
    //    This might be only me :D
    fn is_locked(id: AccountId) -> Selector<IntermediateType<bool>> {
        cake::Account::find()
            .filter(Column::Id.eq(id))
            .select_only()
            .column(account::Column::IsLocked)
            .into_values()
    }
}
```

> We can also support `.all()` which gets `Vec<T>`?

Yeah definitely, that's why I added `Selector<..>`, we have `one`, `all` and `paginate` :D

**Comment by tyt2y3** [comment]
Wow, this is one level better abstraction

**Comment by billy1624** [comment]
Hey @MuhannadAlrusayni, I was wondering whether you would be interested in implementing it?

**Comment by MuhannadAlrusayni** [comment]
Yeah sure, I was a bit busy last week.

في الاثنين، ٢٧ سبتمبر ٢٠٢١ ٧:٥٧ ص Billy Chan ***@***.***> كتب:

**Comment by billy1624** [comment]
Is okay! Thank you so much!!
