### ISSUE TITLE
find_with_related does not return records with no related entity. It just records that have more than one related entities.

### ISSUE THREAD

**Issue by hamedai** [SeaQL/sea-orm#1800]
1. Create two entities named A and B. A has many Bs. So, B is A's related entity.
2. Create an instance of A that has no B.
3. Now try to retrieve this instance with the following query:
```
a_model::Entity::find().filter(some filters)
                .find_with_related(b_model::Entity)
                .all(db)
                .await?
                .first()
                .map(|t| t.to_owned())
                .into()
```

### Expected Behavior
return A with an empty list of Bs

### Actual Behavior
no A has been returned

### Reproduces How Often
Always

**Comment by hamedai** [comment]
I have checked the generated SQL. It is using left join. and by looking at the logs, it seems that the result has one response.
The example:
This a public repository I was working on: https://github.com/bkonkle/rust-example-caster-api
`users` and `role_grants` have such a relation, they are located in lib/domains.
In the graphQL `router` when it is checking the credential by this code:
```       ctx.users
            .get_by_username(username, &true)
            .await
            .unwrap_or(None)
```
It will try to use the problematic feature I mentioned before.
`/lib/domains/users/service.rs:get_by_username@line 80`
```
            query
                .find_with_related(role_grant_model::Entity)
                .all(&*self.db)
                .await?
                .first()
                .map(|t| t.to_owned())
                .into()
```
Note that the issue does not appear on version 11.*, it is just on version 12.0.1.

**Comment by tyt2y3** [comment]
Oh. You pointed out a regression. I think I have a clue now.

**Comment by hamedai** [comment]
No problem!
I'm looking forward to the next version!

**Comment by tyt2y3** [comment]
Please try [0.12.2](https://crates.io/crates/sea-orm/0.12.2).

**Comment by tyt2y3** [comment]
@hamedai appreciate if you can let me know if it's good

**Comment by hamedai** [comment]
Thanks, Chris!
I have tested it and it works fine now.

**Comment by tyt2y3** [comment]
Thank you. Note to self: we'd need to add more test cases.
