### ISSUE TITLE
Mock test crushed with MySql on examples

### ISSUE THREAD

**Issue by makorne** [SeaQL/sea-orm#1801]
## Steps to Reproduce
1. clone https://github.com/SeaQL/sea-orm/tree/master/examples/tonic_example
2. cd service
3. change in  tests/prepare.rs         from Postgres to MySql
```
 pub fn prepare_mock_db() -> DatabaseConnection {
    MockDatabase::new(DatabaseBackend::MySql)  << HERE
``` 
4. in Cargo.rs  [dependencies.sea-orm]      remove   '#'    before   "sqlx-mysql",
5. cargo test --features mock

### Expected Behavior

```
running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
(this result with Postgres) 
```

### Actual Behavior

```
running 1 test
test main ... FAILED

failures:

---- main stdout ----
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Exec(Internal("`exec_results` buffer is empty"))', service/tests/mock.rs:69:57
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

failures:
    main

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

error: test failed, to rerun pass `--test mock`

```

### Reproduces How Often

Always

### Workarounds

None

## Versions
fedora 6.3.12-100.fc37.x86_64Fedora 38
cargo 1.71.0 (cfd3bbd8f 2023-06-08)
MySql 8
```
cargo tree | grep sea-
│   ├── sea-orm v0.12.1
│   │   ├── sea-orm-macros v0.12.1 (proc-macro)
│   │   │   ├── sea-bae v0.2.0 (proc-macro)
│   │   ├── sea-query v0.30.0
│   │   ├── sea-query-binder v0.5.0
│   │   │   ├── sea-query v0.30.0 (*)
└── sea-orm v0.12.1 (*)
```

**Comment by tyt2y3** [comment]
Mock test is database specific. I think it was originally written for Postgres. It might take some effort to convert it to MySQL.
But we'd accept contribution if someone is willing to improve it.
