### ISSUE TITLE
`sea-orm-cli` entities generator panics when an item in EnumType consist entirely without any letters or numbers

### ISSUE THREAD

**Issue by Cinea4678** [SeaQL/sea-orm#1819]
## Description

When I use this enum type in MySQL:

```sql
ENUM('Question','QuestionsAdditional','Answer','Other','/')
```

The `sea-orm-cli` entities generator will panic because it cannot convert '/' into an enum item name in Rust. That's just fine, but what troubles me is the `sea-orm-cli` didn't give a clear explanation for this panic. It just shows this:

```
thread 'main' panicked at 'Ident is not allowed to be empty; use Option<Ident>', <HomePath>\.cargo\registry\src\mirrors.ustc.edu.cn-61ef6e0cd06fb9b8\proc-macro2-1.0.66\src\fallback.rs:752:9
```

this is not really a bug itself, but we could probably provide users with a clearer error message or do some extra handling to accommodate these values. And if you'd be willing to first introduce a friendly error message as a transitional step before proposing other better approaches later, I'd be happy to provide a pull request for that.

Code related are mainly in this file:`sea-orm-codegen/src/entity/active_enum.rs:23`

## Steps to Reproduce

1. Setup a MySQL server, and run this:
 ```sql
CREATE TABLE `test` (
  `enum_column` enum('A','B','/') NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
 ```
2. Try to use `sea-orm-cli` to generate entity

### Expected Behavior

A friendly panic message is given, maybe saying 'We currently do not support enum items consisting entirely without any letters or numbers.', or just process this situation fine.

### Actual Behavior

A confusing error message unrelated to the specific cause was given.

### Reproduces How Often

Always 

### Workarounds

this is fine :)
 ```sql
CREATE TABLE `test` (
  `enum_column` enum('A','B','/') NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
 ```

## Versions

![image](https://github.com/SeaQL/sea-orm/assets/45115933/2252ace2-6a08-49d7-a353-43d7c061705a)

**Comment by Cinea4678** [comment]
What's more, I changed the source code of `sea-orm-codegen` to solve my problem, and it works fine. If you think this is ok, I can run the test and make a pull request.

`sea-orm-codegen/src/entity/active_enum.rs`
```rs
impl ActiveEnum {
    pub fn impl_active_enum(&self, with_serde: &WithSerde, with_copy_enums: bool) -> TokenStream {
        let enum_name = &self.enum_name.to_string();
        let enum_iden = format_ident!("{}", enum_name.to_upper_camel_case());
        let values: Vec<String> = self.values.iter().map(|v| v.to_string()).collect();
        let variants = values.iter().map(|v| v.trim()).map(|v| {
            if v.chars().next().map(char::is_numeric).unwrap_or(false) {
                format_ident!("_{}", v)
            } else {
                let new_name = v.to_upper_camel_case();
                if new_name.is_empty() {
                    // We can't find numbers or letters in the variant name.
                    let mut utf_string = String::new();
                    for c in v.chars() {
                        utf_string.push('U');
                        utf_string.push_str(&format!("{:04X}", c as u32));
                    }
                    format_ident!("{}", utf_string)
                } else {
                    format_ident!("{}", new_name)
                }
            }
        });

        let extra_derive = with_serde.extra_derive();
        let copy_derive = if with_copy_enums {
            quote! { , Copy }
        } else {
            quote! {}
        };

        quote! {
            #[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum #copy_derive #extra_derive)]
            #[sea_orm(rs_type = "String", db_type = "Enum", enum_name = #enum_name)]
            pub enum #enum_iden {
                #(
                    #[sea_orm(string_value = #values)]
                    #variants,
                )*
            }
        }
    }
}
```

**Comment by tyt2y3** [comment]
For sure! A PR on better error messages and enum handling would be appreciated.
