### ISSUE TITLE
support add db column auto field :created_at,update_at？

### ISSUE THREAD

**Issue by baoyachi** [SeaQL/sea-orm#185]
```rust
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub gh_access_token: String,
    pub gh_login: String,
    pub name: Option<String>,
}

```

with db column
```sql
                                             Table "public.users"
       Column        |            Type             | Collation | Nullable |              Default
---------------------+-----------------------------+-----------+----------+-----------------------------------
 id                  | integer                     |           | not null | nextval('users_id_seq'::regclass)
 gh_access_token     | character varying           |           | not null |
 gh_login            | character varying           |           | not null |
 name                | character varying           |           |          |
 created_at          | timestamp without time zone |           |          |
 updated_at          | timestamp without time zone |           |          |
```

**Comment by Acidic9** [comment]
Can't this already be done by adding the two fields to your `Model`?
```rust
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}
```

**Comment by baoyachi** [comment]
> Can't this already be done by adding the two fields to your `Model`?
> 
> ```rust
> pub struct Model {
>     #[sea_orm(primary_key)]
>     pub id: i32,
>     pub created_at: DateTimeWithTimeZone,
>     pub updated_at: DateTimeWithTimeZone,
> }
> ```

with sea-orm auto generated,don not have to specify it manually every time you create it.

I expect it to be implicit, and if not, manually specify that the device is not required. E.g.


* auto generated field.(created_at, updated_at)
```rust
#[derive(Clone, Debug, PartialEq, DeriveEntityModel,AutoField)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub gh_access_token: String,
    pub gh_login: String,
    pub name: Option<String>,
}
```

**Comment by Acidic9** [comment]
It personally feels like a little over the top for something you can just write with two lines of code. Sometimes obscuring stuff like this makes it difficult to read code later.

Imagine someone new to SeaORM comes to a project's code base and doesn't know what AutoField is.. it'd be very easy to miss.

**Comment by tyt2y3** [comment]
Thank you for your suggesting indeed.
I agree with Ari, that seemed to be 'too much magic'.
Besides, I don't think it is actually possible with a derive macro.
You cannot modify existing code with a derive macro, only generating new code blocks.
