### ISSUE TITLE
Enumeration String no longer supports certain characters

### ISSUE THREAD

**Issue by byeblack** [SeaQL/sea-orm#1851]
## Description

Create an enumeration, an error `proc-macro derive panicked message: ""` occurs when inputting most non-English languages as its value.

## Steps to Reproduce

1. Add SeaORM version 0.12.0 or above to the project.
2. Use the command `sea-orm-cli generate entity -u sqlite://any.sqlite` to create any entity.
3. Add an enumeration to the created table and use a non-English language as its value.

### Expected Behavior

The enumeration should be able to handle all supported characters without any errors.

### Actual Behavior

An error occurs when most non-English languages are used as the enumeration value: `proc-macro derive panicked message: ""`.

### Reproduces How Often

The issue is consistently reproducible.

### Workarounds

No workaround has been identified yet.

## Reproducible Example

Please refer to this example link: [Reproducible Example](https://github.com/byeblack/enum_error_example)
```rust
#[derive(Clone, Debug, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "String(None)", enum_name = "status")]
pub enum Status {
    // #[sea_orm(string_value = "Open")]
    // #[sea_orm(string_value = "열려 있는")]

    // The following situations
    // proc-macro derive panicked message: `""` is not a valid identifier
    #[sea_orm(string_value = "打开")]
    // #[sea_orm(string_value = "開ける")]
    // #[sea_orm(string_value = "Нээлттэй")]
    // #[sea_orm(string_value = "Открыть")]
    // #[sea_orm(string_value = "يفتح")]
    Open,
    #[sea_orm(string_value = "Close")]
    Close,
}
```

## Versions

SeaORM version: 0.12.0 and above.

**Comment by tyt2y3** [comment]
I am not sure, but it seems the error originate from within the derive macro, may be related to upgrade to `syn2`?

**Comment by iam888** [comment]
SeaORM version `0.12.15`, 

```rust
proc-macro derive panicked
message: `""` is not a valid identifier
```

code:
```rust
//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.0

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "cate")]
pub enum Cate {
    #[sea_orm(string_value = "開ける")]
    開ける,
}

```

![image](https://github.com/SeaQL/sea-orm/assets/108159/90cef775-82b8-4662-b97d-fcc730fd55f6)

**Comment by ghsang** [comment]
@tyt2y3 Could you reopen this issue? It is still not working on 0.12.15

**Comment by tyt2y3** [comment]
can you open a PR to submit a failing test case? @ghsang

**Comment by byeblack** [comment]
I've updated the examples to 0.12.15 [Reproducible Example](https://github.com/byeblack/enum_error_example)
It still has the same problem.

> can you open a PR to submit a failing test case? @ghsang

**Comment by byeblack** [comment]
Hello, @tyt2y3. I'm pretty confident I've just found the source of the error in the master branch. It's occurring in sea-orm-macros\src\derives\active_enum.rs:
```rust
...
            let enum_variant_iden = format_ident!("{}Variant", ident);
            let enum_variants: Vec<syn::Ident> = str_variants
                .iter()
                .map(|v| {
                    let v_cleaned = camel_case_with_escaped_non_uax31(v); // It turns the string into empty

                    format_ident!("{}", v_cleaned) // Error occurs here
                })
                .collect();
...
```

I tried to work around it so that the following example could run smoothly with insertions, queries, and filtering queries... However, I'm not confident in my ability to fix it myself. I'd be immensely grateful if you could address it.
```rust
#[derive(Clone, Debug, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "status")]
pub enum Status {
    #[sea_orm(string_value = "Open")]
    Open,
    #[sea_orm(string_value = "열려_있는")]
    열려있는,
    #[sea_orm(string_value = "打开")]
    打开,
    #[sea_orm(string_value = "開ける")]
    開ける,
    #[sea_orm(string_value = "Нээлттэй")]
    Нээлттэй,
    #[sea_orm(string_value = "Открыть")]
    Открыть,
    #[sea_orm(string_value = "يفتح")]
    يفتح,
    #[sea_orm(string_value = "Close")]
    Close,
}
```

**Comment by ghsang** [comment]
@tyt2y3 I have opened a PR with a fix and a test case.

**Comment by nadzyah** [comment]
@tyt2y3 Hey! I just want to confirm from my side that this bug still exists. Could you please review the PR mentioned? It looks like it has been there for a year. Thanks!
