### ISSUE TITLE
with 'ON CONFLICT DO UPDATE ' support?

### ISSUE THREAD

**Issue by baoyachi** [SeaQL/sea-orm#187]
raw sql e.g:
```sql
INSERT INTO "users" ("id", "name") VALUES (123, "test") ON CONFLICT (id) WHERE id > 0 DO UPDATE SET "name" = excluded."name";
```

**Comment by baoyachi** [comment]
I'm try do it.

**Comment by billy1624** [comment]
Thanks for the help!!

**Comment by tyt2y3** [comment]
Thank you for the uptaking. Have been busy preparing 0.2, but I think first, we’d need to support this construct in SeaQuery.
________________________________

**Comment by baoyachi** [comment]
@billy1624 @tyt2y3  please add this issue assignees to me

**Comment by tyt2y3** [comment]
Oh. Seems like the facility is missing in SeaQuery

https://github.com/SeaQL/sea-query/blob/a4e12409bdf1f2ca9ba44659b8925f265980c149/src/query/insert.rs#L34-L39

And it's mostly a Postgres only thing

> `INSERT INTO "users" ("id", "name") VALUES (123, "test") ON CONFLICT (id) WHERE id > 0 DO UPDATE SET "name" = excluded."name"`

But what does the `WHERE id > 0` do in the example?

**Comment by frankhorv** [comment]
Hey @baoyachi , any update on this? Thx

**Comment by baoyachi** [comment]
Comming soon.

**Comment by SebastienGllmt** [comment]
Looks like the upstream sea-query feature was merged 3 days ago https://github.com/SeaQL/sea-query/pull/279

**Comment by billy1624** [comment]
Related PR:
- https://github.com/SeaQL/sea-orm/pull/791
