### ISSUE TITLE
ilike filter

### ISSUE THREAD

**Issue by dvtkrlbs** [SeaQL/sea-orm#1882]
## Motivation

ilike filters are used commonly to do basic case insensitive search.

## Proposed Solutions

add ilike filter behind a feature gate for supported databases to column expressions

## Current Workarounds

adding lower on both the term and the parameter #672

**Comment by IgnisDa** [comment]
This already exists: https://docs.rs/sea-query/latest/sea_query/extension/postgres/trait.PgExpr.html#method.ilike

**Comment by dvtkrlbs** [comment]
oh I am so sorry. I think my local version did not had the feature enabled.
