### ISSUE TITLE
`.query_one` with `Statement::from_sql_and_values` returns nothing

### ISSUE THREAD

**Issue by martinmckenna** [SeaQL/sea-orm#1883]
## Description

Execute a query and wrap it in a `match` like so:

```rust
let new_user: Option<QueryResult> = match app_state
    .lock()
    .unwrap()
    .connection
    .query_one(Statement::from_sql_and_values(
        DatabaseBackend::Postgres,
        r#"
        INSERT INTO "user" (username, password, email)
        VALUES ($1,$2,$3)
    "#,
        [
            username.clone().into(),
            hashed_password.into(),
            email.into(),
        ],
    ))
    .await
{
    Ok(value) => {
        println!("hello {:?}", value);
        value
    },
    Err(_) => None,
};
```

## Steps to Reproduce

1. Execute query with code above, check database and see that the record has been created but nothing is returned

<img width="285" alt="Screenshot 2023-09-27 at 4 22 09 PM" src="https://github.com/SeaQL/sea-orm/assets/7387001/3d7e9e9f-dfb3-4656-a20c-4c110b79c606">

but users are being created in my DB:

<img width="454" alt="Screenshot 2023-09-27 at 4 22 34 PM" src="https://github.com/SeaQL/sea-orm/assets/7387001/35f9c959-d8ca-46d0-95df-b91177c20f75">

### Expected Behavior

1. A `Some` value is actual returned

### Actual Behavior

1. Nothing is returned

## Versions

```
sea-orm = { version = "0.12", features = [ "sqlx-sqlite", "runtime-tokio-rustls", "macros" ] }
```

**Comment by martinmckenna** [comment]
or perhaps the actual issue is that I shouldn't be using `.query_one` with an `INSERT` statement? But from the docs, I genuinely can't tell how I would make an `INSERT` with raw SQL and get the result returned back to me all in the same method because `.execute` also returns nothing that can get me the data.

**Comment by IgnisDa** [comment]
Change the query to:

```sql
INSERT INTO "user" (username, password, email) VALUES ($1,$2,$3) returning id, username, password, email;
```
