### ISSUE TITLE
Support RETURNING for SQLite

### ISSUE THREAD

**Issue by bouk** [SeaQL/sea-orm#1885]
@billy1624 I'm not sure what the original problem was, but could RETURNING be supported for SQLite now?

## Motivation

I have a query that has an `ON CONFLICT` and I want to use `exec_with_returning`, however `last_insert_rowid` is not set for SQLite when there's a conflict, so there's no way to figure out which row was updated. My query looks like:

```rust
Model::insert().on_conflict(...).exec_with_returning(db)
```

This works fine on Postgres but not SQLite

## Proposed Solutions

Get RETURNING working for SQLite

## Current Workarounds

You can do an extra SELECT query instead of using ON CONFLICT

**Comment by tyt2y3** [comment]
I think the blocker is we needed a way to tell if the linked SQLite version supports RETURNING.

A less ideal solution would be to detect that on runtime, and adjust the logic accordingly. This would actually be a bigger change.
