### ISSUE TITLE
Make `offset` and `limit` parameter accept `Option`

### ISSUE THREAD

**Issue by gitmalong** [SeaQL/sea-orm#1896]
## Motivation
I want to pass over such variables
```
offset: Option<u64>,
limit: Option<u64>,
```

to the query builder 
```rust
.offset(offset)
.limit(limit)
```

to avoid splitting the query builder into multiple lines with if conditions.

**Comment by IgnisDa** [comment]
What version are you using. Both of them already take Options (https://docs.rs/sea-orm/latest/sea_orm/query/trait.QuerySelect.html#method.limit and https://docs.rs/sea-orm/latest/sea_orm/query/trait.QuerySelect.html#method.offset).

**Comment by gitmalong** [comment]
I stand corrected, this is already implemented as shown above. Sorry.
