### ISSUE TITLE
Documentation for `drop_type`

### ISSUE THREAD

**Issue by dreamerlzl** [SeaQL/sea-orm#1908]
The documentation about `drop_type` in this docs: 

https://www.sea-ql.org/SeaORM/docs/migration/writing-migration/

looks confusing and different from the test example [here](https://github.com/SeaQL/sea-orm/blob/900b4106bb4854f3105c3df342348c57498b9560/sea-orm-migration/tests/common/migration/m20220118_000004_create_tea_enum.rs#L36)

where `Type` should be from `sea_query::extension::postgres::Type` while the docs says its `sea_query::Type`

**Comment by tyt2y3** [comment]
Thank you for pointing this out!
