### ISSUE TITLE
CLI unable to connect to psql through proxy

### ISSUE THREAD

**Issue by Ben-Lichtman** [SeaQL/sea-orm#1917]
## Description

I am unable to connect to my psql database through the fly.io proxy. Instead it just times out

## Steps to Reproduce

1. run the fly.io proxy which proxies to a db hosted by fly-io (ie `fly proxy 5432 -a <app>-db`)
2. `export DATABASE_URL=postgres://<app>:<redacted>@localhost:5432/<app>?sslmode=disable`
3. `sea-orm-cli generate entity -o src/entities`

### Expected Behavior

the CLI should be able to connect to the db and generate entities

### Actual Behavior

Timeout
```
❯ RUST_LOG=trace sea-orm-cli generate entity -o src/entities -v
Connecting to Postgres ...
pool timed out while waiting for an open connection
```

### Reproduces How Often

always

### Workarounds

unable to work around

## Reproducible Example

N/A

## Versions

```
❯ cargo tree | grep sea-
├── sea-orm v0.12.3
│   ├── sea-orm-macros v0.12.3 (proc-macro)
│   │   ├── sea-bae v0.2.0 (proc-macro)
│   ├── sea-query v0.30.2
│   ├── sea-query-binder v0.5.0
│   │   ├── sea-query v0.30.2 (*)
```

**Comment by tyt2y3** [comment]
I am sorry, but we do not support proprietary database providers.
The best you can do is to open a support ticket with them, and see if they'd care to talk with us to sort this out.

**Comment by Ben-Lichtman** [comment]
This isn’t “supporting a proprietary provider” this is just vanilla Postgres behind a local proxy though.

**Comment by Ben-Lichtman** [comment]
Some other info I've uncovered - this only breaks with `@localhost` not `@127.0.0.1`, and only with the `async-std` feature turned on. With tokio `localhost` works fine

**Comment by Ben-Lichtman** [comment]
For now I've used 127.0.0.1 as a workaround

**Comment by tyt2y3** [comment]
That's interesting finding, thanks. But if the proxy or the backend is not open source in a way I can build it on my own machine, it is proprietary. I am sorry, but I don't think we'd be devoting resources to support proprietary technologies.

**Comment by lucasmerlin** [comment]
I've switched to rancher desktop from docker desktop recently and since I also got the timeout error from sea-orm-cli generate entity. It also only happens with sea-orm-cli, sqlx cli works as expected. Fortunately I just tried using 127.0.0.1 and it also fixes it for me. 

So I think this must be the same issue. 

So, to reproduce you could 
1. Install rancher desktop
2. Start postgres with this docker-compose.yml:
```yml
services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - 5432:5432
```
```
docker compose up -d
```
3. have a .env file with:
```env
DATABASE_URL=postgres://postgres:mysecretpassword@localhost:5432/postgres
```
4. Try running sea-orm-cli generate entity

**Comment by tyt2y3** [comment]
Does this only happens on Windows?

**Comment by Ben-Lichtman** [comment]
> Does this only happen on Windows?

I experienced the issue on linux

**Comment by lucasmerlin** [comment]
For me it happened on MacOS

**Comment by tyt2y3** [comment]
Thanks for the info. I should be able to reproduce it then.

**Comment by Ben-Lichtman** [comment]
Any chance you could please reopen this issue until it is solved, just so it can be tracked? Thanks

**Comment by tyt2y3** [comment]
I can't readily reproduce the problem, so need more information for diagnosis.

**Comment by Ben-Lichtman** [comment]
Did the method from Lucas not repro?

**Comment by tyt2y3** [comment]
I mean, there could be many factors at play, Docker, VPN, route table config, firewall.

**Comment by xiro-codes** [comment]
Still happens with version 0.12.10

**Comment by Toruitas** [comment]
I had the same problem using the Bitnami Postgres image `bitnami/postgresql:latest`, even accessing it directly without using the proxy.

Workaround was to temporarily switch to the vanilla `postgres:latest` image, run my normal migrations, and then run `sea-orm-cli generate entity -o entity/src`

**Comment by tyt2y3** [comment]
@Toruitas have you tried `127.0.0.1` as mentioned above?

**Comment by Toruitas** [comment]
I did, without success. Could be a quirk with the Bitnami image specifically.
