### ISSUE TITLE
Column name `type`

### ISSUE THREAD

**Issue by cemoktra** [SeaQL/sea-orm#194]
Hey,

when generating code column named `type` should be renamed to `r#type`. Maybe check other rust keywords.

**Comment by billy1624** [comment]
Related to #76

**Comment by tyt2y3** [comment]
Continuing from #82 

Annotations we need to add to `DeriveColumn`

```rust
#[derive(DeriveColumn)]
pub enum Column {
    #[sea_orm(column_name = "my_db_col")]
    Name,
}
```

And also `DeriveEntityModel`

```rust
#[derive(DeriveEntityModel)]
#[sea_orm(table_name = "cake")]
pub struct Model {
    #[sea_orm(column_type = "Text", column_name = "my_db_col", nullable)]
    pub name: Option<String> ,
}
```

**Comment by DanielHZhang** [comment]
Would it be possible to also include a rename macro such as `#[sea_orm(casing = "camelCase")]` for `DeriveColumn` or `DeriveEntityModel`?

I know it's been discussed previously that SeaORM wants to avoid relying too much on macro magic, but I think it's a common pain point that database column names are in `PascalCase` or `camelCase` and currently there's no convenient way to remap them without writing the expanded entity structure. 

The macro could look something like this:
```rust
#[derive(DeriveEntityModel)]
#[sea_orm(table_name = "Account", casing = "PascalCase")]
pub struct Model {
    #[sea_orm(column_name = "type", enum_name = "Type")]
    pub ty: String,
	pub first_name: String, // mapped to db column `FirstName`
	pub last_name: String, // mapped to db column `LastName`
}
```

**Comment by billy1624** [comment]
Hey @DanielHZhang, good suggestion. It's possible to add this feature.
