### ISSUE TITLE
Regression: SQLite fails to create create AUTO_INCREMENT big_integer

### ISSUE THREAD

**Issue by secana** [SeaQL/sea-orm#1973]
## Description

Upgrade from `sea-orm-migration = 0.11.3` to `sea-orm-migrations = 0.12.6` breaks SQLite table creation with `AUTOINCREMENT is only allowed on an INTEGER PRIMARY KEY`

## Steps to Reproduce

1. Create a simple SQLite table with `big_integer` as the index.

```rust
async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .create_table(
                Table::create()
                    .table(UserIden::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(UserIden::Id)
                            .big_integer() // <--- Works fine in sea-orm 0.11.3
                            .not_null()
                            .auto_increment()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(UserIden::Name)
                            .text()
                            .unique_key()
                            .not_null(),
                    )
                    .col(ColumnDef::new(UserIden::Pwd).text().not_null())
                    .col(ColumnDef::new(UserIden::Salt).text().not_null())
                    .col(ColumnDef::new(UserIden::IsAdmin).boolean().not_null())
                    .to_owned(),
            )
            .await
}
```
Everything works fine and the table is created correctly.

2. Upgrade sea-orm

Upgrade sea-orm / sea-orm-migrations to `0.12.6` and run the code above again. Now, the table creation breaks with `AUTOINCREMENT is only allowed on an INTEGER PRIMARY KEY`.

### Expected Behavior

SQLite table is created with a `big_integer` index.

### Actual Behavior

Table creation fails with `AUTOINCREMENT is only allowed on an INTEGER PRIMARY KEY`.

### Reproduces How Often

Always

### Workarounds

Instead of `big_integer`, `integer` can be used and the code works again. Unfortunatly that is not an option as the all database table are already created with `big_integer`, such that a migration to `integer` would break all of the production databases.

## Versions

Upgrade from `0.11.3` to `0.12.6`

**Comment by secana** [comment]
Remark: The code works fine for PostgreSQL, it only affects SQLite.

**Comment by tyt2y3** [comment]
Thank you for your report. Yes I am aware, and is tracked in https://github.com/SeaQL/sea-query/issues/689
The workaround is to change it to `integer()` for primary keys. I probably would fix it soon.

**Comment by secana** [comment]
Thanks for the feedback. I looked here for an existing issue and didn't find one. Haven't though of looking in the sea-query repo. As the issue is already tracked, I'll close this one as a duplicate.

**Comment by tyt2y3** [comment]
No worries!

**Comment by vrozhdestvenskyi** [comment]
Hey guys, any updates on this?
At `0.12.15`, the table is created correctly but the generated `struct Model` has the primary key field of type `i32` but not `i64`

**Comment by tyt2y3** [comment]
You can try `1.0-rc`

**Comment by 0-don** [comment]
the issue still exists `1.1.2`
