### ISSUE TITLE
Derive `Hash` on active enums

### ISSUE THREAD

**Issue by kije** [SeaQL/sea-orm#1977]
## Motivation

Active enums generated by the `sea-orm-cli generate entity` could be used as keys in hashmaps/hashsets, etc...

Thus it would be really useful if one could opt-in to having `Hash` automatically derived, like there is already an option for the `Copy` trait via the `--with-copy-enums` CLI option

## Proposed Solutions

Add an optional `--with-hash-enums` option to the CLI, which then will add `Hash` to the traits derived on the generated active enums.

## Current Workarounds

Customize generated files manually and repeat that customization after each generate.

**Comment by anshap1719** [comment]
@tyt2y3 I think it would make more sense to have an equivalent of `--model-extra-derives` for ActiveEnums. Do you agree? I can create a PR for that.

**Comment by tyt2y3** [comment]
Thank you @anshap1719 for the nudge.

We added `--enum-extra-derives` and `--enum-extra-attributes` recently (https://github.com/SeaQL/sea-orm/releases/tag/0.12.5), I think this issue can now be closed.
