### ISSUE TITLE
0.12.8 won't build?

### ISSUE THREAD

**Issue by szinn** [SeaQL/sea-orm#1996]
## Description

Upgraded Cargo.toml from 0.12.7 to 0.12.8 and rebuilt. Getting compile errors in sea-orm...

## Steps to Reproduce

1. Build against 0.12.7
2. Change Cargo.toml to 0.12.8 and rebuild
3. See the error

### Expected Behavior

Should build fine.

### Actual Behavior

error[E0308]: mismatched types
   --> /Users/scotte/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sea-orm-0.12.8/src/database/statement.rs:80:45
    |
80  |             DbBackend::MySql => $stmt.build(MysqlQueryBuilder),
    |                                       ----- ^^^^^^^^^^^^^^^^^ expected `&DatabaseBackend`, found `MysqlQueryBuilder`
    |                                       |
    |                                       arguments to this method are incorrect
...
111 | build_query_stmt!(sea_query::WithQuery);
    | --------------------------------------- in this macro invocation
    |
note: method defined here
   --> /Users/scotte/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sea-orm-0.12.8/src/database/statement.rs:21:8
    |
21  |     fn build(&self, db_backend: &DbBackend) -> Statement;
    |        ^^^^^
    = note: this error originates in the macro `build_any_stmt` which comes from the expansion of the macro `build_query_stmt` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0308]: mismatched types
   --> /Users/scotte/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sea-orm-0.12.8/src/database/statement.rs:81:48
    |
81  |             DbBackend::Postgres => $stmt.build(PostgresQueryBuilder),
    |                                          ----- ^^^^^^^^^^^^^^^^^^^^ expected `&DatabaseBackend`, found `PostgresQueryBuilder`
    |                                          |
    |                                          arguments to this method are incorrect
...
111 | build_query_stmt!(sea_query::WithQuery);
    | --------------------------------------- in this macro invocation
    |
note: method defined here
   --> /Users/scotte/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sea-orm-0.12.8/src/database/statement.rs:21:8
    |
21  |     fn build(&self, db_backend: &DbBackend) -> Statement;
    |        ^^^^^
    = note: this error originates in the macro `build_any_stmt` which comes from the expansion of the macro `build_query_stmt` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0308]: mismatched types
   --> /Users/scotte/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sea-orm-0.12.8/src/database/statement.rs:82:46
    |
82  |             DbBackend::Sqlite => $stmt.build(SqliteQueryBuilder),
    |                                        ----- ^^^^^^^^^^^^^^^^^^ expected `&DatabaseBackend`, found `SqliteQueryBuilder`
    |                                        |
    |                                        arguments to this method are incorrect
...
111 | build_query_stmt!(sea_query::WithQuery);
    | --------------------------------------- in this macro invocation
    |
note: method defined here
   --> /Users/scotte/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sea-orm-0.12.8/src/database/statement.rs:21:8
    |
21  |     fn build(&self, db_backend: &DbBackend) -> Statement;
    |        ^^^^^
    = note: this error originates in the macro `build_any_stmt` which comes from the expansion of the macro `build_query_stmt` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0308]: mismatched types
   --> /Users/scotte/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sea-orm-0.12.8/src/database/statement.rs:101:66
    |
101 |                 Statement::from_string_values_tuple(*db_backend, stmt)
    |                 -----------------------------------              ^^^^ expected `(_, Values)`, found `Statement`
    |                 |
    |                 arguments to this function are incorrect
...
111 | build_query_stmt!(sea_query::WithQuery);
    | --------------------------------------- in this macro invocation
    |
    = note: expected tuple `(_, sea_query::Values)`
              found struct `statement::Statement`
note: associated function defined here
   --> /Users/scotte/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sea-orm-0.12.8/src/database/statement.rs:47:19
    |
47  |     pub(crate) fn from_string_values_tuple<T>(db_backend: DbBackend, stmt: (T, Values)) -> Statement
    |                   ^^^^^^^^^^^^^^^^^^^^^^^^                           -----------------
    = note: this error originates in the macro `build_query_stmt` (in Nightly builds, run with -Z macro-backtrace for more info)

### Reproduces How Often

Always

### Workarounds

None

## Versions

├── sea-orm v0.12.8
│   ├── sea-orm-macros v0.12.6 (proc-macro)
│   │   ├── sea-bae v0.2.0 (proc-macro)
│   ├── sea-query v0.30.2
│   │   ├── sea-query-derive v0.4.0 (proc-macro)
│   ├── sea-query-binder v0.5.0
│   │   ├── sea-query v0.30.2 (*)
├── sea-orm-migration v0.12.3
│   ├── sea-orm v0.12.8 (*)
│   ├── sea-orm-cli v0.12.3
│   │   ├── sea-schema v0.14.1
│   │   │   ├── sea-query v0.30.2 (*)
│   │   │   └── sea-schema-derive v0.2.0 (proc-macro)
│   ├── sea-schema v0.14.1 (*)
├── sea-orm v0.12.8 (*)
├── sea-orm-migration v0.12.3 (*)

**Comment by szinn** [comment]
Updated to 0.12.9 and the build went through. I suspect you are correct in that sea-query wasn't being updated automatically (I don't reference it in my Cargo.toml)

**Comment by tyt2y3** [comment]
Yes, thanks for reporting back. Depedency management is tricky sometimes haha.
