### ISSUE TITLE
Runtime error when saving entry using unsupported Model Column Type

### ISSUE THREAD

**Issue by ziimakc** [SeaQL/sea-orm#2007]
## Description
When using following model for postgresql database with [unsupported Model Column Type](https://www.sea-ql.org/SeaORM/docs/generate-entity/entity-structure/#column-type) `u32` and trying to insert(or any other operation) I get runtime error.

```
#[sea_orm(table_name = "xxx")]
pub struct Model {
    pub broken: u32,
}
```

It's error prone and not convenient to always manually check compatibility using provided on website table.

## Steps to Reproduce

1. Create instance of model
2. Insert in postgresql database

### Expected Behavior

Compile time error.

### Actual Behavior

Runtime error.

### Reproduces How Often

Always.

### Workarounds

When creating database model ensure that you don't use [unsupported Column Type](https://www.sea-ql.org/SeaORM/docs/generate-entity/entity-structure/#column-type).

```
#[sea_orm(table_name = "xxx")]
pub struct Model {
    pub broken: i32,
}
```

## Versions

0.12.9

**Comment by tyt2y3** [comment]
Thanks for the writing

**Comment by tyt2y3** [comment]
Thanks for the suggestion. But the Entity definition is not tightly coupled to the database backend.
