### ISSUE TITLE
Migrator does not exist

### ISSUE THREAD

**Issue by DenuxPlays** [SeaQL/sea-orm#2017]
I read trough your documentation on how to run migrations (https://www.sea-ql.org/SeaORM/docs/migration/running-migration/) and there it states: ` You can perform migration on application startup with Migrator, which implements the MigratorTrait`.
But I could not found any migrator and doc.rs confirms this:
![image](https://github.com/SeaQL/sea-orm/assets/83671398/e0526ca8-076d-423a-a8f8-2c30cde65261)

**Comment by tyt2y3** [comment]
It's here https://docs.rs/sea-orm-migration/latest/sea_orm_migration/migrator/trait.MigratorTrait.html

**Comment by DenuxPlays** [comment]
> It's here https://docs.rs/sea-orm-migration/latest/sea_orm_migration/migrator/trait.MigratorTrait.html

Yeah the trait but not the `Migrator`, but no implementation for it.

**Comment by tyt2y3** [comment]
You can look into one of the examples
