### ISSUE TITLE
Add SeaORM to the Diesel benchmark

### ISSUE THREAD

**Issue by weiznich** [SeaQL/sea-orm#204]
I would like to invent you to add sea-orm (and maybe also sea-ql) to the relational database connection crates benchmark suite located inside of the diesel repository. This would give potential users a good overview over the current state + you would also have a comparison with other crates for free.
Additionally to address your [worries from reddit](https://old.reddit.com/r/rust/comments/pvwoh4/introducing_seaorm_an_async_dynamic_orm_for_rust/hedhkop/) about those benchmarks not reflecting the strength of the async implementation side: We are more than happy to extend that benchmark suite so that these strengths could be shown in a better way. What sort of benchmark would you expect to show that? Maybe you would provide an initial implementation of an sea-orm based solution for such an use case?

**Comment by tyt2y3** [comment]
> The first thing I would likely look into in your position is where exactly the overhead of compared to Sqlx is coming from. Is this some unfortunate implementation detail that can be fixed later on quite easily or is it something more fundamental that may require redesigning certain parts of your crate.

I think a part of it is unavoidable: the dynamic query building stage. But then, there should be a lot of room to improve, like using smallvec, and refactor internally to reduce memory reallocation etc.

> My problem with such real world benchmarks is that they include to many variables to really say something about actual components of the benchmark system.

Okay, sorry for not made myself clear. We can have an actix web server, connecting to a database, doing some CRUD operations. The only variable will be the database driver, and then we will be able to tell whether a top-to-bottom async implementation actually makes a difference in terms of concurrency.

The comparison with node.js is a different game: we aim to compete with the node.js + expressjs + TypeORM (or any ORM) stack, with an entire Rust stack. I think we can draw more developers into the Rust ecosystem, if we can prove ourselves to be more performant while being comparatively productive.

> If you feel that some of the assumptions described in the benchmarks Readme is putting a disadvantage on a certain implementation, again please point that out and we will see how we can improve the "rules" and the implementation so that the benchmarks become more fair.

Yes. I have looked through the benchmark, and my only suggestion to improvement would be to have a slightly more complex schema and queries. I will definitely take some time to think about it! But right now our priority is to 'make it work and ship it'.

I'd like to keep this issue open, so a person who cares would be motivated to contribute something.
