### ISSUE TITLE
The DeriveIden macro

### ISSUE THREAD

**Issue by hut8** [SeaQL/sea-orm#2083]
## Description

I'm on the fence about whether to report this as a bug (I feel that it is a design flaw), but it did get me hung up for a few hours trying to trace what's going on with sea-orm's macros.

When I'm trying to define a PostgreSQL type, _which is not a table_, and I'm using the `sea_orm::DeriveIden` macro, then I must specify `Table` as the first variant of the enum to which `DeriveIden` is applied. This confuses me, although I see now in the code that `Table` is treated specially: https://docs.rs/sea-orm-macros/0.12.10/src/sea_orm_macros/derives/derive_iden.rs.html#52

Straight from the documentation here: https://www.sea-ql.org/SeaORM/docs/migration/writing-migration/#seaquery

```
use sea_orm::{EnumIter, Iterable};

#[derive(Iden, EnumIter)]
pub enum Category {
    Table,
    #[iden = "Feed"]
    Feed,
    #[iden = "Story"]
    Story,
}

manager
    .create_type(
        Type::create()
            .as_enum(Category::Table)
            .values([Category::Feed, Category::Story])
            // Or, write it like below.
            // Keep in mind that for it to work,
            // 1. you need to derive `EnumIter`,
            // 2. import `Iterable` into scope
            // 3. and make sure `Category::Table` is the first variant
            .values(Category::iter().skip(1))
            .to_owned(),
    )
    .await?;
```

So, the fact that this says `make sure Category::Table is the first variant`, but is nested under `Or, write it like below`, fails to really show that `Table` is treated specially, and instead of generating `table`, it will generate the snake-cased form of the enum's identifier. Could we maybe add another special case for `Iden` or another value being the first variant?

This blog post (which is not mine) is something that I just found while Googling and is only a few days old: https://cprimozic.net/notes/posts/trying-out-sea-orm/ -- it documents the same sort of struggle to figure out how to define a custom PostgreSQL enum type and reference it within the same migration.

## Steps to Reproduce

Copy and paste code exactly as above into a migration, except replace the first enum variant with `Category::Enum` or `Category::Ident` or something of the sort.

### Expected Behavior

I would expect that when defining a new type in Postgres, I could perhaps call the first variant `Type`, `Enum`, `Iden` or `Identifier` and have it treated the same as `Table` being the first variant (that is, it will generate the name of the enum in `snake_case`).

### Actual Behavior

Only `Table` is treated specially; I have to write `Table` to define something that isn't a Table, or just repeat the name of the enum like `Category::Category` which is clunky.

### Reproduces How Often

Always.

### Workarounds

I just have to use the special identifier `Table` as the first variant when defining a database enum, or repeat the name of the enum as the first variant.

## Reproducible Example

See above

## Versions

PostgreSQL (only), sea-orm 0.12.10

**Comment by tyt2y3** [comment]
I got you. The DeriveIden macro comes from SeaQuery's Iden macro, so it has to match the behaviour for backwards compatibility reasons.

I think 1) we can deprecate and remove it in all examples and use Alias::new instead or 2) design a new macro for a specific purpose or 3) use unit struct instead i.e DeriveIden on struct Something; which has no special treatment 

Can you share the pieces of code you end up with, so we can brainstorm how to make it more concise?

**Comment by tyt2y3** [comment]
Thank you for the feedback. The blog post https://cprimozic.net/notes/posts/trying-out-sea-orm/ is definitely insightful, and we will be able to improve on a few of the problems.

I have addressed some of the confusion by editing the doc https://www.sea-ql.org/SeaORM/docs/generate-entity/enumeration/#native-database-enum and https://www.sea-ql.org/SeaORM/docs/migration/writing-migration/#seaquery

If you have more suggestions, just let us know!

**Comment by JMartinCollins** [comment]
Referencing [this commit](https://github.com/SeaQL/sea-orm/commit/390ca0f0f6b048f53ab7758297f089754f726e33)

Another major issue with this approach is that you're unable to use this enum to add entries to the database. Simply put, if the enum is declared using `DeriveIden` alone, then one can't `use` this enum to populate the database in a later migration, unless you `impl` something simliar to [as_enum](https://docs.rs/sea-orm/latest/src/sea_orm/entity/active_enum.rs.html#137-139) as `impl Into<SimpleExpr> for Tea` method yourself. That being the case it seems better that the primary example for adding a Postgres enum should use `DeriveActiveEnum`, unless there's some issue that I'm not aware of with that approach. 

Here are the two approaches:
```rs
// InsertStatement
      .values_panic([
          // ...some other column values
          // ⚠ This needs to be implemented if only using DeriveIden
          Tea::BreakfastTea.into(),
          // This is provided by DeriveActiveEnum
          Tea::BreakfastTea.as_enum(),
      ])
```

**Comment by tyt2y3** [comment]
Not sure if that's been mentioned, but using the [create_enum_from_active_enum](https://docs.rs/sea-orm/latest/sea_orm/schema/struct.Schema.html#method.create_enum_from_active_enum) helper function is probably the easiest way.

**Comment by JMartinCollins** [comment]
> Not sure if that's been mentioned, but using the [create_enum_from_active_enum](https://docs.rs/sea-orm/latest/sea_orm/schema/struct.Schema.html#method.create_enum_from_active_enum) helper function is probably the easiest way.

Just a suggestion: If that's the recommended way, maybe it would be best to have that be the first example [here](https://www.sea-ql.org/SeaORM/docs/next/generate-entity/enumeration/#postgres) and also have it link to an example. Examples maybe should also include examples of using the enum to populate data in a migration using `Tea::BreakfastTea.as_enum()`.

**Comment by tyt2y3** [comment]
Can you open a PR on https://github.com/SeaQL/seaql.github.io/ ?
