### ISSUE TITLE
SelectThree up to SelectNine

### ISSUE THREAD

**Issue by tyt2y3** [SeaQL/sea-orm#21]
Right now we have a tuple based selector for select one and two. Need to think about how to generalise and support up to arity 9 perhaps?

src/query/combine.rs

**Comment by guymave** [comment]
why did you close this? :(

**Comment by tyt2y3** [comment]
there's a newer discussion thread on this. I couldn't find atm.
But SelectThree has already landed, so potentially we can macro our way to SelectNine

**Comment by billy1624** [comment]
- https://github.com/SeaQL/sea-orm/discussions/2525
- https://github.com/SeaQL/sea-orm/pull/2518
