### ISSUE TITLE
doc: code blocks looks weird in light mode

### ISSUE THREAD

**Issue by ssiyad** [SeaQL/sea-orm#2116]
Code blocks in docs looks weird/unreadable in light mode. Looks okay in dark. Example - https://www.sea-ql.org/SeaORM/docs/relation/one-to-one/#defining-the-relation

<img src='https://github.com/SeaQL/sea-orm/assets/28098330/9c86eec7-8886-4119-9241-681a4890cf8f' width='500px' />
<img src='https://github.com/SeaQL/sea-orm/assets/28098330/6821d708-14f0-4a35-a28c-afb9793e1880' width='500px' />

**Comment by tyt2y3** [comment]
oh it really is. I don't know how to fix it though

**Comment by ssiyad** [comment]
Also, even in dark mode, the contrast is too low on highlighted lines.

<img width="496" alt="image" src="https://github.com/SeaQL/sea-orm/assets/28098330/d3b3e264-a52b-46e2-8152-40461d7734e7">

**Comment by tyt2y3** [comment]
Ah right, may be we should override the highlight color in CSS.

**Comment by billy1624** [comment]
Hey @ssiyad, thanks for the prompt! I just fixed the theme, https://github.com/SeaQL/seaql.github.io/commit/93501d5ce09de2c62ea07517cb7065b94cc59d6a. Please check again!

- <img width="1904" alt="image" src="https://github.com/SeaQL/sea-orm/assets/30400950/1fb3fa85-3668-4b24-aa33-7b727652e246">
- <img width="1904" alt="image" src="https://github.com/SeaQL/sea-orm/assets/30400950/8b7b7197-a25e-460f-b411-c697d4935d3a">

**Comment by billy1624** [comment]
Fixed on https://github.com/SeaQL/seaql.github.io/commit/93501d5ce09de2c62ea07517cb7065b94cc59d6a

**Comment by ssiyad** [comment]
@billy1624 It looks so much better now. Thanks!

**Comment by tyt2y3** [comment]
Many thanks!
