### ISSUE TITLE
Add `#[automatically_derived]` to derive macros

### ISSUE THREAD

**Issue by Acidic9** [SeaQL/sea-orm#216]
Each implementation generated by macros should be tagged with the attribute `#[automatically_derived]`.
Many other libraries including serde and sqlx do this. I'm not sure what tools currently use this, but it would be a minor improvement, but definitely not important at this stage.

https://doc.rust-lang.org/reference/attributes/derive.html#the-automatically_derived-attribute

As an example:
```rust
// sea-orm-macros/src/derives/active_model.rs
quote!(
    #[automatically_derived]
    impl sea_orm::ActiveModelTrait for ActiveModel {
        ...
    }
)
```

**Comment by tyt2y3** [comment]
Sure, I agree. A PR will be appreciated!
