### ISSUE TITLE
sea-orm-cli: Entity generation fails if column name is a reserved keyword

### ISSUE THREAD

**Issue by BeneCollyridam** [SeaQL/sea-orm#217]
Hello,

I am very excited by this project, and I think the work you're doing is amazing.

I encountered a problem, when I was trying to use `sea-orm-cli` to generate entities. I got an error as one of the columns in my database was named `type` which is a reserved keyword. `rustc` suggest fixing it by writing `r#type` instead in the generated code.

Keep up the great work!

**Comment by tyt2y3** [comment]
Hi there, welcome!

It has also been discussed in #82 .

Basically the preliminary work #209 has already been merged, and will be released soon (like this week).

But it'd take some time for us to fix the codegen indeed.

Thank you for your support!

**Comment by tyt2y3** [comment]
[0.2.4](https://github.com/SeaQL/sea-orm/releases/tag/0.2.4)

**Comment by tyt2y3** [comment]
Example included in https://www.sea-ql.org/SeaORM/blog#rename-column-name--column-enum-variant
