### ISSUE TITLE
Expose `order_by_with_nulls` in `QueryOrder` trait

### ISSUE THREAD

**Issue by IgnisDa** [SeaQL/sea-orm#2227]
I would like to `order by  <col> nulls last` in my query but am unable to since that method is not exposed.

**Comment by IgnisDa** [comment]
@tyt2y3 Would you be willing to accept a PR for this?

**Comment by tyt2y3** [comment]
sure!

**Comment by IgnisDa** [comment]
@tyt2y3 Could you take a look at the PR I made?
