### ISSUE TITLE
sea-orm-cli: does not recognize SQL Date on Postgres

### ISSUE THREAD

**Issue by shi-rudo** [SeaQL/sea-orm#225]
```
sea-orm = { 
  version = "^0.2.4", 
  features = ["sqlx-postgres", "macros", "runtime-async-std-native-tls", ], 
  default-features = false 
}
```
sea-orm-cli: 0.2.4

---

Creating a Postgres tables with: 
Postgres sql: 
```sql
create table stores
(
	...
	opening_date date not null,
	...
);
```

Generating entities by **sea-orm-cli**
```console
sea-orm-cli generate entity
-u postgres://user:password@host:port/postgres
-o src/entity
```

results in:
```rust

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "stores")]
pub struct Model {
    ...
    pub opening_date: String,
    ...
}

```

executing:

```rust
let orm = entity::stores::ActiveModel {
	    ...
            opening_date: Set(input.open_date.to_owned()),
            ...
        };
```

🚨 leads to:
```console
 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `std::string::String`, found struct `NaiveDate`
```

As expected, manually replacing **String** with **Chrono:NaiveDate** fixes the error. But the CLI produces every time again String as type for SQL Date.

**Comment by billy1624** [comment]
Hey @shi-rudo, thanks for the feedback! Just found the faulty lines. I will create a PR fixing it ASAP.

https://github.com/SeaQL/sea-orm/blob/632290469b649d40b45760ff00f687a1467c5508/sea-orm-codegen/src/entity/column.rs#L30-L31

**Comment by billy1624** [comment]
Please change... for now

```rust
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "stores")]
pub struct Model {
    ...
    pub opening_date: Date, // Change `String` to `Date`
    ...
}
```

**Comment by shi-rudo** [comment]
thanks for the fast response!

By the way, the same thing happens with SQL Time `pub opening_time: String` should be `Time` resp. `NaiveTime` Just a note in case you didn't notice this type in the next PR.

**Comment by billy1624** [comment]
Yes, I will fix both `NaiveDate` & `NaiveTime` mappings. Thanks!!
