### ISSUE TITLE
support sqlx v0.8

### ISSUE THREAD

**Issue by gitmalong** [SeaQL/sea-orm#2310]
sea-orm uses sqlx 0.7. Please support sqlx v0.8

See https://github.com/launchbadge/sqlx/blob/main/CHANGELOG.md

**Comment by Expurple** [comment]
Maintainers already have [plans](https://www.sea-ql.org/blog/2024-08-04-sea-orm-1.0/#release-planning) for this and a PR: #2305.

Although treir plan basically involves making 1.1.0 a breaking release, which I don't approve. No one even read their blog post with the advice to pin 1.0.0. Compared to the amount of users SeaORM has
