### ISSUE TITLE
(Solved)Cyclic dependency issue with ahash crate - maybe worthwhile to document.

### ISSUE THREAD

**Issue by elbart** [SeaQL/sea-orm#235]
Dear Sea ORM creators / maintainers,

first of all, thanks a lot for all the effort you seem to spend on this nice peace of software. I was just skimming around to look for a ORM to try for a new project I am trying to build. While knowing diesel (no it's not async, so it's not really interesting to me anymore) and also trying rbatis, Sea ORM looks the most promising to be honest. I have been working with sqlx before but wished for a more high level layer for regular crud operations.

I have been trying to pull in Sea ORM in an quasi active project with openidconnect / oauth dependency, however failed to pull in Sea ORM. I got a cyclic dependency error:

```bash
> cargo build
    Updating crates.io index
error: cyclic package dependency: package `ahash v0.7.4` depends on itself. Cycle:
package `ahash v0.7.4`
    ... which is depended on by `hashbrown v0.11.2`
    ... which is depended on by `indexmap v1.7.0`
    ... which is depended on by `serde_json v1.0.67`
    ... which is depended on by `wasm-bindgen v0.2.77`
    ... which is depended on by `js-sys v0.3.54`
    ... which is depended on by `getrandom v0.2.3`
    ... which is depended on by `ahash v0.7.4
```

I was a bit puzzled and did a `cargo clean` but this did not help, too. I searched for such an Issue and found an unanswered SO post: https://stackoverflow.com/questions/68399961/how-do-i-resolve-a-cyclic-dependency-in-cargo in the same question range. 

I then wanted to do a minimal example for reproduction in a clean project ... I failed! I was unabled to reproduce, which left me puzzled. The only thing for me, left to do was to do `rm Cargo.lock && cargo clean && cargo build` and this suddenly worked (*remark: i did not change any version specs in Cargo.toml*, but I never pinned to patch versions, but usually minors). Seems like I was locked to an older version somewhere - the changes in Cargo.lock were too many to track down where the issue could have been, however it resolved the issue for me. Instead of deleting Cargo.toml I just learned, that i should have better used `cargo update` :).

Anyways, other people pulling Sea ORM in existing projects might stumble upon this issue and do not jump on the train. A simple 'cargo update' instruction for the above error somewhere in the documentation could help :)

Keep up the great work and feel free to close if too minor for you guys!

**Comment by baoyachi** [comment]
it's caused by this issue:[https://github.com/tkaitchuck/aHash/issues/95](https://github.com/tkaitchuck/aHash/issues/95).
Using indexmap = "~1.6.2" works as a workaround.

**Comment by elbart** [comment]
@baoyachi thanks for the quick reply! I never claimed that sea orm can solve the issue, sorry if that somehow sounded like that (which is why I put solved in the ticket title). I just wanted to point out that this happened to mem while adding sea orm to the project and never happend before with any other crate I added. Therefore i thought it might be good to document this here, too, just someone else stumbles upon this same issue. And if you guys want, you could add a short remark to your already great documentation. No must have, just came to my mind.
