### ISSUE TITLE
[sea-orm-cli] Better handling of relation generations

### ISSUE THREAD

**Issue by tyt2y3** [SeaQL/sea-orm#239]
It has been reported that the codegen can generate non-compilable code when dealing with relations.

As the first step, we can simply skip generating the relations if:

1) the related entity is self::Entity (https://github.com/SeaQL/sea-orm/discussions/231#discussioncomment-1449066)
2) there exist multiple relations to the same related Entity (#218)

Later, we can also try to generate Links inplace of those relations.

**Comment by AngelOnFira** [comment]
Hey, this doesn't look like too hard of an issue, can I take it? Also, is this repo participating in Hacktoberfest (or rather, would you be willing to add the `hacktoberfest-accepted` tag once I get to the PR stage?)

**Comment by AngelOnFira** [comment]
> @AngelOnFira do you want to assign this to yourself or you have other ideas?

Ya, if I can be assigned this it would be good :smile: I just got caught up in the other PR I was working on 😛

**Comment by billy1624** [comment]
Hey @AngelOnFira, any updates on this? :P

**Comment by AngelOnFira** [comment]
Thanks for checking in, I need this for a project I have coming up, but I've been super busy with other work. As soon as I do have time, I do plan on hopping on this issue since it's quite important to me, but if someone else has time to work on it right now, I'd be very grateful for that as well :(

**Comment by billy1624** [comment]
> Thanks for checking in, I need this for a project I have coming up, but I've been super busy with other work. As soon as I do have time, I do plan on hopping on this issue since it's quite important to me, but if someone else has time to work on it right now, I'd be very grateful for that as well 😄

Thanks!! @AngelOnFira. Take your time!

**Comment by billy1624** [comment]
Hey @AngelOnFira, I have just open a PR for this. You can check it if you have time :))
