### ISSUE TITLE
sea-orm-cli

### ISSUE THREAD

**Issue by tyt2y3** [SeaQL/sea-orm#24]
What should be command line interface?

First, we should read config from `.env`.

1. `migrate` command for schema migration
```sh
# to run all migrations
sea-orm-cli migrate
# to run one migration
sea-orm-cli migrate up
# to revert a migration
sea-orm-cli migrate down
```

2. `generate` command for code generation
```sh
# to generate entity files
sea-orm-cli generate entity
```

**Comment by tyt2y3** [comment]
To clarify, our expected behavior:

- for MySQL `--database-schema` is ignored
- for Postgres `--database-schema` is optional, defaults to public

Please make the changes to `sea-orm-cli`

**Comment by billy1624** [comment]
The new ignore hidden table behavior for `sea-orm-cli generate entity`:
- ignore table name starts with "_" (an underscore)
- add an option `--include-hidden-tables` to disable this behavior
