### ISSUE TITLE
0.4.x Docs

### ISSUE THREAD

**Issue by tyt2y3** [SeaQL/sea-orm#260]
## Advanced Relations
- [x] Entity related to itself
- [x] multiple relations to the same related Entity

## Issues / PRs
- [x] #273
- [x] #252 & #324
- [x] #290
- [x] #292
- [x] #297
- [x] #306 & #307
- [x] #309
- [x] #318

**Comment by billy1624** [comment]
I think we do have this. Perhaps we can reorganize it?

>  multiple relations to the same related Entity

https://www.sea-ql.org/SeaORM/docs/advanced-query/advanced-relations/#linked

**Comment by tyt2y3** [comment]
Yeah at least extract it to its own

**Comment by billy1624** [comment]
> Yeah at least extract it to its own

Maybe we can put it under "Relation"?
