### ISSUE TITLE
because when he updated a field he moved the row to the last one

### ISSUE THREAD

**Issue by efrain2007** [SeaQL/sea-orm#272]
![image](https://user-images.githubusercontent.com/65697999/138580850-3e46fe07-64ea-4473-a621-71050232beb2.png)

**Comment by efrain2007** [comment]
If I register 10 rows of a table and I update the item in row 5, what it does is update the row and remove it to the last row, that is, if before row 5 was in 5, now it is in 10 because that happens ?

**Comment by tyt2y3** [comment]
I think this behaviour has nothing to do with ORM.
It's just that database would return rows in pseudorandom order, if there isn't a primary key in place.
