### ISSUE TITLE
Distinct support?

### ISSUE THREAD

**Issue by edg-l** [SeaQL/sea-orm#275]
I saw sea-query supports it, but It doesn't seem like it's supported yet in sea-orm.

**Comment by ikrivosheev** [comment]
@edg-l we add support for some types of DISTINCT into sea-query!

**Comment by billy1624** [comment]
I'll open this issue for contributions. With support of DISTINCT in SeaQuery, for sure we could bring it to SeaORM :)

**Comment by kyoto7250** [comment]
Hi, I am interested in this issue.

I'd like to work on this issue, so could you tell me a little more about this issue?
