### ISSUE TITLE
Support for BYTEA Postgres primary keys

### ISSUE THREAD

**Issue by robot-head** [SeaQL/sea-orm#286]
Currently any column marked as a primary key needs to satisfy `TryFromU64`.

A BYTEA (`Vec<u8>`) does not satisfy this (and, I don't think ever could).

Would it be possible to add support for this type of primary key?  We use it a lot in our application

**Comment by tyt2y3** [comment]
`TryFromU64` can definitely return `Err` in that case. That's how `UUID` primary key is supported.
We can do something to support `Vec<u8>` explicitly, but it should be working already.

https://github.com/SeaQL/sea-orm/blob/57c255387f62884915311a7f3a8995c2c209b58e/tests/common/features/metadata.rs#L5-L15

**Comment by robot-head** [comment]
Seeing this 
![image](https://user-images.githubusercontent.com/877644/139797408-64cf6a3d-8c51-4c46-98c8-a05b56466380.png)

With this example model:

```
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "foobar")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub primary: Vec<u8>,
}
```

**Comment by billy1624** [comment]
The errors are expected. I will create a PR now to make it work! Stay tuned

**Comment by robot-head** [comment]
Thank you so much!

Loving this crate so far btw, refactoring our large codebase to make it *finally* unit testable.

Thanks for the quick help

**Comment by billy1624** [comment]
Thanks for the support! Do recommend `sea-orm` to your friends loll :P

**Comment by billy1624** [comment]
Hey @robot-head, please try #287.

Simply...

```toml
sea-orm = { version = "^0.3", git = "https://github.com/SeaQL/sea-orm.git", branch = "vec-u8-primary-key", ... }
```

P.S. For now, it works on Postgres but not MySQL and MariaDB

**Comment by tyt2y3** [comment]
> Loving this crate so far btw, refactoring our large codebase to make it _finally_ unit testable

Cool, we definitely would like to know a bit more about your scenario!

**Comment by tyt2y3** [comment]
[0.3.x](https://github.com/SeaQL/sea-orm/releases/tag/0.3.2)
