### ISSUE TITLE
Why insert, update, etc return a ActiveModel instead of Model?

### ISSUE THREAD

**Issue by edg-l** [SeaQL/sea-orm#289]
I find it curious, since you can easily go from a model to a activemodel, but not backwards (from what i've seen), and most of the time after a insert i want the Model which i can return from my api.

I've seen the impl of the insert model and it in fact does a query to find the inserted model and then it converts it to a activemodel, I think we should let the end user decide whether to convert it to a activemodel or not and just return a model.

**Comment by tyt2y3** [comment]
You have made a good point! I agree that the conversion could seem unnecessary.

For now, the returned object of 'update' is the input ActiveModel.

So may be it makes sense that the return type of 'model.insert()' is Self.

And they also trigger the ActiveModelBehavior

Do you have new thoughts on it?

**Comment by Vandell63** [comment]
+1 here. So finally we have to make a double `select` query to get back the last inserted user as Model finally right ?
