### ISSUE TITLE
Impl Clone on DatabaseConnection

### ISSUE THREAD

**Issue by robot-head** [SeaQL/sea-orm#293]
I saw in https://github.com/SeaQL/sea-orm/issues/152 that `DatabaseConnection` was not marked `Clone` if mocks are enabled, but I see now that the Mock connection variant is behind an `Arc`.

Is there any reason not to make `DatbaseConnection` `Clone`?  We've stuffed it into an `Arc` in our application code, but my code reviewers are questioning why the `Arc` is necessary.

**Comment by tyt2y3** [comment]
Yes he is right. Do not stuff an Arc in your app code.

Add a feature in your Cargo, and only enable Mock while in testing.

The reason behind that is Mock has a mock output buffer and a transaction log, where it will be hard to reason it's behaviour when being cloned.

**Comment by robot-head** [comment]
Thanks!  

I might send ya a PR on the testing docs to help others that come across this

**Comment by PoOnesNerfect** [comment]
It seems like [DatabaseConnection::MockDatabaseConnection](https://github.com/SeaQL/sea-orm/blob/master/src/database/db_connection.rs#L30) has inner mock connection struct in an `Arc`, making it cloneable.
It seems strange that all variants of this `DatabaseConnection` derives `Clone` including `Arc<MockDatabaseConnection>`, but the wrapper enum itself does not implement `Clone` when mock feature is enabled.
