### ISSUE TITLE
How can auto migrate table struct when application startup?

### ISSUE THREAD

**Issue by niuhuan** [SeaQL/sea-orm#332]
I used sea-orm and sqlite for desktop application save preferences.
I need auto modify columns and index when app upgrade (app startup).

Does sea-orm have this function ?

like this

```rust
Cake::auto_migrate(db).await?;
```

```rust
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "cake")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub content: String, // <--- add this line , table auto add column
}
```
auto migrate index 
```rust
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(index="idx_name_content")]
    pub name: String,
    #[sea_orm(index="idx_name_content")]
    pub content: String,
    #[sea_orm(unique="uk_uuid")]
    pub demo_uuid: String,
}
```

**Comment by billy1624** [comment]
Hey @niuhuan, welcome! We don't have migration feature at the moment but we're developing it.
If you looking for ways to setup database schema from fresh you could reference [this](https://www.sea-ql.org/SeaORM/docs/write-test/sqlite).

**Comment by billy1624** [comment]
> @billy1624 Thanks for reply. and expect sea-orm to be better.

Thanks for the support!

**Comment by helphi** [comment]
What's the release date?

**Comment by billy1624** [comment]
> What's the release date?

Hi @helphi, would probably be near the Christmas or early 2022.

**Comment by niuhuan** [comment]
It's all year, any weather. I will still come and have a look the issue every day. Is going well?

**Comment by billy1624** [comment]
I think I saw a comment here last night. @niuhuan

The migrator will be ready by Jan 2022 :P

**Comment by niuhuan** [comment]
That's great!!

**Comment by Madoshakalaka** [comment]
> > What's the release date?
> 
> Hi @helphi, would probably be near the Christmas or early 2022.

Looking forward to it! Thanks for the work!

**Comment by helphi** [comment]
It's now Feb 2022, is it released?

**Comment by billy1624** [comment]
Hey @helphi, it will comes with sea-orm 0.6.0, it's around the corner. We are brushing up the docs today

**Comment by niuhuan** [comment]
I upgrade sea-orm to 0.6.0. I saw a migration program, like a database version controller, this is good.

I'm making a light app, table is compatible with lower versions. 

I most desirable :  Auto add nonexistent columns and indexes, after run **Cake::auto_migrate(db).await?;** .

I think it would be better if I could support it.

**Comment by billy1624** [comment]
Hey @niuhuan, I think in terms of migration, we want things to be predictable. The auto migrate feature which create missing columns or indexes might not be desired. As it will perform operations under the hood.

You might want to set a baseline for the database schema then migrate it based on that.

**Comment by niuhuan** [comment]
> we want things to be predictable.

This is very important if it is the server side. 

But I used sea-orm on mobile app, It never downgrades. I look forward to supporting automatic migration in the future.

**Comment by niuhuan** [comment]
> Oh, you are using sea-orm on client side? Use it for local storage? SQLite, I assumed?

Yes, is client side. I'm using.sea-orm and sqlite.
Save user preferences, album, lesson, video. it are not many tables.

**Comment by billy1624** [comment]
Cool! I guess you can always run the follow code on startup to make sure clients' SQLite schemas are up to date?

```rust
/// Apply all pending migrations
Migrator::up(db, None).await?;
```

REF: https://www.sea-ql.org/SeaORM/docs/migration/running-migration#migrating-programmatically

**Comment by billy1624** [comment]
Please reopen this if you still have questions :)
