### ISSUE TITLE
Schema name is missing in the generated Model entity (Postgresql)

### ISSUE THREAD

**Issue by frankhorv** [SeaQL/sea-orm#334]
I'm running `sea-orm-cli` code generator on Postgresql and using the schema name CLI option, but the 
schema_name attribute is missing in the generated table entity:

```
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(schema_name = "valid_schema_name", table_name = "valid_table_name")]
pub struct Model {
}
```

**Comment by billy1624** [comment]
Hi @frankhorv, welcome! Oh, this is your first issue on GitHub loll

Yes, currently the schema name is not generated automatically. Thanks for the report!

**Comment by jmeischner** [comment]
+1

Thanks for creating this great library and cli 👍

**Comment by billy1624** [comment]
Hey @jmeischner, thanks for the love and support! :))
