### ISSUE TITLE
How to define rust type of TIMESTAMP?

### ISSUE THREAD

**Issue by billy1624** [SeaQL/sea-orm#344]
### Discussed in https://github.com/SeaQL/sea-orm/discussions/341

<div type='discussions-op-text'>

<sup>Originally posted by **lz1998** December  1, 2021</sup>
I have tried 4 types, never of them works. **`NaiveDateTime`, `i64`, `DateTime<Utc>` and `DateTime<FixedOffset>`**

I use MySQL 8. I create table by myself without `automigrate`, and I define rust struct by myself.

```SQL
    `created_at` TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
```

```rust
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "product")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub name: String,
    pub operator: String,
    pub status: i32,
    pub created_at: DateTime<FixedOffset>,
    pub updated_at: DateTime<FixedOffset>,
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
```

**`NaiveDateTime` and `i64`**
```bash
Err(Query("error occurred while decoding column \"created_at\": mismatched types; Rust type `core::option::Option<chrono::naive::datetime::NaiveDateTime>` (as SQL type `DATETIME`) is not compatible with SQL type `TIMESTAMP`"))
```

**`DateTime<Utc>` and `DateTime<FixedOffset>`**
```bash
error: proc-macro derive panicked
 --> src/database/product.rs:8:35
  |
8 | #[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
  |                                   ^^^^^^^^^^^^^^^^^
  |
  = help: message: `"DateTime<Utc>"` is not a valid identifier

```</div>

**Comment by tyt2y3** [comment]
We can use `sea_orm::prelude::DateTime`, which is actually `NaiveDateTime`.
Whether it is `DateTime<Local>` or `DateTime<Utc>` is dependent on system configuration.

**Comment by billy1624** [comment]
> We can use `sea_orm::prelude::DateTime`, which is actually `NaiveDateTime`.

Yes, it should. I discover that for MySQL, it's blocked by SQLx. See launchbadge/sqlx#1581

**Comment by tyt2y3** [comment]
I think the root cause is we have different opinions to the MySQL timestamp.
They usually are `DateTime<Utc>` but it really depends on the MySQL configuration.
To me, it seems like `NaiveDateTime` is an appropriate representation.

**Comment by tyt2y3** [comment]
I think the root cause is the slightly strange behavior MySQL timestamp.

> In short, “ MySQL converts TIMESTAMP values from the current time zone to UTC for storage, and back from UTC to the current time zone for retrieval. (This does not occur for other types such as DATETIME.)”

They usually are `DateTime<Utc>` but it really depends on the MySQL configuration.

To me, it seems like `NaiveDateTime` is an appropriate representation.

**Comment by tyt2y3** [comment]
My opinion is, `DateTime<Utc>` should have same size as `NaiveDateTime`, where `Utc` is only a marker instead of being a true byte of data where `offset = 0`.

**Comment by tyt2y3** [comment]
I think we should support `DateTime<Utc>` natively in SeaORM soon

**Comment by tyt2y3** [comment]
[0.4.2](https://github.com/SeaQL/sea-orm/releases/tag/0.4.2)
