### ISSUE TITLE
how to update dynamicly from json value

### ISSUE THREAD

**Issue by qyihua** [SeaQL/sea-orm#346]
Hello, 
Is there any way to support dynamic update from json value?
like update from user input , and only allow update special fields
if the input json field is null, need set None value for activemodel,
so it need get None value from column:

``` rust
struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub addr: Option<String>,
    pub other: Option<String>,
    ...
}
...
let allow_change_fields = vec![Column::Name, Column::Addr];

let mut actives = table::ActiveModel::new();
actives.set(Column::Id, 1.into());

// json is from user input, dynamic
let mut json = json!{addr: "new address"}; 

for col in allow_change_fileds{
   if let Some(json_val) =  json.get(col.to_string()) {
     let new_val = if json_val.is_null() {
       col.null_value() // Value::from(None::<i32>) or Value::from(None::<String>)
     } else {
       json_value_to_sea_value(json_val)
     };
     actives.set(col, new_val);
   }
}

actives.update(db).await?;
...
```
Any better suggestion?

https://github.com/qyihua/sea-orm/commit/0fa0f33ac1ebfa1444e8b4de1411a11e59bd4533

**Comment by billy1624** [comment]
Hey @qyihua, thanks for the suggestions!

Are you integrating sea-orm with other web API? I'm interested in your use case.

I think it's common to take a Json / key-value pair from user and updating the corresponding rows in the database.

**Comment by qyihua** [comment]
> Hey @qyihua, thanks for the suggestions!
> 
> Are you integrating sea-orm with other web API? I'm interested in your use case, can you tell me more?
> 
> I think it's common to take a Json / key-value pair from user and updating the corresponding rows in the database.

Hi, @billy1624 
I am integrating sea-orm with axum, 
demo web page like this:
![Screenshot_20211201_193024](https://user-images.githubusercontent.com/13034668/144228083-6a2f0489-ac66-4e02-ab72-d4d3cc44e24c.png)

it's very common to update dynamicly from json value in web api, so i need a None SeaValue.
I am not very familiar with github, i think i make a wrong commit

**Comment by billy1624** [comment]
Wow, you got some serious use case here!!

I'm thinking a mass assignment API similar to Laravel Eloquent, where you need to explicitly define what column is allowed to be mass assigned. Then, passing in a PHP array as input data.
- https://laravel.com/docs/8.x/eloquent#mass-assignment

We could did similar things in sea-orm
- explicitly define what column is allowed to be mass assigned
- taking in `serde_json::Value` as input
- returning `ActiveModel` fill with mass assigned values

@tyt2y3 any thoughts?

**Comment by qyihua** [comment]
- explicitly define what column is allowed to be mass assigned
  I think the columns can be changed at runtime, special in RBAC , diffirent role has diffirent permission, it need some variable vecs

**Comment by billy1624** [comment]
We could provide two methods for mass assignment
- `set_attributes(input: Json)` it will mass assign all keys defined in `fillable` vec
- `set_attributes_with_keys(input: Json, keys: &[Column])` it will mass assign all keys in `keys` slice
(I just name the method randomly, we can rethink it later)

**Comment by qyihua** [comment]
Hello, @billy1624 @tyt2y3 
I had make a commit for `set_from_json`.
Can you give me some suggestion ? Thank you.
https://github.com/qyihua/sea-orm/commit/6d3f693453f3897aaa49189b7ce4ec44d8bb782d
``` rust
struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub addr: Option<String>,
    pub other: Option<String>,
    ...
}
...
let allow_change_fields = vec![Column::Name, Column::Addr];

let mut actives = table::ActiveModel::new();
actives.set(Column::Id, 1.into());

// json is from user input, dynamic
let mut json = json!{addr: "new address"}; 
for col in allow_change_fileds{
   if let Some(json_val) =  json.get(col.to_string()) {
    // before
    /*
         let new_val = if json_val.is_null() {
           col.null_value() // Value::from(None::<i32>) or Value::from(None::<String>)
         } else {
           json_value_to_sea_value(json_val)
         };
         actives.set(col, new_val);
    */
    // now just one line
    actives.set_from_json(col, json_val)?;
   }
}
actives.update(db).await?;
...
```

**Comment by billy1624** [comment]
I'm checking the changes you made with following link
- https://github.com/SeaQL/sea-orm/compare/master...qyihua:test-json

It looks reasonable to me but I think we need some helper methods in `ActiveModel` as well. So, we don't need to manually iterate the attributes in it and update it one by one like you did here.

> ```rust
> // json is from user input, dynamic
> let mut json = json!{addr: "new address"}; 
> for col in allow_change_fileds{
>    if let Some(json_val) =  json.get(col.to_string()) {
>     // before
>     /*
>          let new_val = if json_val.is_null() {
>            col.null_value() // Value::from(None::<i32>) or Value::from(None::<String>)
>          } else {
>            json_value_to_sea_value(json_val)
>          };
>          actives.set(col, new_val);
>     */
>     // now just one line
>     actives.set_from_json(col, json_val)?;
>    }
> }
> actives.update(db).await?;
> ...
> ```

All in all, this is a good starting point & demo :))

**Comment by qyihua** [comment]
Thank you in advance for your attention to this issue. 
I think so. waiting for your good news :))

**Comment by tyt2y3** [comment]
Thank you for the contribution! I think this is pretty close.
Though, I believe there could be a way to avoid adding the impl inside the `DeriveActiveModel`.
Instead, I believe it is possible to default implement it inside `ActiveModelTrait` by relying on `set`.
And perhaps the method could be `set_json_value`.
Because in my opinion I thought `set_from_json` is a massive assignment that would iterate over the json keys.

**Comment by billy1624** [comment]
Hey @qyihua, please check PR #492

**Comment by qyihua** [comment]
Thank

> Hey @qyihua, please check PR #492

Hi, @billy1624 Thank you for your attention . The PR work for me

But in my use case, a web crawler, and the primary keys come from json. I think we also need to set primary keys come from json.
``` rust
       // Restore primary key values
        for (col, active_value) in primary_key_values {
            match active_value {
                ActiveValue::Unchanged(v) | ActiveValue::Set(v) => self.set(col, v),
                // NotSet => self.not_set(col),
                NotSet => (), // do nothing
            }
        }
```

**Comment by billy1624** [comment]
> But in my use case, a web crawler, and the primary keys come from json. I think we also need to set primary keys come from json.
> 
> ```rust
>        // Restore primary key values
>         for (col, active_value) in primary_key_values {
>             match active_value {
>                 ActiveValue::Unchanged(v) | ActiveValue::Set(v) => self.set(col, v),
>                 // NotSet => self.not_set(col),
>                 NotSet => (), // do nothing
>             }
>         }
> ```

If it's implemented in this way the `set_from_json` method might be confusing. Consider the following cases...

1. Given the original ActiveModel with primary key which is `NotSet`. After calling `set_from_json` method, primary key value will be `Set(JSON_primary_key_value)`

2. Given the original ActiveModel with primary key which is `Set(some_primary_key_value)` or `Unchanged(some_primary_key_value)`. After calling `set_from_json` method, primary key value will stay unchanged as `Set(some_primary_key_value)` or `Unchanged(some_primary_key_value)`

Thoughts? @qyihua @tyt2y3

**Comment by qyihua** [comment]
To case 1, we can implement an associated function named `from_json`, this function will not backup or restore primary key values.
What do you think about it?

**Comment by billy1624** [comment]
Hey @qyihua, yeah, this make sense. Check https://github.com/SeaQL/sea-orm/pull/492/commits/50aeb1c42631781341dfc8ef240b4e83f13a0563
