### ISSUE TITLE
Add Table on the generated Column enum

### ISSUE THREAD

**Issue by Sytten** [SeaQL/sea-orm#356]
This might seem weird, but it comes from a legit need to no change hundreds of lines of sea-query code.
Currently we have a lot of enums like:
```rust
#[derive(Iden, Clone)]
pub enum InterceptEntries {
    Table,
    Id,
    RequestId,
}
```
That we use like:
```rust
Query::select()
.column((InterceptEntries::Table, InterceptEntries::Id))
.column((InterceptEntries::Table, InterceptEntries::RequestId))
.from(InterceptEntries::Table)
// Wayyyy more code 
```

We want to use sea-orm for all the most simple use cases, but doing so would imply having to change all the `InterceptEntries::Table` to `intercept_entries::Entity` and `InterceptEntries::Id` to `intercept_entries::Column::Id`.
That is a lot of code for us.

A smoother transition would be to just change the import:
```rust
use entities::intercept_entries::Column as InterceptEntries;
```
But it would require the `Column` enum to have a `Table` field.

Maybe this could be a flag only for people that need it?

**Comment by billy1624** [comment]
As discussed on Discord. It's doable and we should implement it :P

**Comment by tyt2y3** [comment]
Great, and thanks for the PR

**Comment by tyt2y3** [comment]
[0.4.2](https://github.com/SeaQL/sea-orm/releases/tag/0.4.2)
