### ISSUE TITLE
Impl `IntoMockRow` on `FromQueryResult` derived structs so they can be supplied to `MockDatabase`'s `append_query_results()`

### ISSUE THREAD

**Issue by robot-head** [SeaQL/sea-orm#357]
Would it be possible to Impl `IntoMockRow` on `FromQueryResult` derived structs so they can be supplied to `MockDatabase`'s `append_query_results()`?

As it stands, it seems the only way to provide expectations for custom model selects is to use the `BTreeMap` `IntoMockRow` impl

**Comment by billy1624** [comment]
Hey @robot-head, can you explain more on your use case?

You can supply any `IntoMockRow ` into `append_query_results()`, including
- `MockRow`
- `ModelTrait`
- BTreeMap<&str, Value>

https://github.com/SeaQL/sea-orm/blob/871a5e8de646eca2d1669fe69235e277f27b679e/src/database/mock.rs#L182-L207

**Comment by robot-head** [comment]
Sorry for late response, confirming `BTreeMMap<&str, Value>` works just fine!

**Comment by tyt2y3** [comment]
Thank you for coming back
