### ISSUE TITLE
find_with_related panic

### ISSUE THREAD

**Issue by MorganNesbitt** [SeaQL/sea-orm#374]
Hey, I am new to sea-orm, so was looking to see if I could get some help around this.

I have two entities with a one to many relation (that I built using the cli generation).
I can fetch them both individually, but it panics when I try to join them together.

They are quite big structs, each with the following properties
- id is a uuid
- have one Postgres enum
- with the only overlapping fields being id and their respective createdAt and updatedAt.
- foreign key is on the relevant uuid of the other table.
- fields are camelCase

I'm using the column_name attribute to map from snake case in the struct to camel case in the db.

here is a variant of the query in question, but just building the query

```
    let query = CustomerEmployeeRecord::find()
        .find_with_related(HistoricalCustomerEmployeeRecord)
        .build(DbBackend::Postgres)
        .to_string();

```

Result:
```
thread 'main' panicked at 'cannot apply alias for expr other than Column'
```

any help we be greatly appreciated!

**Comment by billy1624** [comment]
Hey @MorganNesbitt, welcome! And thanks for the report. I'm digging into it right now

**Comment by tyt2y3** [comment]
[0.4.2](https://github.com/SeaQL/sea-orm/releases/tag/0.4.2)
