### ISSUE TITLE
Support `DateTime<Utc>` & `DateTime<Local>`

### ISSUE THREAD

**Issue by tyt2y3** [SeaQL/sea-orm#381]
I think we should support `DateTime<Utc>` natively in SeaORM soon

_Originally posted by @tyt2y3 in https://github.com/SeaQL/sea-orm/issues/344#issuecomment-991500315_

May be we can create a new type alias `DateTimeUtc` on `chrono::DateTime<Utc>`

**Comment by billy1624** [comment]
We may also support `DateTime<Local>`. Then, we have full support over all three `chrono::DateTime`, namely `DateTime<FixedOffset>`, `DateTime<Utc>` and `DateTime<Local>`.
