### ISSUE TITLE
connect by ip address

### ISSUE THREAD

**Issue by LucienGCW** [SeaQL/sea-orm#393]
use this:
`let db = Database::connect("postgresql://username:password@ipAddress/mydb").await.unwrap();`
Err:
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Conn("error occurred while attempting to establish a TLS connection: InvalidDNSNameError")'
but this is ok:
`let db = Database::connect("postgresql://username:password@domainName/mydb").await.unwrap();`
So, do I have to use the domain name?

**Comment by billy1624** [comment]
Hey @LucienGCW, welcome!! Thanks for reaching out. Can you see if this is helpful?

Related #310

**Comment by LucienGCW** [comment]
> Hey @LucienGCW, welcome!! Thanks for reaching out. Can you see if this is helpful?
> 
> Related #310

Oh,thanks.
The problem was solved when i use  "runtime-tokio-native-tls" instead of  "runtime-tokio-rustls",
