### ISSUE TITLE
Codegen `column_name` proc_macro attribute if column name isn't in snake case

### ISSUE THREAD

**Issue by billy1624** [SeaQL/sea-orm#395]
And a question I'm having, doesn't sea-orm-cli automatically generate the `column_name` ?

_Originally posted by @Gabriel-Paulucci in https://github.com/SeaQL/sea-orm/discussions/391#discussioncomment-1842047_

**Comment by Johann150** [comment]
I just got surprised by this when trying to implement something on a big legacy database whose structure I can not change. The code generation renaming columns in the code *without even telling me* means that the generated code does not work.

Please add this! 🙏

**Comment by billy1624** [comment]
Hey @Johann150, we are releasing this fix soon, in the next sprint.

Btw... at the meantime you can clone the PR #433, then install the updated CLI.

**Comment by Johann150** [comment]
Thank you 😃
