### ISSUE TITLE
Model with Generics

### ISSUE THREAD

**Issue by oscartbeaumont** [SeaQL/sea-orm#402]
I am working on a crate called [`async-graphql-relay`](https://github.com/oscartbeaumont/async-graphql-relay) and have recently redone the public API to make it less cumbersome to use (you can checkout the example folder in the repo). When doing this I introduced a type `RelayNodeID` which is generic on the Model so it is declared as `RelayNodeID<Self>`. This is done so that among other things all ID's returned from GraphQL are globally unique and contain information about the specific type they are. This type is a wrapper around a standard Uuidv4 and from a database perspective should be treated this way.

After chatting with @billy1624 he pointed me towards [this resource](https://github.com/SeaQL/sea-orm/blob/master/issues/324/src/model.rs) which shows how to implement `sea-orm` support for custom types. The issue I found with this is that my type is generic and this does not currently seem to be supported by `sea-orm`. When I run my code the `DeriveEntityModel` macro panics (refer to the code linked below).

I put together some code [here](https://gist.github.com/oscartbeaumont/94fc0412668609255df88f17a3de0cfa) which should help show the sort of syntax I am going for without all the complexity and macros of the `async-graphql-relay` codebase.

Thanks, @billy1624 for creating PR #400 which is going to be the fix for this.

**Comment by tyt2y3** [comment]
❄️🎄

**Comment by billy1624** [comment]
With #400 you could define the following:

```rust
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "model")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: AccountId<String>,
    pub name: String,
}
```

But not...

```rust
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "model")]
pub struct Model<T> {
    #[sea_orm(primary_key)]
    pub id: AccountId<T>,
    pub name: String,
}
```

So, I'm think should we also support the use of generics over Model? @tyt2y3

**Comment by oscartbeaumont** [comment]
PR #400 works perfectly for my usecase. Thanks, @billy1624.
Something to note was that although my original idea was `RelayNodeID<Self>` this causes a lot of issues because the ID field is copied to some SeaORM internal stuff (Eg. `ActiveModel`, etc) and those types do not satisfy the expected trait for my code. I fixed this easily by changing it to `RelayNodeID<Model>`. This could be worth noting in documentation although this is probably something a Rust developer would be able to work out.
