### ISSUE TITLE
Foreign key constraint collision when multiple keys exist between the same two tables

### ISSUE THREAD

**Issue by hlb8122** [SeaQL/sea-orm#405]
```rust
#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::account::Entity",
        from = "Column::Member1",
        to = "super::account::Column::Id"
    )]
    Member1,
    #[sea_orm(
        belongs_to = "super::account::Entity",
        from = "Column::Member2",
        to = "super::account::Column::Id"
    )]
    Member2,
}
```

generates

```
  CONSTRAINT "fk-team2-account" FOREIGN KEY ("member1") REFERENCES "account" ("id"),
  CONSTRAINT "fk-team2-account" FOREIGN KEY ("member2") REFERENCES "account" ("id")
```
which results in
```
error returned from database: constraint "fk-team2-account" for relation "team2" already exists
```

**Comment by billy1624** [comment]
Hey @hlb8122, I was thinking a new naming scheme for foreign keys.

What do you think if we employ the scheme below?

> How about `FK_TABLENAME_COLUMNNAME`?
> **K**eep **I**t **S**imple **S**tupid whenever possible.
> 
> https://stackoverflow.com/a/199504/7059723

**Comment by hlb8122** [comment]
Does this scheme prevent colisions in all cases?

What I was looking for when I noticed the collision was a way to do manual naming.

**Comment by billy1624** [comment]
> Does this scheme prevent colisions in all cases?

Not all cases, it's possible to create two foreign keys on the same local column and referencing two different foreign columns. But I would say this seems unlikely to happen in real life.

```sql
CONSTRAINT "fk-team2-member1" FOREIGN KEY ("member1") REFERENCES "account1" ("id")
CONSTRAINT "fk-team2-member1" FOREIGN KEY ("member1") REFERENCES "account2" ("id")
```

> What I was looking for when I noticed the collision was a way to do manual naming. I'm not sure whether this is possible in addition to this fix?

Yeah, it's possible to perform manual naming on `RelationDef`, I can add that.
