### ISSUE TITLE
Highlight how to solve N+1 class of problems

### ISSUE THREAD

**Issue by VaZark** [SeaQL/sea-orm#424]
Since SeaORM is not lazy and can use eager loading to fetch data, I'm assuming the classic N+1 problems that occur in most ORMs are completely sidestepped.

It will be useful for newcomers to learn the "standard" way to handle it if there is an explicit example in the docs.

**Comment by billy1624** [comment]
Hey @VaZark, sorry for the late reply.

For the eager loading of one to many relation, we use `find_with_related` method

```rust
let active_enum_with_children: Vec<(active_enum::Model, Vec<active_enum_child::Model>)> = ActiveEnum::find()
    .find_with_related(ActiveEnumChild)
    .all(db)
    .await?;
```

It will query all parents and its children in a single select query

```sql
SELECT `active_enum`.`id`              AS `A_id`,
       `active_enum`.`category`        AS `A_category`,
       `active_enum`.`color`           AS `A_color`,
       `active_enum`.`tea`             AS `A_tea`,
       `active_enum_child`.`id`        AS `B_id`,
       `active_enum_child`.`parent_id` AS `B_parent_id`,
       `active_enum_child`.`category`  AS `B_category`,
       `active_enum_child`.`color`     AS `B_color`,
       `active_enum_child`.`tea`       AS `B_tea`
FROM `active_enum`
         LEFT JOIN `active_enum_child` ON `active_enum`.`id` = `active_enum_child`.`parent_id`
ORDER BY `active_enum`.`id` ASC
```

Then, aggregate the result into the shape `Vec<(active_enum::Model, Vec<active_enum_child::Model>)>` by going through the query result linearly from start to end (as the query result is sorted in specific order `ORDER BY `active_enum`.`id` ASC`)

https://github.com/SeaQL/sea-orm/blob/76c0d7fff57fda617add443568f3fcbca29d1be2/src/executor/select.rs#L752-L786
