### ISSUE TITLE
sea-orm-cli passwordless database user causes "No password was found in the database url" error

### ISSUE THREAD

**Issue by jokil123** [SeaQL/sea-orm#435]
when you try to generate an entity using the `sea-orm-cli generate entity --database-url "mysql://root@localhost/<dbname>"` command it panics with the error `thread 'main' panicked at 'No password was found in the database url'`

is there some other way to log into a database user without a password?

**Comment by billy1624** [comment]
Hey @jokil123, could you try `mysql://root:@localhost/<dbname>`?

**Comment by jokil123** [comment]
`mysql://root:@localhost/<dbname>` will return the same error.
`mysql://root: @localhost/<dbname>` throws `error returned from database: 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)`

**Comment by Madoshakalaka** [comment]
As a temporary workaround, I can confirm a random password works for Postgres (like `postgres://Matt:anythingworks@localhost:5432/my_db`). According to @jokil123 though, it doesn't seem to work for MySQL.

**Comment by billy1624** [comment]
Thanks! @Madoshakalaka
It has been fixed on latest master.

As a temporary solution, you can install the fixed version of sea-orm-cli by running
```sh
cargo install sea-orm-cli --git https://github.com/SeaQL/sea-orm.git
```
