### ISSUE TITLE
`TryGetError` doesn't implement `std::error::Error`

### ISSUE THREAD

**Issue by 05storm26** [SeaQL/sea-orm#439]
`TryGetError` should implement `std::error::Error` similarly as `sqlx::DbErr` is implementing it:

```rust
impl std::error::Error for DbErr {}
```

Without it `TryGetError` cannot be used with `anyhow::Result`

**Comment by 05storm26** [comment]
Oh sorry `TryGetError` can already be converted into `DbErr` usint `into()`.

**Comment by billy1624** [comment]
Yeah, that's confusing. Good spotting!
