### ISSUE TITLE
How to Deserialize an ActiveModel ? and a request for Serialization examples

### ISSUE THREAD

**Issue by VaZark** [SeaQL/sea-orm#457]
I'm trying to implement a basic CRUD app and I'm a bit lost. I'm trying to create a REST API with Axum. I've been trying to use the `Json(new_active_model)`. Is this not supported by Serde yet ?

```rust
 let new_task = task::ActiveModel {
        title: Set(payload.title),
        text: Set(payload.text),
        ..Default::default()
    }
    .save(conn)
    .await
    .expect("could not insert task");

    // this will be converted into a JSON response
    // with a status code of `201 Created`
    (StatusCode::CREATED, Json(new_task))
```

Regardless of the problem that I'm facing, It'd be nice if the examples and/or docs were updated showing how to serialize and deserialize entities/models, as well as, examples for REST APIs

**Comment by billy1624** [comment]
Hey @VaZark, you can check web API demo in the `/examples` folder. Example for Actix, Rocket and Poem (#) are included

**Comment by VaZark** [comment]
hI @billy1624, I played with the examples but it seems like the underlying issue is `the trait Serialize is not implemented for task::ActiveModel`.  (I generated the model with the sea-orm-cli generate entity)

So can the ActiveModel add support for Serialize? Or can I convert an ActiveModel to just a Model and just use derive Serialize on it? 

I'm pretty new to rust so you can feel free to point out if I'm missing /misunderstanding something here

**Comment by billy1624** [comment]
If you want to get back the inserted / updated model in `Model` instead of `ActiveModel`. You can use `insert` / `update` method in sea-orm 0.5.x

**Comment by VaZark** [comment]
Thanks. Insert was what I needed to get it working. Is it not possible to make the `ActiveModel` support `Serialize`?

**Comment by billy1624** [comment]
> Thanks. Insert was what I needed to get it working. Is it not possible to make the `ActiveModel` support `Serialize`?

Is there any reason you need to `Serialize` `ActiveModel`? I guess what you need is just getting POST data (`Model` without primary key attribute if it's insert) from end user and responding the saved `Model`

**Comment by VaZark** [comment]
Yup. That's what I ended up doing. I was trying to come up with ways to not write new types by hand for each table.

**Comment by billy1624** [comment]
Nice! Feel free to ping us if you got any other questions :)
