### ISSUE TITLE
Query from raw SQL blows apart && operator in postgres

### ISSUE THREAD

**Issue by Rudi3** [SeaQL/sea-orm#470]
A query like https://www.sea-ql.org/SeaORM/docs/basic-crud/raw-sql/ using `from_raw_sql` with a supplied string containing a `&&` operator will fail, as it gets converted into `& &`.

(The same seems to be the case for other array related postgres operators)

I don't know where it happens, but it might be in `sqlx`. As far as I could tell, it just gets passed to `sqlx` as a string without being modified or formatted.

However, a plain `sqlx::query` doesn't seem to be affected by this (after a quick test).

**Comment by Rudi3** [comment]
I don't know where it happens, but it might be in sqlx. As far as I could tell, it just gets passed to sqlx as a string without being modified or formatted.

**Comment by Rudi3** [comment]
This seems to be a wrong report - it gets debug printed as `& &`, but it actually executes normally.

**Comment by billy1624** [comment]
Hey @Rudi3, thanks for the update :P
