### ISSUE TITLE
Surface max_lifetime connection option

### ISSUE THREAD

**Issue by Sytten** [SeaQL/sea-orm#475]
It is missing from the abstraction over sqlx, but is an important thing (specially for serverless)

**Comment by billy1624** [comment]
Hey @Sytten, thanks for pointing that out. We can add that, in the meantime you can use one of [`from_sqlx_*`](https://docs.rs/sea-orm/0.5.0/sea_orm/?search=from_sqlx_) conversion method to setup the connection with `max_lifetime` config.

REF: https://docs.rs/sqlx/latest/sqlx/pool/struct.PoolOptions.html#method.max_lifetime
