### ISSUE TITLE
Postgres JSONB support?

### ISSUE THREAD

**Issue by callym** [SeaQL/sea-orm#476]
I'm using sea-orm-cli to generate the entities for me, and I've got the following table in Postgres:

```sql
CREATE TABLE IF NOT EXISTS table (
  id UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  data JSONB NOT NULL DEFAULT '{}'::JSONB,
  PRIMARY KEY (id)
);
```

It generates the following:

```rust
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "table")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false)]
  pub id: Uuid,
  #[sea_orm(column_type = "Custom(\"jsonb\".to_owned())")]
  pub data: String,
}
```

Which then gives this error:

```
Query Error: error occurred while decoding column "data": mismatched types; Rust type `core::option::Option<alloc::string::String>` (as SQL type `TEXT`) is not compatible with SQL type `JSONB`
```

**Comment by billy1624** [comment]
Hey @callym, this has to be fixed in sea-orm-cli. As a temporary solution, can you change the generated code to below? Changing the `data: String` into `data: Json`.

```rust
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "table")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false)]
  pub id: Uuid,
  pub data: Json,
}
```

**Comment by callym** [comment]
Thanks, that seems to be working perfectly!

Is it possible to have `data: MyData` where `MyData` derives `serde::Deserialize`, and to have it "automatically" converted, instead of having to then have `serde_json::from_value(x).unwrap()` wherever I want to use it? Not sure if that's something that is supported and I'm missing it, isn't supported and is out of scope, or something that could potentially be added?

**Comment by billy1624** [comment]
> Is it possible to have `data: MyData` where `MyData` derives `serde::Deserialize`, and to have it "automatically" converted, instead of having to then have `serde_json::from_value(x).unwrap()` wherever I want to use it?

That would be nice! I think this is possible.

Related SeaQL/sea-query#185

**Comment by ammongit** [comment]
I'm also able to fix the entity file by manually changing the type to `JsonBinary` and using `serde_json::Value` instead of `String`. One strange thing is that it works fine for `JSON`, but `JSONB` columns trip it up.

**Comment by billy1624** [comment]
Hey @ammongit, I have written a demo #488. Seems that `JSONB` is working. I can insert a row with `JSONB` datatype and retrieve it from the db.

**Comment by ammongit** [comment]
Oh interesting, the `Json` datatype. Thanks, I'll look at this.

**Comment by billy1624** [comment]
I'm closing this. As `JSONB` datatype is working in the demo shown in #488
