### ISSUE TITLE
Where does a TableCreateStatement go?

### ISSUE THREAD

**Issue by alper** [SeaQL/sea-orm#478]
I want to create a new Model and have that create database tables as well.

I saw this: https://docs.rs/sea-query/0.20.0/sea_query/table/struct.TableCreateStatement.html

But where does it go? Will that automatically create a Model

**Comment by alper** [comment]
I put it in my main and ran it once just like the Axum example.

**Comment by alper** [comment]
Here's the line in the example: https://github.com/SeaQL/sea-orm/blob/master/examples/axum_example/src/main.rs#L37

Still not sure whether to run that on every application start or not.

**Comment by billy1624** [comment]
> Here's the line in the example: https://github.com/SeaQL/sea-orm/blob/master/examples/axum_example/src/main.rs#L37
> 
> Still not sure whether to run that on every application start or not.

In this demo, yes, we run the create table statement every time on application startup. As I said in [another discussion](https://github.com/SeaQL/sea-orm/discussions/481#discussioncomment-2035054), once we have migration (#335) in place. You could migrate the database once by hand via the migrator CLI. But I would say running the migration automatically on application startup would be better, this ensure you application is running against a database with up-to-date schema.
