### ISSUE TITLE
PaginatorTrait for SelectorRaw

### ISSUE THREAD

**Issue by cemoktra** [SeaQL/sea-orm#500]
Hi,

it seems this is not implemented at the moment, any plans on doing it?

**Comment by shinbunbun** [comment]
@billy1624 

Hi, I would like to contribute to solving this issue.
I have thought of the following implementation, but could you please let me know if there is another good way to implement it?

```rust
impl<'db, C, S> PaginatorTrait<'db, C> for SelectorRaw<S>
where
    C: ConnectionTrait,
    S: SelectorTrait + Send + Sync + 'db,
{
    type Selector = S;
    fn paginate(self, db: &'db C, page_size: usize) -> Paginator<'db, C, S> {
        let mut sql = self.stmt.sql.trim();
        if sql.starts_with("SELECT") || sql.starts_with("select") {
            sql = &sql[6..];
        }

        let mut query = SelectStatement::new();
        query.expr(Expr::cust(sql));

        Paginator {
            query,
            page: 0,
            page_size,
            db,
            selector: PhantomData,
        }
    }
}
```

**Comment by billy1624** [comment]
Hey @shinbunbun, thank you so much for reaching out!!

I think we can assume the statement is a select statement. We can explicitly mention this assumption on the method docs.

So, this part and be ignored.

```rs
if sql.starts_with("SELECT") || sql.starts_with("select") {
    sql = &sql[6..];
}
```

`Statement` might have `sea_query::Value` with it. So, we also need to pass it in (if any).
- https://docs.rs/sea-orm/0.6.0/sea_orm/struct.Statement.html
- https://docs.rs/sea-query/0.22.0/sea_query/expr/enum.SimpleExpr.html#variant.CustomWithValues

```rs
if have_values {
    query.expr(Expr::cust_with_values(sql, values));
} else {
    query.expr(Expr::cust(sql));
}
```

All in all your implementation looks good! :P

**Comment by shinbunbun** [comment]
@billy1624 

Thank you for your reply!
When we build a `SelectStatement`, it is automatically prefixed with `SELECT`. So, if I implement it as documented, the SQL statement generated will be, for example, `SELECT SELECT "cake". name" FROM "cake" GROUP BY "cake"." name"`. Therefore, I have implemented a process to eliminate the `SELECT`. Please point out if I am wrong as I may not have understood the intent of your comment.

- ref: <https://www.sea-ql.org/SeaORM/docs/basic-crud/raw-sql>

**Comment by shinbunbun** [comment]
@billy1624 
Sorry, I misunderstood your advice.
I have submitted a Pull Request and would like you to review it.

#617
