### ISSUE TITLE
Reduce database connections to 1 during codegen

### ISSUE THREAD

**Issue by benluelo** [SeaQL/sea-orm#511]
## Summary

Currently, the default connection pool of SQLx is used which defaults to 10 connections. This could be reduced to 1 since codegen only performs readonly requests.

## Motivation

This can cause issues with databases that limit the amount of connections (my personal use case is ElephantSQL free tier, which limits to 5 connections).

**Comment by billy1624** [comment]
I guess we can add a option for `sea-orm-cli` to limit the maximum number of connection
https://docs.rs/sea-orm/0.6.0/sea_orm/struct.ConnectOptions.html#method.max_connections
