### ISSUE TITLE
Better migration docs please!

### ISSUE THREAD

**Issue by MattGson** [SeaQL/sea-orm#512]
Right now, migrations looks like it contains some powerful features. 
Unfortunately is is very difficult to work out what to use and how to use it.

From what I can see the docs first suggest using sqlx migrations? https://www.sea-ql.org/SeaORM/docs/install-and-config/schema
So I wrote some migrations and now have some tables.

Then they tell me that it can generate entities from existing table: https://www.sea-ql.org/SeaORM/docs/generate-entity/sea-orm-cli
I obliged and now have code generated matching my tables.

Then I can create table from entity https://www.sea-ql.org/SeaORM/docs/generate-database-schema/create-table
(seems like we are going in circles)
Although the examples somewhat opaquely import what I assume are 'example entities' from an internal 'tests_cfg' module. This seems to require passing a non-existing `Entity` type into `create_table_from_entity` which was not generated in the previous step. It seems that this only exists in the so called `Expanded entity structure`.

Then I find that SeaORM has it's own migration tool in the docs. So I wonder if the previous docs were just out of date? https://www.sea-ql.org/SeaORM/docs/migration/setting-up-migration
This most confusingly suggests I need the entity classes before I can write the migrations?? (we're definitely going in circles now?)
I then try and wrap my head around why ` Table::create().table(Entity)` needs the opaquely imported `Entity` type again instead of just a string for the table name?? This feels like it's trying to be too clever.

I now get to the docs on writing migrations and find that they don't actually include any useful information on writing migrations, just how to set up the folder https://www.sea-ql.org/SeaORM/docs/migration/writing-migration
I see that SQL migrations are supported which honestly looks easier at this point than the schema builder.

At this point I'm basically going to give up and just use sqlx since it just does what it says on the box. Migrations are simple, writing them should too. I think SeaORM should provide clear paths for how to use migrations and Entities together.

When it comes to keeping ORM models in sync with schema I think there are 3 choices: 

- DB first and generate models (my preference for most projects). No worry about keeping in sync, happens automatically. You lose some small features like auto many-to-many relations. But when writing imperative migrations, keeping models in sync manually is very tedious.

- Entity first and generate migrations (good if the migration generator is good). This is essentially declarative diff based migrations. Much more difficult to implement well. https://entgo.io/docs/migrate is a good example.
If executed well then this is great, otherwise it's a nightmare as you end up writing manual migrations to clean up the mess. Note that you **MUST** use codegen here. No-one is going to trust generated migrations that they can't read first. In general I think code-gen is a better approach than macros but here it is a requirement. See https://www.prisma.io/

- Third choice is to manually write imperative migrations and manually keep ORM models in sync. This was good when Rails came out but now it is a pretty old-school approach and is very tedious. Avoid making this the default at all costs (right now it seems like this is where SeaORM is heading). 

Hope this feedback is helpful.

**Comment by billy1624** [comment]
Hey @MattGson, docs updated. See https://www.sea-ql.org/SeaORM/docs/install-and-config/schema

**Comment by tyt2y3** [comment]
I think being schema first is (or should) be the default path. So the difference only comes down to defining the schema in raw SQL or in a database-generic syntax (which sea-query provides) plus being a programming language that could do more than SQL.

The problem with `create_table_from_entity` is that it is only good for the first time. Once we have a live database, we can only write migrations to mutate the schema.

I don't think we will develop a migration generator though, it is a problem too complex to handle.

One interesting approach though, is that we can use a hand written Entity in the initial migration for a table to bootstrap a database. And subsequent migrations has to manually write `add_column` etc.
