### ISSUE TITLE
sea_orm::DatabaseConnection should implement `Clone` by default 

### ISSUE THREAD

**Issue by feelingnothing** [SeaQL/sea-orm#517]
Because `MockConnection` is under an `Arc` - `DatabaseConnection` can implement `Clone` by default
https://github.com/SeaQL/sea-orm/blob/f418c4e58069cb7ae42b79c721a44c8bb8915f1a/src/database/db_connection.rs#L18
https://github.com/SeaQL/sea-orm/blob/f418c4e58069cb7ae42b79c721a44c8bb8915f1a/src/database/db_connection.rs#L31

**Comment by billy1624** [comment]
Hey @feelingnothing, good observations! We have discussed it previously, see
- https://github.com/SeaQL/sea-orm/issues/438#issuecomment-1007968237

**Comment by billy1624** [comment]
How about we exclude `mock` feature from default feature? This way normal user will have cloneable `DatabaseConnection` out of the box.

**Comment by feelingnothing** [comment]
Sound cool, considering that not much people would write tests with `sea-orm` along the lines, but the main problem is that if person would have to write a test with it, that person would lose `Clone`, also the fact that it is a breaking change. My point on either making separate `MockDatabaseConnection` specifically for testing purposes, or making `Clone` a default for `DatabaseConnection`.
