### ISSUE TITLE
sea-orm-cli generate entity: auto_increment should be true?

### ISSUE THREAD

**Issue by conanchen** [SeaQL/sea-orm#527]
## Description

with sqlite schema : 
```
CREATE TABLE IF NOT EXISTS nodes(
   id INTEGER PRIMARY KEY NOT NULL,
   subject TEXT NOT NULL
);
```

## Steps to Reproduce

1. sea-orm-cli generate entity -o src/entity
2. check src/entity/nodes.rs
```
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "nodes")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false)]
  pub id: i32,
  pub subject: String,
 }
```
3. 

### Expected Behavior
the generated code should be true for auto_increment ?
```
 #[sea_orm(primary_key, auto_increment = true)]
  pub id: i32,
```
### Actual Behavior

 #[sea_orm(primary_key, auto_increment = false)]

### Reproduces How Often

yes

## Versions

❯ cargo tree | grep sea-

db-sea-orm v0.1.0 (/db-sea-orm)
├── sea-orm v0.6.0 (/github/SeaQL/sea-orm)
│   ├── sea-orm-macros v0.6.0 (proc-macro) (/github/SeaQL/sea-orm/sea-orm-macros)
│   ├── sea-query v0.21.0
│   │   ├── sea-query-derive v0.2.0 (proc-macro)
│   ├── sea-strum v0.23.0
│   │   └── sea-strum_macros v0.23.0 (proc-macro)

**Comment by billy1624** [comment]
Hey @conanchen, it's expected that the following Entity will be generated

```rust
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "nodes")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false)]
  pub id: i32,
  pub subject: String,
 }
```

As the primary key does not `AUTOINCREMENT`

```sql
CREATE TABLE IF NOT EXISTS nodes(
   id INTEGER PRIMARY KEY NOT NULL,
   subject TEXT NOT NULL
);
```

To make it `AUTOINCREMENT`, you should add the keyword

```sql
CREATE TABLE IF NOT EXISTS nodes(
   id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
   subject TEXT NOT NULL
);
```
