### ISSUE TITLE
Cascade

### ISSUE THREAD

**Issue by Ilqjx** [SeaQL/sea-orm#540]
Table Person
![image](https://user-images.githubusercontent.com/53934234/154426814-ad681874-b1b2-43ce-8d2d-d58ba1c6418a.png)

Table Animal
![image](https://user-images.githubusercontent.com/53934234/154426760-6c4bd898-f5a5-416a-8419-8429f2042a22.png)

The generated model is like this, I mean a person has many animals, but I don't see anything similar to the generation of `animals: Vec<Animal>`. If I want to get the animals under the person, how should I do it?
```rust
// person
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    pub name: String,
}

// animal
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    pub name: String,
    pub pid: i32,
}
```

**Comment by billy1624** [comment]
Hey @Ilqjx, you can select related models via lazy loading or eager loading.
More on https://www.sea-ql.org/SeaORM/docs/basic-crud/select#find-related-models

**Comment by Ilqjx** [comment]
Hello @billy1624, I know these two apis exist, what I want to know is can `animals: Vec<Animal>` be included in the generated struct. Like this:
```rust
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    pub name: String,
    pub animals: Vec<Animal>,
}
```
This will make it more convenient to obtain animals, such as `person.animals`.

**Comment by billy1624** [comment]
> This will make it more convenient to obtain animals, such as `person.animals`.

Similar feature is under development, see #415 for details

**Comment by Ilqjx** [comment]
Ok, thanks for your reply.

**Comment by Ilqjx** [comment]
Ok, thanks for your reply.
