### ISSUE TITLE
Generate database table from struct

### ISSUE THREAD

**Issue by Ilqjx** [SeaQL/sea-orm#550]
## Summary

Generate database table from structure.

## Motivation

The entities generated by sea-orm-cli are sometimes not very expected, and the structure of the generated entity needs to be modified or a structure is defined for conversion.

**Comment by Ilqjx** [comment]
> Hey @Ilqjx, yes you could!
> https://www.sea-ql.org/SeaORM/docs/generate-database-schema/create-table

It's not what I thought. Look this
```rust
#[sea_orm(table_name = "person")]
struct Person {
    #[sea_orm(primary_key)]
    id: Uuid,
    name: String,
}
```
Generate the person table in the database based on this Person struct.

**Comment by billy1624** [comment]
Yes, `create_table_from_entity` method does what you said.

Given you have a SeaORM entity defined.

https://github.com/SeaQL/sea-orm/blob/27143a8ddc3ffce03cfcd6e0e92d955006d4c6e8/src/tests_cfg/cake_filling_price.rs#L17-L25

You can use `create_table_from_entity` method to generate a SQL statement to create the table in the database.

```rs
use sea_orm::{tests_cfg::*, DbBackend, Schema, Statement};

let db_postgres = DbBackend::Postgres;
let schema = Schema::new(db_postgres);

assert_eq!(
    db_postgres.build(&schema.create_table_from_entity(CakeFillingPrice)),
    Statement::from_string(
        db_postgres,
        vec![
            r#"CREATE TABLE "public"."cake_filling_price" ("#,
            r#""cake_id" integer NOT NULL,"#,
            r#""filling_id" integer NOT NULL,"#,
            r#""price" decimal NOT NULL,"#,
            r#"CONSTRAINT "pk-cake_filling_price" PRIMARY KEY ("cake_id", "filling_id"),"#,
            r#"CONSTRAINT "fk-cake_filling_price-cake_id-filling_id" FOREIGN KEY ("cake_id", "filling_id") REFERENCES "cake_filling" ("cake_id", "filling_id")"#,
            r#")"#,
        ]
        .join(" ")
    )
);
```

**Comment by Ilqjx** [comment]
Of course this is not required, but it may be more convenient to use.

**Comment by tyt2y3** [comment]
I don't think we will provide such a "magical" API
