### ISSUE TITLE
Update / Delete by id

### ISSUE THREAD

**Issue by Ilqjx** [SeaQL/sea-orm#552]
Is there something like `find_by_id(1).one(&db)` for `update` and `delete`?

Look like `update_by_id(1).one(&db)` and `delete_by_id(1).one(&db)`.

**Comment by billy1624** [comment]
Hey @Ilqjx, interesting idea!

For delete, I think it's make sense to delete by id. I support adding a new API for it.

For update, I would say it's natural to select the ActiveModel from db then alter the row then save it back to db.

```rust
let orange: Option<fruit::Model> = Fruit::find_by_id(30).one(db).await?;
let orange: fruit::Model = orange.unwrap();

let res: DeleteResult = orange.delete(db).await?;
assert_eq!(res.rows_affected, 1);
```

Or, update any rows exists that match specific conditions.

```rust
// Bulk set attributes using ActiveModel
let update_result: UpdateResult = Fruit::update_many()
    .set(pear)
    .filter(fruit::Column::Id.eq(1))
    .exec(db)
    .await?;

// UPDATE `fruit` SET `cake_id` = NULL WHERE `fruit`.`name` LIKE '%Apple%'
Fruit::update_many()
    .col_expr(fruit::Column::CakeId, Expr::value(Value::Null))
    .filter(fruit::Column::Name.contains("Apple"))
    .exec(db)
    .await?;
```

I'm not sure how `update_by_id(1).one(&db)` would work? Can you explain more with it?

**Comment by Ilqjx** [comment]
Indeed, delete are useful and update are unnecessary.

**Comment by billy1624** [comment]
I will open this issue for contributions :)

**Comment by AbhijithGanesh** [comment]
I'd like to work on this @billy1624

**Comment by billy1624** [comment]
Hey @AbhijithGanesh, thanks for the interest!!

The `delete_by_id` API is under development by @ShouvikGhosh2048.

I saw your message on Discord, you want to work on the `update_by_id` API. However, as discussed above. Seems that it's not necessary to have the API. I wonder if you got any other thoughts on it?

**Comment by AbhijithGanesh** [comment]
I agree with llqjx
