### ISSUE TITLE
Failed to generate entities for large schema

### ISSUE THREAD

**Issue by milesgranger** [SeaQL/sea-orm#555]
## Description

When testing out the project, specifically generating entities for a schema we use which has nearly 1,000 tables, the following results:

```
$ sea-orm-cli generate entity -u $CONNECTION_URI -s big-schema -o src/models/replication/big-schema --compact-format
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: PoolTimedOut', /home/milesg/.cargo/registry/src/github.com-1ecc6299db9ec823/sea-schema-0.5.1/src/postgres/discovery/executor/real.rs:30:55
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

## Steps to Reproduce

Difficult, but generating a lot of tables, which may have hundreds of columns can reproduce this error.

### Expected Behavior

Same behavior (works) on small schemas with ~20 tables.

### Actual Behavior

`PoolTimedOut`

### Reproduces How Often

Every time.

## Versions

```
└── sea-orm v0.6.0
    ├── sea-orm-macros v0.6.0 (proc-macro)
    ├── sea-query v0.21.0
    │   ├── sea-query-derive v0.2.0 (proc-macro)
    ├── sea-strum v0.23.0
    │   └── sea-strum_macros v0.23.0 (proc-macro)
```

OS: Ubuntu 18
Database: PostgreSQL 12.7

**Comment by billy1624** [comment]
Hey @milesgranger, thanks for the report! Actually, we haven't try to run `sea-orm-cli generate entity` on a huge database. I think there are some bottleneck when querying the metadata from the information schemas. We would try to reproduce the errors with a large database then identify the bottleneck.

**Comment by tyt2y3** [comment]
The cause of failure may or may not be "large". It could be because of one table using an unsupported feature. So I think at least a minimum-reproducible schema be provided for this to be actionable. Please reopen if you have any updates

**Comment by milesgranger** [comment]
I think at least, a reasonable error should be produced if a table is using an unsupported feature, would you agree?

**Comment by tyt2y3** [comment]
Indeed
