### ISSUE TITLE
Be able to support Array in database

### ISSUE THREAD

**Issue by hf29h8sh321** [SeaQL/sea-orm#576]
## Summary

Be able to directly support Array in database

Such as `text[]`

## Additional Information

Right now it is represented by a custom `column_type = "Custom(\"array\".to_owned())"` and the type in struct is `String`, not `Vec<T>`

**Comment by billy1624** [comment]
Hey @hf29h8sh321, I assumed you mean supporting Array of some permitives for PostgreSQL?

**Comment by hf29h8sh321** [comment]
@billy1624 For example, `Vec<String>`

**Comment by billy1624** [comment]
Okay, this has been discussed before
- #151

**Comment by EtienneProthon** [comment]
Could we have an example of the workaround using Json type for the moment ? I need to store and array of enum and i can't find any example on array storage as json.

**Comment by billy1624** [comment]
Hey @EtienneProthon, please check #783

**Comment by negezor** [comment]
This is the only thing that prevents me from using sea-orm right now, because I need to work with the postgres array. I can't change the array to JSON in my tables. Is there a workaround to use an array without JSON? I'm interested in an int8 array.

**Comment by kudlatyamroth** [comment]
and array support was merged in sea-query: https://github.com/SeaQL/sea-query/pull/467 :)

**Comment by ikrivosheev** [comment]
@kudlatyamroth and released)

**Comment by kudlatyamroth** [comment]
@ikrivosheev in release 0.27 info there is no mention about it :)
so i assume that it was not included in 0.27, but if it is, its great news :)

**Comment by ikrivosheev** [comment]
@kudlatyamroth thank! I will edit Changelog!

**Comment by emmiegit** [comment]
Exciting! What is needed for sea-orm to support it now that sea-query has it?

**Comment by ikrivosheev** [comment]
@emmiegit you can look here: https://github.com/SeaQL/sea-orm/pull/985
