### ISSUE TITLE
sea-orm-cli: Ident cannot be a number

### ISSUE THREAD

**Issue by yb3616** [SeaQL/sea-orm#579]
## Description

Error reported with `sea-orm-cli` when there is one of the Enum variant is of integer / number in the sql table.

## Steps to Reproduce

Error reporeted when `'k1','k2'` changed to `'1', '2'`
![image](https://user-images.githubusercontent.com/8839021/156723477-1ee65ae9-8f7a-465a-9c49-d3b205debc16.png)

![image](https://user-images.githubusercontent.com/8839021/156723662-fd468ccf-90a6-49e3-b038-460b134b1ada.png)

### Expected Behavior

no errors

### Actual Behavior

![image](https://user-images.githubusercontent.com/8839021/156723338-c8f45dc9-c1f0-43d1-8d03-6cc65a5eca1b.png)

### Reproduces How Often

always 

## Versions

![image](https://user-images.githubusercontent.com/8839021/156723865-f1251574-5b74-4975-bc4a-64c3217fe17c.png)

## Additional Information

no

**Comment by billy1624** [comment]
Hey @yb3616, thanks! Please check #588
