### ISSUE TITLE
sea-orm-cli generate --with-serde does not work on Postegresql custom type

### ISSUE THREAD

**Issue by fistons** [SeaQL/sea-orm#581]
## Description
Using a Postgresql database, I have a custom type 
```sql
CREATE TYPE user_role AS ENUM ('basic', 'admin');
```
I'm using `sea-orm-cli generate entity --with-serde both -o entity/src` to build my entities and my custom type entity does not derive
Serialize/Deserialize, preventing my other entity relying on it to build.

## Steps to Reproduce

1. Create an enum type in Postegresql
2. Use this enum type in some other
3. Generate your entity with `sea-orm-cli generate entity --with-serde both -o entity/src`
4. Try to compile your project
5. You can't :(

### Expected Behavior
Here is the entity `sea-orm-cli` should build:

```rust
//! SeaORM Entity. Generated by sea-orm-codegen 0.6.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "user_role")]
pub enum UserRole {
    #[sea_orm(string_value = "admin")]
    Admin,
    #[sea_orm(string_value = "basic")]
    Basic,
}
```

### Actual Behavior

Here is what is generated

```rust
//! SeaORM Entity. Generated by sea-orm-codegen 0.6.0

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "user_role")]
pub enum UserRole {
    #[sea_orm(string_value = "admin")]
    Admin,
    #[sea_orm(string_value = "basic")]
    Basic,
}
```

### Reproduces How Often

Always

## Versions

sea-orm-cli 0.6.0
rustc 1.59.0 (9d1b2106e 2022-02-23)

**Comment by billy1624** [comment]
Hey @fistons, thanks for reporting!

Related Issue & PR:
- #461
- #463

**Comment by billy1624** [comment]
I'll close this issue as #463 was merged
