### ISSUE TITLE
`sea-orm-cli generate --expanded-format` panic when postgres table contains enum type

### ISSUE THREAD

**Issue by pymongo** [SeaQL/sea-orm#614]
## Description

```
2022-03-15T08:45:09.769986Z DEBUG sea_schema::postgres::discovery: PrimaryKey(PrimaryKey { name: "meal_price_pkey", columns: ["id"] })    
thread 'main' panicked at 'not implemented', /home/w/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/sea-orm-codegen-0.6.0/src/entity/column.rs:120:18
```

## Steps to Reproduce

1. postgres table with enum type field `create type status as enum('ok', 'error');`
2. sea-orm-cli generate --expanded-format

### Expected Behavior

no panic

### Actual Behavior

thread 'main' panicked at 'not implemented'

### Reproduces How Often

always

## Versions

sea-orm-cli 0.6.0

postgres version 13.6

**Comment by billy1624** [comment]
Hey @pymongo, thank for the report! Nice catch! Please try #624

**Comment by alexander-cingolani** [comment]
I've been experiencing this issue as well, using sea-orm-cli v0.11.2 and postgres 15.2.. Tried installing past versions, but either they didn't compile (versions < 0.9) or they just showed the same error.

**Comment by billy1624** [comment]
Hey @alexander-cingolani, could you please submit a new issues with a detailed error report?

**Comment by alexander-cingolani** [comment]
Sorry, my bad.. after looking into the issue further it turns out it was entirely my fault. (I wasn't running the tool in the correct directory.. 😬) I also found out that the panic was caused by an `interval`, not an `enum` as I first thought.
