### ISSUE TITLE
UUID fields are not serialized by .into_json() on queries

### ISSUE THREAD

**Issue by yashsamit** [SeaQL/sea-orm#619]
## Description

Datetime fields are not serialized by .into_json() on queries. Possible duplicate of #530.

## Steps to Reproduce

1. Add UUID in any Model(Entity)
2. Run into_json query
3. It will hide the UUID field. If into_json removed field comes back.

### Expected Behavior

It should convert UUID to string and should be visible in the final JSON output.

### Actual Behavior

The field is missing as explained above.

### Reproduces How Often
It can be reproduced every time.

## Versions
0.6

## Additional Information

```rust
#[sea_orm(table_name = "categories")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub api_key: Uuid,
    pub added: DateTime,
    pub updated: DateTime,
}

let db = &data.conn;
let  u = Uuid::parse_str(uuid.as_str()).expect("UUID is required!");
let category = Category::find()
        .filter(categories::Column::ApiKey.eq(u))
        .into_json()
        .one(db)
        .await
        .expect("category not found");
```

**Comment by billy1624** [comment]
Hey @yashsamit, thanks for the report! It would be fixed on #539
