### ISSUE TITLE
support longblob in mysql

### ISSUE THREAD

**Issue by hunjixin** [SeaQL/sea-orm#631]
## Summary

support longblob in mysql
## Motivation

blob is small, need long blob to store vec<u8>

**Comment by billy1624** [comment]
Hey @hunjixin, sorry for the delay. Yes, we definitely can bring this to SeaORM
- https://github.com/SeaQL/sea-query/pull/314

Please check this PR I just created:
- https://github.com/SeaQL/sea-orm/pull/850
