### ISSUE TITLE
CLI generate `Decimal` for column with `real` type in sqlite

### ISSUE THREAD

**Issue by duskmoon314** [SeaQL/sea-orm#637]
## Description

I have a table with a column whose type is `real`. When generating entities from it, CLI generates `Decimal` for the column. But according to [the doc of sqlite](https://www.sqlite.org/datatype3.html), the type of `real` is f64:

> REAL. The value is a floating point value, stored as an 8-byte IEEE floating point number.

## Steps to Reproduce

1. Create an SQLite database via `sqlite3 test1.db "CREATE TABLE FLOAT(x real);"`
2. Exec CLI to generate rust code. `sea-orm-cli generate entity -u sqlite:///path/to/test1.db -o test`
3. Check the rust code:

	  ```rust
	  //! SeaORM Entity. Generated by sea-orm-codegen 0.7.0
	  
	  use sea_orm::entity::prelude::*;
	  
	  #[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
	  #[sea_orm(table_name = "FLOAT")]
	  pub struct Model {
	      pub x: Option<Decimal>,
	  }
	  
	  #[derive(Copy, Clone, Debug, EnumIter)]
	  pub enum Relation {}
	  
	  impl RelationTrait for Relation {
	      fn def(&self) -> RelationDef {
	          panic!("No RelationDef")
	      }
	  }
	  
	  impl ActiveModelBehavior for ActiveModel {}
	  ```

### Expected Behavior

Maybe generate `f64`, I think.

```rust
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "FLOAT")]
pub struct Model {
    pub x: Option<f64>,
}
```

### Actual Behavior

CLI generates `Decimal`.

### Reproduces How Often

Every time for now.

## Versions

sea-orm-cli 0.7.1

**Comment by billy1624** [comment]
Hey @duskmoon314, sorry for the delay. The issue will be fixed by:
- https://github.com/SeaQL/sea-schema/pull/75

Thanks for the report!
