### ISSUE TITLE
Support schemas in queries

### ISSUE THREAD

**Issue by Acidic9** [SeaQL/sea-orm#65]
As far as I'm aware, there seems to be a lack of support for querying from schemas. For example, switching from public schema to a different schema.

A possible solution is that `EntityName` should support a new function called `schema_name` perhaps:
```rust
pub trait EntityName {
    fn schema_name(&self) -> Option<&str> {
        None
    }
}
```
Where `None` would not include a schema selector in the queries.. and `Some(&str)` would append the schema before the table name in queries.

This would change queries from:
```sql
SELECT "users"."id", "users"."email" FROM "users" ...
```
to:
```sql
SELECT "user"."users"."id", "user"."users"."email" FROM "user"."users" ...
-- or
SELECT "public"."users"."id", "public"."users"."email" FROM "public"."users" ...
```

**Comment by Acidic9** [comment]
It seems like the hack I described above no longer works.

**Comment by billy1624** [comment]
I think we should add the capability of prefixing schema name to SeaQuery first.

Then, we can have something like... in SeaORM?
```rust
impl EntityName for Entity {
    fn schema_name(&self) -> Option<&str> {
        Some("public")
    }

    fn table_name(&self) -> &str {
        "users"
    }
}
```

**Comment by tyt2y3** [comment]
I think SeaQuery already have that. I have done that previously for supporting SeaSchema.

**Comment by tyt2y3** [comment]
> I think we should add the capability of prefixing schema name to SeaQuery first.
> 
> Then, we can have something like... in SeaORM?
> 
> ```rust
> impl EntityName for Entity {
>     // With default implementation of returning `None`
>     fn schema_name(&self) -> Option<&str> {
>         Some("public")
>     }
> 
>     fn table_name(&self) -> &str {
>         "users"
>     }
> }
> ```

Totally agree your approach.

**Comment by billy1624** [comment]
I guess we need `schem_name` on each columns for the following use case:

```sql
SELECT public.actor.*
FROM public.actor, new_schema.actor
```

**Comment by billy1624** [comment]
If so, I guess we need... in SeaQuery

```rust
/// Column references
#[derive(Debug, Clone)]
pub enum ColumnRef {
    Column(DynIden),
    TableColumn(DynIden, DynIden),
    // New variant
    SchemaTableColumn(DynIden, DynIden, DynIden),
}
```

https://github.com/SeaQL/sea-query/blob/bab97eebbbf7581c9cefe0eeef24d636aac5dc65/src/types.rs#L47-L52

**Comment by billy1624** [comment]
Btw... I think we have to change the `RelationDef` to join table with schema prefix.

https://github.com/SeaQL/sea-orm/blob/af4fb2ab7df92131ebe140e53de7f15598b4bdf5/src/entity/relation.rs#L17-L22

**Comment by billy1624** [comment]
Should we support schema prefix in column expressions at this stage? @tyt2y3

**Comment by tyt2y3** [comment]
I agree that the `from_tbl` field of RelationDef has to be changed (perhaps simply to `Identity`)
And I think the scope of this issue is only about the table name

**Comment by billy1624** [comment]
If so, #74 is ready to merge
