### ISSUE TITLE
update clap to last version: clap = { version = "3.1.8",

### ISSUE THREAD

**Issue by cindRoberta** [SeaQL/sea-orm#664]
## Additional Information

[dependencies]
clap = { version = "3.1.8", features = ["derive"] }

**Comment by cindRoberta** [comment]
https://github.com/clap-rs/clap/discussions/3611

**Comment by ikrivosheev** [comment]
@cindRoberta I am working on this PR. I'll do it soon

**Comment by cindRoberta** [comment]
> @cindRoberta I am working on this PR. I'll do it soon

I'm too, do you want to exchange information? did you open a fork?

**Comment by ikrivosheev** [comment]
@cindRoberta Oh, then keep working, I'll take another task)

**Comment by billy1624** [comment]
Thanks!! @cindRoberta @ikrivosheev

**Comment by smonv** [comment]
@cindRoberta do you still working on this ?
