### ISSUE TITLE
The DeriveRelation macro fails to derive the Related trait

### ISSUE THREAD

**Issue by bkonkle** [SeaQL/sea-orm#669]
## Description

The documentation [here](https://www.sea-ql.org/SeaORM/docs/relation/one-to-many) indicates that it's not necessary to manually implement the `Related` trait if you're using the `DeriveRelation` input. In practice, however, I get a "trait not implemented" message when I omit it.

Thanks for an outstanding library, by the way!

## Steps to Reproduce

1. Add the `DeriveRelation` derive input to a `Relation` enum, and use the `has_many` attribute maco - [as seen in this demo repo](https://github.com/bkonkle/rust-example-caster-api/blob/main/libs/users/src/user_model.rs#L46-L51).
2. Remove the [`impl Related` definition](https://github.com/bkonkle/rust-example-caster-api/blob/main/libs/users/src/user_model.rs#L53-L57) from the code in the demo repo.
3. Run into compile errors:

```
   Compiling caster-users v0.1.0 (/home/brandon/code/caster-rust/libs/users)
error[E0277]: the trait bound `user_model::Entity: sea_orm::Related<_>` is not satisfied
  --> libs/users/src/users_service.rs:64:18
   |
64 |                 .find_with_related(role_grant_model::Entity)
   |                  ^^^^^^^^^^^^^^^^^ the trait `sea_orm::Related<_>` is not implemented for `user_model::Entity`
   |
note: required by a bound in `sea_orm::query::join::<impl sea_orm::Select<E>>::find_with_related`
  --> /home/brandon/.cargo/registry/src/github.com-1ecc6299db9ec823/sea-orm-0.7.1/src/query/join.rs:60:12
   |
60 |         E: Related<R>,
   |            ^^^^^^^^^^ required by this bound in `sea_orm::query::join::<impl sea_orm::Select<E>>::find_with_related`

error[E0277]: the trait bound `user_model::Entity: sea_orm::Related<_>` is not satisfied
  --> libs/users/src/users_service.rs:94:18
   |
94 |                 .find_with_related(role_grant_model::Entity)
   |                  ^^^^^^^^^^^^^^^^^ the trait `sea_orm::Related<_>` is not implemented for `user_model::Entity`
   |
note: required by a bound in `sea_orm::query::join::<impl sea_orm::Select<E>>::find_with_related`
  --> /home/brandon/.cargo/registry/src/github.com-1ecc6299db9ec823/sea-orm-0.7.1/src/query/join.rs:60:12
   |
60 |         E: Related<R>,
   |            ^^^^^^^^^^ required by this bound in `sea_orm::query::join::<impl sea_orm::Select<E>>::find_with_related`
```

### Expected Behavior

The documentation says "the following is equivalent to the above", so the code should work without the explicit `impl Relation` definition.

### Actual Behavior

The `impl Relation` definition is necessary.

### Reproduces How Often

Always reproducible. Can be seen in other areas of the demo codebase as well, such as in the [Episode model](https://github.com/bkonkle/rust-example-caster-api/blob/main/libs/shows/src/episode_model.rs).

## Versions

v0.7.1

## Additional Information

Rust 2021 edition

**Comment by tyt2y3** [comment]
I think this is more so a documentation error, because we don't auto generate `Related` trait impl. We only generate `RelationTrait` impl

**Comment by Occhioverde** [comment]
> we don't auto generate `Related` trait impl

Sorry for posting on an old issue, but may I ask why isn't the `DeriveRelation` macro deriving `Related` too?

Maybe I'm missing something that is already written in the documentation, but in my opinion, removing the need to manually derive `Related` multiple times would simplify the code and improve its readability.

**Comment by billy1624** [comment]
Hey @Occhioverde, we believe it's much easy for the user to view and change the `Related` impl directly. Instead of `DeriveRelation` macro deriving it implicitly. So, it's visibility and ease of maintenance over readability.

**Comment by Occhioverde** [comment]
Hi, @billy1624, thanks for your reply.

I can understand your position but, since all of the entities I wrote implemented the `Related` trait with a simple

```rust
impl Related<super::other::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Other.def()
    }
}
```

I think that SeaORM could provide at least a new `DeriveRelated` macro that can automatically write this simple snippet for each one of the elements in the `Relation` enum.

Again, maybe I'm missing out some problem that is preventing you from implementing something like this, but if you want to avoid to add this capability to `DeriveRelation`, adding a new derive macro can be a good solution to let the final developer choose between - quoting your message - ease of maintenance and readability.

**Comment by billy1624** [comment]
For simple one-to-many or many-to-one relation, yes, it's straightforward to provide a derive macros for the `Related` impls with a given `Relation` enum.

However, when we face more complex relation, let say...
- relation with additional condition: user have to decide which relation to be used?
  - https://github.com/SeaQL/sea-orm/blob/10a215d28e746b0fb8cdd82e9d146e6e8a82201a/src/tests_cfg/cake.rs#L17-L32
- M-to-N relation with intermediate table: we have no easy way to automatically derive this
  - https://github.com/SeaQL/sea-orm/blob/10a215d28e746b0fb8cdd82e9d146e6e8a82201a/src/tests_cfg/cake.rs#L34-L42

**Comment by tyt2y3** [comment]
Those two are good points. In some cases it's only possible to derive Linked

**Comment by billy1624** [comment]
Docs for `Linked`
- https://www.sea-ql.org/SeaORM/docs/relation/chained-relations/
- https://www.sea-ql.org/SeaORM/docs/relation/self-referencing/

**Comment by Occhioverde** [comment]
I understand. Maybe implementing a macro just for the simple relations isn't indeed that useful as it can create problems when more complex diagrams need to be implemented.
Thank you very much for taking the time to link me these cases.
