### ISSUE TITLE
SeaORM Entity Generator does not support Blob fields.

### ISSUE THREAD

**Issue by johnttan** [SeaQL/sea-orm#684]
This was observed with `sea-orm-cli generate entity` on a table with a `BLOB` field.

It generated a Model struct with this field

```
    #[sea_orm(column_type = "Custom(\"BLOB\".to_owned())")]
    pub blob_field: String,
```

**Comment by billy1624** [comment]
Hey @johnttan, thanks for the report! PR #685 should fix the issue.

You can try it by cloning the branch, then run `cargo run -- generate entity --database-url ...` on `sea-orm/sea-orm-cli` directory.
