### ISSUE TITLE
[BUG]migration in version 0.7 can not detect Mysql Derive

### ISSUE THREAD

**Issue by Goodjooy** [SeaQL/sea-orm#688]
## Description

In my new project. I uisng migration to manage my database model. but when I register all model to `Migrator`  and runing 
`sea-orm-cli migrate up`. it report error
```shell
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Conn("The connection string 'mysql://root:lib_pwd@localhost:3306/lib_db' has no supporting driver.")'
``` 

in another project witch uisng 0.6 of seaOrm can migration successfully

## Steps to Reproduce

1. prepare migration and add to `Migrator`
2. runing `sea-orm-cli migrate up`
3. it report that error

### Expected Behavior

apply migrate 

### Actual Behavior

report Error 
has no supporting driver.

### Reproduces How Often

100% happen in new project
never happen in another old project,but when update `sea-schema` to 0.7 same problem happen

## Versions

mysql : ` Ver 8.0.28 for Win64 on x86_64 (MySQL Community Server - GPL)`

dependence in migration crate
```rust
[dependencies]
sea-schema = { version = "0.7.1", default-features = false, features = [
    "migration",
    "debug-print",
] }
```
rustc version `rustc 1.62.0-nightly (1f7fb6413 2022-04-10)`

## Additional Information

it seems the error is from here 
https://github.com/SeaQL/sea-orm/blob/master/src/database/mod.rs#L71

when I write migrate in the start up in project , It can successfully connect to database and appling migrates
```rust
fn main() {
    let rt = tokio::runtime::Runtime::new().expect("StartUp Runtime Failure");

    rt.block_on(async {
        let conn = sea_orm::Database::connect("mysql://root:lib_pwd@localhost:3306/lib_db")
            .await
            .expect("Db Lose");

        migration::Migrator::up(&conn, None).await;

       // ...
    })
}
```
but when I copy the same code to the `main.rs` in `migration` , It do not work
```rust
#[async_std::main]
async fn main() {
    // cli::run_cli(Migrator).await;
    let conn = sea_orm::Database::connect("mysql://root:lib_pwd@localhost:3306/lib_db")
        .await
        .expect("Db Lose");

    Migrator::up(&conn, None).await;
}
```
----

through the source code https://github.com/SeaQL/sea-orm/blob/master/src/database/mod.rs#L56， I think the match can reach here if and only if Enable the `sqlx-mysql` feature,but in the [cargo.toml](https://docs.rs/crate/sea-schema/0.7.1/source/Cargo.toml) it only enable sea-orm `marco` feature and disable default feature. thus can cause `has no supporting driver`

**Comment by Goodjooy** [comment]
https://github.com/Goodjooy/sea-schema/commit/67dc5e31d5f5e7c8e50ca108896ce04ca65c39e7
I am try to fix the problem 
but I do not known wether is the best or not : (

**Comment by c4ys** [comment]
entity/Cargo.toml

```
[dependencies]
sea-orm = { version = "0.7.1", default-features = false, features = ["macros", "sqlx", "sqlx-sqlite", "sqlx-mysql", "sqlx-postgres", "runtime-tokio-native-tls", "debug-print"] }
```

**Comment by Goodjooy** [comment]
> 

do you mean add that to the `migration` crate in my project?

**Comment by billy1624** [comment]
Hey @Goodjooy, I don't think this is a bug. You need to add `sqlx-mysql` feature to your `sea-orm` dependency in `Cargo.toml`

**Comment by Goodjooy** [comment]
> Hey @Goodjooy, I don't think this is a bug. You need to add `sqlx-mysql` feature to your `sea-orm` dependency in `Cargo.toml`

I have a bit understand why the same code can work in my old porject but can not work in that

in that old project. The dependence of `migration` is 
```toml
[dependencies]
sea-schema = { version = "0.5.0", default-features = false, features = [ "migration", "debug-print" ] }

db-entity={path="../libs/db-entity"}
```
where `db-entity` is another crate setting all database model of sea-orm where the `sqlx-mysql` feature is enabled. when the `migration` see `db-entity` as dependence. the `db-entity` config of sea-orm will influence the feature flag of sea-orm in `sea-schema`, thus it can conncet to my database

---

I adding the crate holding my database models to `migration` dependence. It work as expect :)

**Comment by billy1624** [comment]
I admit it's quite confusing. Perhaps we can somehow highlight this in our docs? Any suggestions?

**Comment by Goodjooy** [comment]
> I admit it's quite confusing. Perhaps we can somehow highlight this in our docs? Any suggestions?

maybe you can add features like `migrate-mysql` to enable `sea-orm\sqlx-mysql`  to select the database Derive directly? 

And adding features `migrate-rustls` and `migrate-native-tls` to select the tls?

 migrate has it own `async-std` thus not need to select async runtime

----

when adding dependence, user can either using feature flag or introduce the "enity" crate 

"
If you are not going to add `entity` into dependences you can using feature flag `migrate-<DATABASE>` and `migrate- <TLS_LIB>` of `sea-schema`
***NOTE: you MUST use either adding `entity` into dependence or adding feature flag `migrate-<DATABASE>` and `migrate- <TLS_LIB>` of `sea-schema`***
 "

like this ^ ?
English is not my mother tongue ， there may have some wrong : (

**Comment by billy1624** [comment]
Conversation continue on SeaQL/sea-schema#63
