### ISSUE TITLE
Bump Uuid version to 1.0.0

### ISSUE THREAD

**Issue by boraarslan** [SeaQL/sea-orm#689]
## Summary

Bump [Uuid](https://crates.io/crates/uuid) dependency version to 1.0.0

## Motivation

Since version 1.0.0 is released 10 days ago, would you consider bumping the version? Staying in version 0.8 also prevents other apps that uses SeaORM to switch to Uuid 1.0.0.

**Comment by billy1624** [comment]
Hey @boraarslan, thanks for the reminder! We're waiting our upstream SQLx's `uuid` dependency to be updated before bumping the version on our side.

Blocked by launchbadge/sqlx#1821

**Comment by smonv** [comment]
> Hey @boraarslan, thanks for the reminder! We're waiting our upstream SQLx's `uuid` dependency to be updated before bumping the version on our side.
> 
> Blocked by [launchbadge/sqlx#1821](https://github.com/launchbadge/sqlx/pull/1821)

https://github.com/launchbadge/sqlx/pull/1821 merged. Do you need help to bump `uuid` for sea-orm? I can working on this issue.

**Comment by ahollmann** [comment]
There is no released version of sqlx with a bumped uuid dependency is blocked by https://github.com/launchbadge/sqlx/issues/1877.

**Comment by billy1624** [comment]
Hey everyone, SQLx 0.6.0 has been released. Changelog: https://github.com/launchbadge/sqlx/blob/main/CHANGELOG.md#060---2022-06-16

**Comment by smonv** [comment]
@billy1624 I'll try to create a PR to upgrade later today
