### ISSUE TITLE
Error for sqlx_migrations table when generating entities

### ISSUE THREAD

**Issue by heliumbrain** [SeaQL/sea-orm#69]
Hi guys!

Bumped in to a tiny error just now when trying to generate entities for my Postgres database. I've used sqlx-cli for the migrations.

```bash
❯ sea-orm-cli generate entity
Error writing files: failed to resolve mod `sqlx_migrations`: /Users/nilskanevad/projects/kekou-api does not exist
```

The default table name for sqlx migrations is `_sqlx_migrations` - Notice the underscore.

The codegen creates a `_sqlx_migrations.rs` file but the table_name is getting set to `sqlx_migrations`

```rust
//! src/entity/_sqlx_migrations.rs
impl EntityName for Entity {
  fn table_name(&self) -> &str {
    "sqlx_migrations"
  }
}
```

After changing the table name in my DB to `sqlx_migrations` instead of `_sqlx_migrations` and generating the entities again it works without a issue.

So, it seems that somewhere, somehow the cli/codegen gets confused by the "_" in the tablename. Can't find where in the code though

**Comment by billy1624** [comment]
Hi @heliumbrain, nice catch!

**Comment by tyt2y3** [comment]
But I guess it's better for us to simply ignore table names starting with underscore

**Comment by billy1624** [comment]
> But I guess it's better for us to simply ignore table names starting with underscore

The CLI will generate an entity file named `sqlx_migrations.rs` for `_sqlx_migrations` table, with

```rust
//! src/entity/sqlx_migrations.rs
impl EntityName for Entity {
  fn table_name(&self) -> &str {
    "_sqlx_migrations"
  }
}

```

**Comment by tyt2y3** [comment]
Yes but that's not what users want typically.

**Comment by billy1624** [comment]
You mean we should skip all tables names starting with underscore?

i.e. not generating entity files for these tables

**Comment by tyt2y3** [comment]
Yes that's what I meant.

**Comment by billy1624** [comment]
Perhaps we can add an `ignore` option?

```shell
sea-orm-cli generate entity --ignore '^_'
```

With default value `^_`.

Users can choose to override it by providing an empty regex expression, i.e. 
```shell
sea-orm-cli generate entity --ignore ''
```

Or, it would be better to explicitly disable it?
```shell
sea-orm-cli generate entity --no-ignore
```

**Comment by billy1624** [comment]
Hey @heliumbrain, I have published the fix. Please run `cargo install sea-orm-cli` to update the CLI.

**Comment by tyt2y3** [comment]
I think we don't need to overdo it for now.
Ignoring _ prefix tables is a reasonable behaviour.
At most add an 'include-hidden-tables' option is fine.

**Comment by billy1624** [comment]
> I think we don't need to overdo it for now.
> Ignoring _ prefix tables is a reasonable behaviour.
> At most add an 'include-hidden-tables' option is fine.

We can merge the PR then implement the new behavior
