### ISSUE TITLE
mismatched types; Rust type `core::option::Option<alloc::string::String>` (as SQL type `VARCHAR`) is not compatible with SQL type `VARBINARY`

### ISSUE THREAD

**Issue by ttys3** [SeaQL/sea-orm#704]
## Description

create table with field like `varbinary(20)` will result in error with `find_by_id(id)`
```
error occurred while decoding column
mismatched types; Rust type `core::option::Option<alloc::string::String>` (as SQL type `VARCHAR`) is not compatible with SQL type `VARBINARY`
```

## Steps to Reproduce

1. create table `demo` which has a `varbinary(20)` field

```sql
CREATE TABLE `demo` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `secret` varbinary(20) NOT NULL,
   PRIMARY KEY (`id`)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8
```

2. insert some demo data:

```sql
INSERT INTO demo (secret) VALUES (UNHEX('b2df817c8b751a3ae3d8ba1de4dc8369'));


select * from demo;
+----+------------------------------------+
| id | secret                             |
+----+------------------------------------+
| 1  | 0xb2df817c8b751a3ae3d8ba1de4dc8369 |
+----+------------------------------------+
```

3.  generate entity using cli:  `sea-orm-cli generate entity -t demo`

and we'll got 

```rust
//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "demo")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u32,
    #[sea_orm(column_type = "Custom(\"VARBINARY(20)\".to_owned())")]
    pub secret: String,
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
```

5.  fetch one row data:

```rust
use super::demo::Entity as Demo;

let hello: Option<demo::Model> = Demo::find_by_id(1).one(db).await?;
```

and we got the errror "mismatched types; Rust type core::option::Option<alloc::string::String> (as SQL type VARCHAR) is not compatible with SQL type VARBINARY"

### Expected Behavior

sea-orm-cli generate entity with table has `VARBINARY` fields execute `find_by_id` query has no problem

### Actual Behavior

sea-orm-cli generate entity with table has `VARBINARY` fields execute `find_by_id` query got  "mismatched types; Rust type core::option::Option<alloc::string::String> (as SQL type VARCHAR) is not compatible with SQL type VARBINARY"

### Reproduces How Often

always reproducible

**Comment by ikrivosheev** [comment]
Hello, @ttys3! Thank you for the report. Can write a small example which reproduces error?

**Comment by ikrivosheev** [comment]
And I think varbinary is not equal to String. You can use Binary instead of String.

**Comment by billy1624** [comment]
Hey @ttys3, I think `varbinary` should represented as `Vec<u8>` in Rust

**Comment by ttys3** [comment]
@ikrivosheev  @billy1624  I updated the issue with re-produce steps.

I think the problem is sea-orm-cli generate entity does not support table has VARBINARY fields
