### ISSUE TITLE
[CLI] Show progress when generating entity files

### ISSUE THREAD

**Issue by billy1624** [SeaQL/sea-orm#722]
## Motivation

The `sea-orm-cli generate entity` command doesn't show its progress such as which entity (db table) it's generating. Some time when it fail, user have no idea which db table is at fault and making it hard to debug.

## Proposed Solutions

- Display the progress when running the command and show info such as the table name and the specification of table columns that it's currently generating

## Additional Information

- Discussed and suggested on #702

**Comment by kyoto7250** [comment]
@billy1624 

Hello, I am interested in this issue.
I am new comer to contributing to this repository,  Could you tell me about it?

**Comment by billy1624** [comment]
Hey @kyoto7250, thanks for the interest!

I think there are two things we need to code.

First, log the table name and its column info of the generating entity.

- We could add the `tracing::info!` macro to https://github.com/SeaQL/sea-orm/blob/e00562695ebb99eca444acbce41aafd0c5f3d539/sea-orm-codegen/src/entity/writer.rs#L93-L111
- For example, in `sea-orm-migration` we have done something similar logging https://github.com/SeaQL/sea-orm/blob/e00562695ebb99eca444acbce41aafd0c5f3d539/sea-orm-migration/src/migrator.rs#L154-L157

Second, print log of log level `info` via `tracing_subscriber`.

- We could initialize the `tracing_subscriber` at the `else` part of https://github.com/SeaQL/sea-orm/blob/e00562695ebb99eca444acbce41aafd0c5f3d539/sea-orm-cli/src/commands.rs#L19-L24
- For example, https://github.com/SeaQL/sea-orm/blob/e00562695ebb99eca444acbce41aafd0c5f3d539/sea-orm-migration/src/cli.rs#L45-L54
