### ISSUE TITLE
sea-orm-migration should not depend on async-std

### ISSUE THREAD

**Issue by Sytten** [SeaQL/sea-orm#748]
## Description

The migrations should not depend on any async implementation.
What should instead be done is changing the template created on init to have the dependency and then remove it from the crate.

**Comment by billy1624** [comment]
Hey @Sytten, thanks for pointing that out, I agree with you. We should let user to decide the runtime :)

**Comment by billy1624** [comment]
Hey @Sytten, please check @Sytten
