### ISSUE TITLE
Escape column names that conflict with Rust keywords in CLI

### ISSUE THREAD

**Issue by Acidic9** [SeaQL/sea-orm#76]
When generating models with the sea-orm-cli, if you have a column with a name that conflicts with a Rust keyword, the cli crashes and is not handled correctly.

For example, an SQL table:
```
| column_name | data_type |
|-------------------------|
| id          | serial    |
| type        | varchar   |
```
I get an error:
```
11 | ... { pub id : i64 , pub type : Option < String > }
   |                          ^^^^ expected identifier, found keyword
```
This is caused because the column `type` conflicts with the Rust keyword `type`.

Any rust columns conflicting should be renamed to resolve this issue.
https://doc.rust-lang.org/reference/keywords.html

**Comment by tyt2y3** [comment]
Any suggestion on the naming convention? How about an underscore at the end?

**Comment by Acidic9** [comment]
I didn't make any suggestions for this because I am not sure 😄 

I guess `type_` with an underscore could work.. or `type_col` (adding `_col`). I'm not sure of any better options than these.

**Comment by billy1624** [comment]
I think we can leave it for the user to decide how to resolve the name conflict.

Personally think that neither `r#type` nor `type_` be a good option. For me, I would simply choose another name to avoid conflicting with Rust keywords.

```rust
#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel)]
pub struct Model {
    pub id: i32,
    pub type_of: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveCustomColumn)]
pub enum Column {
    Id,
    TypeOf,
}

impl IdenStatic for Column {
    fn as_str(&self) -> &str {
        match self {
            Self::TypeOf => "type",
            _ => self.default_as_str(),
        }
    }
}
```

**Comment by Acidic9** [comment]
The problem is that users will integrate existing databases with SeaORM.. and usually you don't want your framework / language to dictate your database, it should be flexible enough to avoid issues like this

**Comment by billy1624** [comment]
Good point!
