### ISSUE TITLE
When db is sqlite::memory:, `unique` constraints does not work.

### ISSUE THREAD

**Issue by wurikiji** [SeaQL/sea-orm#762]
## Description

The in-memory backend of SQLite3 supports `unique` constraints. But, when I use 

## Steps to Reproduce

Follow the below using sea-orm's methods.

1. create table a (a int primary key, b text unique);
2. insert into a values (10, "hi");
3. insert into a values (11, "hi");
4. select * from a;

### Expected Behavior

The result of step 4 should be a length of 1

### Actual Behavior

But sea-orm returns 2 rows with the same column value for `b`;

### Reproduces How Often

Every time I use sea-orm with `sqlite::memory:`. 

## Versions

DB: SQLite3 - :memory:
OS: MacOS 12.3.1.
sea-orm info
```
│   └── sea-orm-migration v0.8.2
│       ├── sea-orm v0.8.0
│       │   ├── sea-orm-macros v0.8.0 (proc-macro)
│       │   ├── sea-query v0.24.6
│       │   │   ├── sea-query-derive v0.2.0 (proc-macro)
│       │   │   ├── sea-query-driver v0.1.1 (proc-macro)
│       │   ├── sea-strum v0.23.0
│       │   │   └── sea-strum_macros v0.23.0 (proc-macro)
│       ├── sea-orm-cli v0.8.1
│       │   ├── sea-schema v0.8.0
│       │   │   ├── sea-query v0.24.6 (*)
│       │   │   └── sea-schema-derive v0.1.0 (proc-macro)
│       ├── sea-schema v0.8.0 (*)
├── sea-orm v0.8.0 (*)
```

**Comment by billy1624** [comment]
Hey @wurikiji, welcome and thanks for the report! I was not able to reproduce the behaviour. See #763

**Comment by billy1624** [comment]
Please reopen this if you have any updates
