### ISSUE TITLE
Migrate fresh not deleting postgres type

### ISSUE THREAD

**Issue by MaderNoob** [SeaQL/sea-orm#765]
## Description

If the migration creates postgres types, running `sea-orm-cli migrate fresh` will fail because it doesn't delete types, and it will say that the type already exists.

## Steps to Reproduce

1. Create a migration which creates a postgres type.
2. Run the migration `sea-orm-cli migrate up`
3. Try to run a fresh migration `sea-orm-cli migrate fresh`

### Expected Behavior

The fresh migration should work

### Actual Behavior

The fresh migration returns an error saying that the enum type already exists.

### Reproduces How Often

always

## Versions

│   └── sea-orm v0.8.0
│       ├── sea-orm-macros v0.8.0 (proc-macro)
│       ├── sea-query v0.24.6
│       │   ├── sea-query-derive v0.2.0 (proc-macro)
│       │   ├── sea-query-driver v0.1.1 (proc-macro)
│       ├── sea-strum v0.23.0
│       │   └── sea-strum_macros v0.23.0 (proc-macro)
│   ├── sea-orm-migration v0.8.2
│   │   ├── sea-orm v0.8.0 (*)
│   │   ├── sea-orm-cli v0.8.1
│   │   │   ├── sea-schema v0.8.0
│   │   │   │   ├── sea-query v0.24.6 (*)
│   │   │   │   └── sea-schema-derive v0.1.0 (proc-macro)
│   │   ├── sea-schema v0.8.0 (*)
├── sea-orm v0.8.0 (*)
├── sea-orm-rocket v0.5.0
│   └── sea-orm-rocket-codegen v0.5.0 (proc-macro)

`uname -a`
Linux arch 5.17.5-arch1-1 #1 SMP PREEMPT Wed, 27 Apr 2022 20:56:11 +0000 x86_64 GNU/Linux

`pacman -Q postgresql`
postgresql 14.2-1

## Additional Information

Types should be first deleted when running a fresh migration.

**Comment by billy1624** [comment]
Hey @MaderNoob, sorry for the delay. As discussed on Discord, we could delete all PostgreSQL types in current schema when calling `fresh` on migrator.
- https://github.com/SeaQL/sea-orm/blob/9983e5d4987149ad227ccf402e4cf2618a1dddc3/sea-orm-migration/src/migrator.rs#L130-L212

It would be a two steps process:
1. Select all type names out of PostgreSQL
2. Construct [delete type statement](https://docs.rs/sea-query/0.26.0/sea_query/extension/postgres/struct.TypeDropStatement.html) and execute it

**Comment by billy1624** [comment]
I'll open this issue for anyone who have interested in contributing :)

**Comment by ikrivosheev** [comment]
@karpa4o4 done!

**Comment by karpa4o4** [comment]
@ikrivosheev thanks

**Comment by billy1624** [comment]
Thanks for the interest! @karpa4o4
