### ISSUE TITLE
custom table names like  user1, user2,user... ， They all have same columns, but table name

### ISSUE THREAD

**Issue by langzime** [SeaQL/sea-orm#782]

**Comment by billy1624** [comment]
Hey @langzime, welcome! If I understand your question correctly:

```rs
macro_rules! def_entity {
    ($mod: ident, $table_name: literal) => {
        pub mod $mod {
            use sea_orm::entity::prelude::*;
    
            #[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
            #[sea_orm(table_name = $table_name)]
            pub struct Model {
                #[sea_orm(primary_key)]
                pub id: i32,
            }
    
            #[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
            pub enum Relation {}
    
            impl ActiveModelBehavior for ActiveModel {}
        }
    };
}

def_entity!(user, "user");
def_entity!(user1, "user1");
def_entity!(user2, "user2");
```

You can create a macro your own to define those entities with ease.

**Comment by langzime** [comment]
> Hey @langzime, welcome! If I understand your question correctly:
> 
> ```rust
> macro_rules! def_entity {
>     ($mod: ident, $table_name: literal) => {
>         pub mod $mod {
>             use sea_orm::entity::prelude::*;
>     
>             #[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
>             #[sea_orm(table_name = $table_name)]
>             pub struct Model {
>                 #[sea_orm(primary_key)]
>                 pub id: i32,
>             }
>     
>             #[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
>             pub enum Relation {}
>     
>             impl ActiveModelBehavior for ActiveModel {}
>         }
>     };
> }
> 
> def_entity!(user, "user");
> def_entity!(user1, "user1");
> def_entity!(user2, "user2");
> ```
> 
> You can create a macro your own to define those entities with ease.

but it adds a lot of repetition，

**Comment by langzime** [comment]
> Hey @langzime, welcome! If I understand your question correctly:
> 
> ```rust
> macro_rules! def_entity {
>     ($mod: ident, $table_name: literal) => {
>         pub mod $mod {
>             use sea_orm::entity::prelude::*;
>     
>             #[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
>             #[sea_orm(table_name = $table_name)]
>             pub struct Model {
>                 #[sea_orm(primary_key)]
>                 pub id: i32,
>             }
>     
>             #[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
>             pub enum Relation {}
>     
>             impl ActiveModelBehavior for ActiveModel {}
>         }
>     };
> }
> 
> def_entity!(user, "user");
> def_entity!(user1, "user1");
> def_entity!(user2, "user2");
> ```
> 
> You can create a macro your own to define those entities with ease.

I have 256 tables and other 128 tables
