### ISSUE TITLE
Support time 0.3.x

### ISSUE THREAD

**Issue by D1plo1d** [SeaQL/sea-orm#788]
The chrono crate causes `cargo-audit` to warn about RUSTSEC-2020-0071. Chrono also causes a warning about it's stdweb dependency being unmaintained.

If someone is able to enable `time 0.3.x` for this crate then it would resolve these cargo-audit issues.

Note: Since `sqlx::query!` overrides `time` (de-)seriaization with `chrono` when `chrono` is enabled ( https://github.com/launchbadge/sqlx#cargo-feature-flags ) it might be better to remove both from `sqlx-deps` and allow the user to choose between `chrono`, `time-0_2`, or `time-0_3` so that they can continue to use `sqlx::query!` outside of Sea Orm with the time library of their choice.

Related:
- https://github.com/chronotope/chrono/issues/602
- https://github.com/SeaQL/sea-query/issues/340
- https://github.com/SeaQL/sea-query/pull/341

**Comment by GiyoMoon** [comment]
> it might be better to remove both from `sqlx-deps` and allow the user to choose

I agree! It's currently not possible to remove `chrono` from the dependencies :/

**Comment by billy1624** [comment]
Hey everyone, SQLx 0.6.0 has been released. Changelog: https://github.com/launchbadge/sqlx/blob/main/CHANGELOG.md#060---2022-06-16

**Comment by billy1624** [comment]
`time` version bumped to 0.3
- https://github.com/SeaQL/sea-orm/pull/834
