### ISSUE TITLE
Does sea-orm-cli generate MigrationName by current datetime, not Fixed Date

### ISSUE THREAD

**Issue by baoyachi** [SeaQL/sea-orm#806]
code link:https://github.com/SeaQL/sea-orm/blob/fff738a706d8097bb2b92d7a1fad3b67c2cde653/sea-orm-cli/src/commands.rs#L232

Now:
<img width="1399" alt="image" src="https://user-images.githubusercontent.com/10433001/174709479-d0d932ee-b549-4310-933a-92201e74c42b.png">

Suggestion:

<img width="879" alt="image" src="https://user-images.githubusercontent.com/10433001/174709310-d51b2f8f-dc3f-4bcd-94b9-c3fee17e1929.png">

**Comment by billy1624** [comment]
Hey @baoyachi, sorry for the delay. Good suggestions! Actually, it's very similar to this feature: creating new migration file with filename of current date time
- https://github.com/SeaQL/sea-orm/pull/656
- This line, to be exact: https://github.com/SeaQL/sea-orm/pull/656/files#diff-0ad0c0489cc7359f48740c645608cad9aaf0318787c7d1b7fc0910828f2429e4R234

Btw... with this PR landed. We no longer has to specify name of the migration explicitly
- https://github.com/SeaQL/sea-orm/pull/736
- So, the template now becomes: https://github.com/SeaQL/sea-orm/blob/beef8211d82567858a9ea403d3cb7e54176fa92a/sea-orm-cli/template/migration/src/m20220101_000001_create_table.rs#L3-L4

**Comment by billy1624** [comment]
I'll open this for anyone who feel interested to contribute :)

**Comment by baoyachi** [comment]
I want try.

**Comment by billy1624** [comment]
Please go ahead! Thanks in advance! Feel free to ping me here or at Discord if you need help. Just open a draft PR and ask for comments / review :)

**Comment by billy1624** [comment]
Hey @baoyachi, I'll assign this to you
