### ISSUE TITLE
Table name not match in some examples

### ISSUE THREAD

**Issue by swaitw** [SeaQL/sea-orm#809]
## Description

try to run [axum-example](https://github.com/SeaQL/sea-orm/tree/master/examples/axum_example) which not work for me

fixed by change(https://github.com/SeaQL/sea-orm/blob/master/examples/axum_example/migration/src/m20220120_000001_create_post_table.rs):
`
#[derive(Iden)]
enum Post {
    Table,
    Id,
    Title,
    Text,
}
`
to 
`
#[derive(Iden)]
enum Posts {
    Table,
    Id,
    Title,
    Text,
}
`

or modify (https://github.com/SeaQL/sea-orm/blob/master/examples/axum_example/entity/src/post.rs) from
`
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "posts")]
pub struct Model {
    #[sea_orm(primary_key)]
    #[serde(skip_deserializing)]
    pub id: i32,
    pub title: String,
    #[sea_orm(column_type = "Text")]
    pub text: String,
}

`

to 

`
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "post")]
pub struct Model {
    #[sea_orm(primary_key)]
    #[serde(skip_deserializing)]
    pub id: i32,
    pub title: String,
    #[sea_orm(column_type = "Text")]
    pub text: String,
}

`

**Comment by billy1624** [comment]
Hey @swaitw, thanks for catching that. I will fix it in a bit!
