### ISSUE TITLE
sea-orm-cli does not process tables with system versioning enabled [mariadb]

### ISSUE THREAD

**Issue by mohs8421** [SeaQL/sea-orm#848]
I wanted to import a table that I generated on mariadb with system versioning feature (https://mariadb.com/kb/en/system-versioned-tables/), and was surprised that the entity file was not generated at all (there also was no error message about that).
After I dropped the system versioning for that table, it was recognized properly.

**Comment by billy1624** [comment]
Thanks! @mohs8421 I've just created PRs fixing it. You can try it out :)

> Running `sea-orm-cli` from source code
> - https://github.com/SeaQL/sea-orm/blob/master/CONTRIBUTING.md#running-sea-orm-cli-from-source-code
