### ISSUE TITLE
Compile error '`Sync` is not implemented' under tokio

### ISSUE THREAD

**Issue by Acidic9** [SeaQL/sea-orm#86]
Related issue: https://github.com/SeaQL/sea-query/issues/105

With the following function in a tokio async runtime, I get an error saying:
```
future created by async block is not `Send`
help: the trait `Sync` is not implemented for `(dyn Iden + 'static)`
```
```rust
async fn update(
    db: &DatabaseConnection,
    active_model: model::ActiveModel,
) -> Result<bool, Box<dyn std::error::Error>> {
    Entity::update(active_model)
        .exec(db)
        .await
        .map_err(Box::new)?;

    Ok(true)
}
```

SeaORM does not seem to be thread safe. Perhaps this is due to sea-query's Iden type.

**Comment by tyt2y3** [comment]
Can you setup an minimal reproducible example under /examples?

**Comment by Acidic9** [comment]
I've fixed it locally... the quick fix seems to be changing the definition of `trait Iden` in sea-query to:
```rust
pub trait Iden: Send + Sync {
    ...
}
```
This is to enforce the type is Sync

**Comment by tyt2y3** [comment]
Great finding. Can we instead do it inside SeaORM, changing IdenStatic instead of Iden?
```rust
pub trait IdenStatic: Iden + Copy + Debug + Send + Sync + 'static {
```

I am trying to understand the problem

**Comment by Acidic9** [comment]
I've tried removing Send + Sync from `Iden` trait in sea-query and adding it to `IdenStatic` like you suggested, but the errors come back.

T inside `Arc<T>` should be Send + Sync for the whole Arc to be Send + Sync, but it's not required.
https://doc.rust-lang.org/std/sync/struct.Arc.html#thread-safety
It says:
> `Arc<T>` will implement `Send` and `Sync` as long as the `T` implements `Send` and `Sync`. Why can’t you put a non-thread-safe type `T` in an `Arc<T>` to make it thread-safe? This may be a bit counter-intuitive at first: after all, isn’t the point of `Arc<T>` thread safety? The key is this: `Arc<T>` makes it thread safe to have multiple ownership of the same data, but it doesn’t add thread safety to its data.

**Comment by tyt2y3** [comment]
Okay, good to know. Thanks.

**Comment by tyt2y3** [comment]
Btw, any idea how can I add a test case to our test suite?

**Comment by Acidic9** [comment]
> Btw, any idea how can I add a test case to our test suite for this?

Perhaps just making a tokio app and executing your query in a tokio spawned task:
```rust
tokio::spawn(async move {
    MyEntity::find().one(&db).await;
})
.await;
```

**Comment by tyt2y3** [comment]
@billy1624 can we also run our test suite using tokio?

**Comment by billy1624** [comment]
> Planning to do so. Running doctest & unit test on all supported runtime.

See #91

**Comment by tyt2y3** [comment]
I verified that `thread-safe` on SeaQuery did solved the issue.
