### ISSUE TITLE
[sea-orm-cli] generate entity prints columns info with respect to `--date-time-crate` option

### ISSUE THREAD

**Issue by billy1624** [SeaQL/sea-orm#869]
## Motivation

Generating entity will prints the progress and column info. However, it does not respect the `--date-time-crate` option introduce in PR:
- https://github.com/SeaQL/sea-orm/pull/724

```
sea-orm-cli generate entity -u mysql://root:root@localhost/active_enum_tests --date-time-crate time
Generating satellite.rs
    > Column `id`: i32, auto_increment, not_null
    > Column `satellite_name`: String, not_null
    > Column `launch_date`: DateTimeUtc, not_null
    > Column `deployment_date`: DateTimeUtc, not_null
```

```
sea-orm-cli generate entity -u mysql://root:root@localhost/active_enum_tests --date-time-crate chrono
Generating satellite.rs
    > Column `id`: i32, auto_increment, not_null
    > Column `satellite_name`: String, not_null
    > Column `launch_date`: DateTimeUtc, not_null
    > Column `deployment_date`: DateTimeUtc, not_null
```

## Proposed Solutions

`get_info` method takes `DateTimeCrate` enum and pass it onto `get_rs_type` method (now hard coded as `DateTimeCrate::Chrono`.
- https://github.com/SeaQL/sea-orm/blob/c949a3367852d987469cef3c5e69174e1e665420/sea-orm-codegen/src/entity/column.rs#L167-L181

**Comment by billy1624** [comment]
Hi @anshulxyz, welcome! Please go ahead! Feel free to ping me if you need any help :)
Just open a draft PR and ask for help. Thanks!!

**Comment by nahuakang** [comment]
I'm so sorry about this bug 🙈 It was in the back of my mind but I think I forgot about it.

**Comment by billy1624** [comment]
Hey @nahuakang, it's not your fault! I should have catch that during the review phase loll
