### ISSUE TITLE
`ORDER BY` with `::integer`

### ISSUE THREAD

**Issue by penso** [SeaQL/sea-orm#878]
Hi,

Pgsql supports sorting like this for string columns: `ORDER BY column_name::integer` but I can't find a way to achieve that using sea orm. Any way I can?

**Comment by ikrivosheev** [comment]
@penso, hello! Yes, you can use method: https://docs.rs/sea-query/latest/sea_query/query/struct.SelectStatement.html#method.order_by_expr and `Expr::col(...).into_simple_expr().cast_as(...)`

**Comment by penso** [comment]
How am I supposed to use this? I tried:

```Rust
    let paginator = token::Entity::find()
        .filter(token::Column::CollectionAddr.eq(path.collection_addr.clone()))
         .order_by_expr(
             token::Column::TokenId.into_simple_expr(),
             sea_query::Order::Asc,
         )
        .paginate(db, per_page);
```

but not luck. A bit of documentation would be nice :)

**Comment by ikrivosheev** [comment]
@penso can you move this issue to sea-query? I add some more documentation.

**Comment by penso** [comment]
Well I feel stupid I just spent hours reading source code to understand where to put it, and this is how it should be done:

```Rust
    let paginator = token::Entity::find()
        .filter(token::Column::CollectionAddr.eq(path.collection_addr.clone()))
        .order_by_asc(
          Expr::col(entity::token::Column::TokenId)
             .into_simple_expr()
             .cast_as(Alias::new("integer")),
         )
        .paginate(db, per_page);
```

I think documentation would have been nice...
