### ISSUE TITLE
Sea-orm error handling is not friendly enough to distinguish SQL execution errors by type

### ISSUE THREAD

**Issue by step-baby** [SeaQL/sea-orm#881]
## Motivation

First of all, sea-orm is the orm framework I am looking forward to, and I have used this now. But I think this error handling is not friendly enough. It is impossible to judge the type of SQL execution error through an enumeration, such as the error of violating the unique constraint.

**Comment by billy1624** [comment]
Hey @step-baby, sorry for the delay. This is a good suggestions and it has been discussed before. Please check related thread below and let us know your opinions: 
- https://github.com/SeaQL/sea-orm/discussions/709
- https://github.com/SeaQL/sea-orm/pull/750

**Comment by tyt2y3** [comment]
Merge into https://github.com/SeaQL/sea-orm/issues/1194
