### ISSUE TITLE
Setting Up Migration

### ISSUE THREAD

**Issue by zbinhazzaa** [SeaQL/sea-orm#884]
### Expected Behavior
I run  
```
use migration::{Migrator, MigratorTrait};

let connection = sea_orm::Database::connect(&database_url).await?;
Migrator::up(&connection, None).await?;
```
I expected that at the end of the app the DB would close. 
### Actual Behavior
Db does not close at the end of the app and still has .shm and .wal files.
I had this problem trying to copy the Db after the migration ended.

**Comment by billy1624** [comment]
Hey @zbinhazzaa, thanks for the report! This has to do with the underlying database connector: SQLx.

Related Issues:
- https://github.com/launchbadge/sqlx/issues/1760
- https://github.com/launchbadge/sqlx/issues/272

I think at SeaORM we could introduce an async `close` method to close the connection.

**Comment by tyt2y3** [comment]
https://docs.rs/sea-orm/latest/sea_orm/entity/prelude/enum.DatabaseConnection.html#method.close
