### ISSUE TITLE
Represent several relations between same types

### ISSUE THREAD

**Issue by nicoulaj** [SeaQL/sea-orm#89]
Example problematic cases:

1. Entities A et B have several different many-to-many relations
2. Entity A has several one-to-many relations to entity B (Eg: `COUPLE.member1 -> USER` and `COUPLE.member2 -> USER`)

In these cases there are several issues:

1. the codegen uses A/B entity names to generate `Relation` variants, so we obtain duplicate variants. I guess it could use the join table or foreign key entity name
2. the `Related` trait is typed on A/B entities, so same issue. So I believe fixing this requires a breaking conception change...

**Comment by tyt2y3** [comment]
`Related` was not designed to support this scenario and I want to keep its current definition for it's simplicity of usage.
Goods news is, we had thought about how to define advanced relations with more than two level joins, and it would be another triat concept. Perhaps something like:

```rust
trait Linked {
    type FromEntity: EntityTrait;
    type ToEntity: EntityTrait;
    fn link() -> Vec<RelationDef>;
}
```

such that multiple `Link` could be defined between any pair of Entities.

**Comment by tyt2y3** [comment]
Some clarifications:

Related is for inherit relations, like order with order item and product with product attribute, basically an edge on the ER diagram.

While Linked is the pathway between any two Entity on the ERD, which can jump through multiple hops, and have multiple valid routes.

**Comment by tyt2y3** [comment]
We target to introduce new APIs in 0.2.0
Meanwhile you can use the 'nakes' join method (like in https://www.sea-ql.org/SeaORM/docs/advanced-query/more-join)
