### ISSUE TITLE
mssql support?

### ISSUE THREAD

**Issue by BezBIS** [SeaQL/sea-orm#900]
## Motivation
I was just wondering whether there is any possibility of supporting mssql in the future?
I'm currently working with a pre-existing SQLServer database using Tiberius, but it would be really nice to switch to letting something like sea-orm handle building my queries etc in a way which is database-agnostic.

I see that SQLx offers support for mssql now, but have no idea how difficult that would be to add.

**Comment by BezBIS** [comment]
> 
Hi, thank you for such a quick response!
I wholeheartedly agree with your stance; I'm, unfortuantely, just saddled with a legacy MS database at the moment. If I was in a position to build the whole system again I would definitly be using entirely open-source components.

**Comment by billy1624** [comment]
Thanks for the support! @BezBIS

**Comment by atomanV** [comment]
What is the plan for supporting MS SQLServer? would it be possible to support in later future? Thanks a lot!

**Comment by tyt2y3** [comment]
It might be remotely related to https://github.com/launchbadge/sqlx/discussions/1616

We have a half-baked MSSQL support SeaQuery. But not yet for SeaORM. A lot of things took our attention, and we *want* to make it a reality next year. It will likely be a closed beta initially, and if there is enough interest, I am sure SQLx team would like to make official support for MSSQL too.

**Comment by tyt2y3** [comment]
We are now offering closed beta of [SQL Server for SeaORM](https://www.sea-ql.org/SeaORM-X/) as mentioned in https://www.sea-ql.org/blog/2024-04-08-whats-new-in-seaorm-1.0-rc.x/#sql-server-support
