### ISSUE TITLE
Simple spelling issue on sea-orm-cli's toml file

### ISSUE THREAD

**Issue by pmnxis** [SeaQL/sea-orm#917]
## Description
There's `featrure` that is misspell of `feature` when generate migrator from `sea-orm-cli`.

## Steps to Reproduce
1. `sea-orm-cli migrate init`
2. `featrure` is in cargo.toml
```
  # Enable at least one `ASYNC_RUNTIME` and `DATABASE_DRIVER` feature if you want to run migration via CLI.
  # View the list of supported features at https://www.sea-ql.org/SeaORM/docs/install-and-config/database-and-async-runtime.
  # e.g.
  # "runtime-tokio-rustls",  # `ASYNC_RUNTIME` featrure
  # "sqlx-postgres",         # `DATABASE_DRIVER` feature
```

### Expected Behavior
Don't care, Because it's comment

### Actual Behavior
Don't care

### Reproduces How Often
Don't care

## Versions
Don't care, maybe master

## Additional Information
Would be resolve this by applying simple nit commit.

**Comment by billy1624** [comment]
Hey @pmnxis, thanks for catching this!!
