### ISSUE TITLE
Convert model to active model

### ISSUE THREAD

**Issue by zys864** [SeaQL/sea-orm#927]
## Motivation
Activemodel don't support Serialize, Deserialize. I deserialize json to Model and wan to insert to db.
There is any convinient wany to convert model to Active model?

**Comment by billy1624** [comment]
Hey @zys864, you could easily convert any `Model` into `ActiveModel` with `into_active_model` method.
_https://docs.rs/sea-orm/0.9.1/sea_orm/entity/trait.IntoActiveModel.html#tymethod.into_active_model_

**Comment by zys864** [comment]
thanks,it works.

**Comment by billy1624** [comment]
Welcome!
