### ISSUE TITLE
[SeaORM] Support `time` crate on SQLite

### ISSUE THREAD

**Issue by billy1624** [SeaQL/sea-orm#945]
Native support of `time` crate has been added in PR https://github.com/launchbadge/sqlx/pull/1865 and released as part of SQLx [0.6.1](https://github.com/launchbadge/sqlx/blob/main/CHANGELOG.md).

Now we could bind `time` on to SQLite query statement and get `time` from SQLite directly.

**Comment by anshulxyz** [comment]
Hi @billy1624 I would like to work on this.
I have small experience of working with SQLite and DateTime
- https://github.com/SeaQL/sea-orm/pull/910
- https://github.com/SeaQL/sea-query/pull/400

**Comment by billy1624** [comment]
Hey @anshulxyz, thanks for taking the initiative! Please go ahead :)

**Comment by billy1624** [comment]
Hey @anshulxyz, I'd like to pick up this issue if you haven't start working on it yet :)

**Comment by anshulxyz** [comment]
@billy1624 okay, go ahead! :D
