### ISSUE TITLE
[FeatureRequest] An option to generate migration file based on UTC time instead of LocalTime

### ISSUE THREAD

**Issue by Animeshz** [SeaQL/sea-orm#946]
## Motivation

The ordering of migrations may clutter, if people from different timezones are contributing to the same project.

A UTC universal time may be able to fix this.

## Proposed Solutions

While using the LocalTime we could change the timezone to +0:00 and then start formatting it to file name.

SystemTime and Instant from stdlib donot give easy access to format them to desired format atm.

## Additional Information

Originated from discussion #935.

**Comment by billy1624** [comment]
Hey @Animeshz, would you like to contribute? hahaa

**Comment by Animeshz** [comment]
Ya, sure!
