### ISSUE TITLE
Not compatible with the new version of rust nightly

### ISSUE THREAD

**Issue by phidiaLam** [SeaQL/sea-orm#954]
## Description
In the "2022-08-06' version of rust nightly. Seaorm cannot compile

## Steps to Reproduce

1. Upgrade to latest rust nightly which release in 2022-08-07
2. Run the program.

### Expected Behavior

successfully compiled

### Actual Behavior

Compilation failed

### Reproduces How Often

Everytime

## Versions

- rustc 1.65.0-nightly (2befdefdd 2022-08-06)
- cargo 1.65.0-nightly (4fd148c47 2022-08-03)
- sea-orm v0.9.1
- mysql 8.0.29
- Try in mac, windows10 and linux. 

## Additional Information

![image](https://user-images.githubusercontent.com/67498817/183575240-1a209db9-86b7-4c11-b970-01a3b93f399b.png)

**Comment by HigherOrderLogic** [comment]
This is an issue with the toolchain itself, see rust-lang/rust#100215 for more info.

**Comment by phidiaLam** [comment]
> This is an issue with the toolchain itself, see [rust-lang/rust#100215](https://github.com/rust-lang/rust/issues/100215) for more info.

Ok, Thank you very much!

**Comment by billy1624** [comment]
Thanks! @HigherOrderLogic

**Comment by billy1624** [comment]
I'll keep this issue open and wait for reply from the Rust team :)

**Comment by phidiaLam** [comment]
> I'll keep this issue open and wait for reply from the Rust team :) Thanks! @phidiaLam

I think versions after rustc 1.65.0-nightly (75b7e52e9 2022-08-13) are no longer a problem.
Or maybe Maybe after version 2022-08-10.
You can close this issue.
Thank you very much!!!

**Comment by billy1624** [comment]
Thanks for the ping! @phidiaLam
