### ISSUE TITLE
Directory in which `cargo install sea-orm-cli` compiles to

### ISSUE THREAD

**Issue by jxuanli** [SeaQL/sea-orm#956]
Hello, I am wondering which directory can I find the files created by `cargo install sea-orm-cli`? Thanks

**Comment by billy1624** [comment]
Hey @jxuanli, welcome! Interesting question! Why are you asking?

Anyways, you can find the location of `sea-orm-cli` binary in your file system with `which sea-orm-cli` command.

```console
$ which sea-orm-cli
/Users/billy/.cargo/bin/sea-orm-cli
```

**Comment by jxuanli** [comment]
The error I had was a system (windows x86) linking issue when compiling `sqlx-macros` but I dont want the compiled files to take extra space

**Comment by billy1624** [comment]
What's you Rust compiler version?

You can get that info by executing:
```shell
$ rustc -V
rustc 1.62.1 (e092d0b6b 2022-07-16)
```

**Comment by billy1624** [comment]
These issues might be related if you're on a older version of Rust:
- https://github.com/SeaQL/sea-orm/issues/875
- https://github.com/SeaQL/sea-orm/pull/938

**Comment by billy1624** [comment]
Hey @jxuanli, please reopen this if you still have questions :)
