### ISSUE TITLE
Does sea-orm open extension, Custom gen raw_sql and connection database? 

### ISSUE THREAD

**Issue by baoyachi** [SeaQL/sea-orm#957]
Now, I want use dameng database, but sea-orm not support. And `sqlx` also not support dameng database.

Does sea-orm open gen raw_sql trait, and connection databse trait. 
Then,I can solve the problem of SQL generation by myself：like `sea-query` crate. 
also open connection dabtase trait, I can use [odbc-api](https://crates.io/crates/odbc-api) solve database connection problem.

This is good idea to inprove sea-orm open ability. If your want, I can do this part.

What is my position?
* Reuse the api of sea-orm, no perception database in the business layer
* make sea-orm stronger scalability
* I don't want fork sea-orm, because the fork code cannot be merged into the main line and cannot be supported later
* I am optimistic about the sea-orm team, because I am also one of the contributors. Working together can go a long way

 @billy1624 @tyt2y3

**Comment by billy1624** [comment]
Is this related?
- https://github.com/SeaQL/sea-orm/issues/867

**Comment by baoyachi** [comment]
> Is this related?
> 
> - https://github.com/SeaQL/sea-orm/issues/867

yes
