### ISSUE TITLE
`fn column()` also handle enum type

### ISSUE THREAD

**Issue by tyt2y3** [SeaQL/sea-orm#960]
Looks like we are doing some magic inside `fn column_list(&self) -> Vec<SimpleExpr> {` of `select.rs`.
It should also be possible to do the same in `fn column()` ? @billy1624 
Then it will be transparent to the user?

_Originally posted by @tyt2y3 in https://github.com/SeaQL/sea-orm/discussions/843#discussioncomment-3370904_

**Comment by billy1624** [comment]
Good call!
