### ISSUE TITLE
[cli] Add `#[serde(skip_serializing)]` and `#[serde(skip_deserializing)]` to hidden collumns

### ISSUE THREAD

**Issue by HigherOrderLogic** [SeaQL/sea-orm#961]
## Motivation

Since we don't generate entity for hidden table (which has name starts with underscore) by default so it'd be good to add `#[serde(skip_serializing)]` and `#[serde(skip_deserializing)]` to hidden columns, too.

## Proposed Solutions

N/A

## Additional Information

N/A

**Comment by billy1624** [comment]
Hey @HigherOrderLogic, thanks for proposing this on Discord!

I'll open this for contributions! I second this as long as it's opt-in, i.e. feature is disabled by default and can be choose to enabled by will.

**Comment by Sculas** [comment]
You don't need to add both, adding `#[serde(skip)]` does the same.
