### ISSUE TITLE
how can i do for date_time default value of migration

### ISSUE THREAD

**Issue by ringrid** [SeaQL/sea-orm#963]
I don't know how do i add default value to type of date_time, eg:

```
...
.col(ColumnDef::new("op_time").date_time().default(???))
...
```

thanks

**Comment by billy1624** [comment]
Hey @ringrid, welcome! Got it resolved?

**Comment by ringrid** [comment]
@billy1624 no，I tried this method, but it becomes a fixed value, I have no any idea...

```
.col(
                        ColumnDef::new("op_time")
                            .date_time()
                            .default({
                                let now = OffsetDateTime::now_utc().to_offset(offset!(+8));
                                PrimitiveDateTime::new(now.date(), now.time()).to_string()
                            }),
                    )
```

do you have any better ideas?

**Comment by ringrid** [comment]
@billy1624 thank you , I found your answer of sea-query question #[346](https://github.com/SeaQL/sea-query/discussions/346),  I had resolved my question.

**Comment by billy1624** [comment]
Thanks for the updates :)
