### ISSUE TITLE
[codegen] Struct / enum derive `PartialEq` should also derive `Eq`

### ISSUE THREAD

**Issue by billy1624** [SeaQL/sea-orm#965]
## Motivation

New clippy lint was added in Rust 1.63.0. which checks for types that derive `PartialEq` and could implement `Eq`.

Example:

```rs
#[derive(PartialEq)]
struct Foo {
    i_am_eq: i32,
    i_am_eq_too: Vec<String>,
}
```

Do this instead:

```rs
#[derive(PartialEq, Eq)]
struct Foo {
    i_am_eq: i32,
    i_am_eq_too: Vec<String>,
}
```

## Proposed Solutions

Check `sea-orm-codegen` where `#[derive(PartialEq)]` should be changed to `#[derive(PartialEq, Eq)]`.

## Additional Information

Clippy lints index: https://rust-lang.github.io/rust-clippy/master/index.html#derive_partial_eq_without_eq

**Comment by baoyachi** [comment]
I‘m try

**Comment by billy1624** [comment]
Thanks! @baoyachi

**Comment by baoyachi** [comment]
Oh，I see you've done it。

**Comment by billy1624** [comment]
Nope, it's not

**Comment by billy1624** [comment]
https://github.com/SeaQL/sea-orm/pull/967 doesn't touch codegen code writer

**Comment by baoyachi** [comment]
I’m try

**Comment by baoyachi** [comment]
It's seem's touch sea-query create

```diff
...
/// Value variants
///
/// We want Value to be exactly 1 pointer sized, so anything larger should be boxed.
+ #[derive(Clone, Debug, PartialEq)]
pub enum Value {
    Bool(Option<bool>),
    TinyInt(Option<i8>),
    SmallInt(Option<i16>),
    Int(Option<i32>),
...
```

**Comment by baoyachi** [comment]
So，first need change sea-query?

**Comment by tyt2y3** [comment]
I don't think we need an option for this behaviour. It seems to be universally true that we want Eq and PartialEq wherever possible.

**Comment by billy1624** [comment]
There are only three place in the codegen we need to modify:
- https://github.com/SeaQL/sea-orm/blob/d262501a44c048ed36a17bbf661ced3c5193f455/sea-orm-codegen/src/entity/active_enum.rs#L33-L42
- https://github.com/SeaQL/sea-orm/blob/d262501a44c048ed36a17bbf661ced3c5193f455/sea-orm-codegen/src/entity/writer.rs#L387-L390
- https://github.com/SeaQL/sea-orm/blob/d262501a44c048ed36a17bbf661ced3c5193f455/sea-orm-codegen/src/entity/writer.rs#L623-L633

Btw... both `f32` and `f64` does not implement `Eq` but implemented `PartialEq`

**Comment by w93163red** [comment]
May I take this one? If I understand correctly, only the above files need to be changed?

**Comment by billy1624** [comment]
Hey @w93163red, sure! Please go ahead :)

**Comment by billy1624** [comment]
But note that if we have any `f32` / `f64` fields in the model, it shouldn't derive `PartialEq`.

**Comment by w93163red** [comment]
I submitted a PR. If you find anything wrong, please let me know. Thanks~

**Comment by billy1624** [comment]
Thanks! @w93163red Please check the comment: https://github.com/SeaQL/sea-orm/pull/988#pullrequestreview-1084965612
