### ISSUE TITLE
Invalid default value for 'updated_at'

### ISSUE THREAD

**Issue by zrz4066** [SeaQL/sea-orm#994]
If I use ”.col(ColumnDef::new(User::Created_at).date_time().not_null()) ”，It will work。it failed when Change to ".col(ColumnDef::new(User::Created_at).timestamp_with_time_zone().not_null())", error is "Exec("error returned from database: 1067 (42000): Invalid default value for 'updated_at'")"

![1661439352673](https://user-images.githubusercontent.com/16775484/186699270-bc4a218a-68cf-4157-81b2-1501ff916b36.png)

**Comment by billy1624** [comment]
Hey @zrz4066, my wild guess is that you're using MySQL as the database?

Similar issue has been discussed at https://github.com/SeaQL/sea-orm/pull/854.

My suggestion for you. Try adding a `.extra("DEFAULT CURRENT_TIMESTAMP()")` on both timestamp column. It's a workaround before this, https://github.com/SeaQL/sea-query/pull/428, lands.

**Comment by tyt2y3** [comment]
Close as duplicate

**Comment by dreamerlzl** [comment]
> 

Could we make this obvious somewhere in the tutorial or docs? 
Also, it shall be `.extra("default CURRENT_TIMESTAMP".to_string())`

**Comment by billy1624** [comment]
Hey @dreamerlzl, the workaround isn't need anymore after next SeaORM & SeaQuery release.
https://github.com/SeaQL/sea-query/blob/a7f2defac169c93f9b6a059264d9ba52aebb9b43/src/table/column.rs#L154-L161
